### ISSUE TITLE
<Timeout exceeded.><Terminated by signal 9 (Killed).> after update to (version: r2.10.1-1)

### ISSUE THREAD

**Issue by syswombat** [matteocorti/check_ssl_cert#102]
Hello
since the update to (version: r2.10.1-1)
i got sometimes the error 

Plugin Output
<Timeout exceeded.><Terminated by signal 9 (Killed).>

after a couple of day i comes back to ok and all green.

i did install it like this
http://wombat3.kozo.ch/j/icinga-list/9802-icinga2-ssl
have a nice day
vinc

**Comment by syswombat** [comment]
each time i call it with -d at the end it is not showing the error ;-(

**Comment by syswombat** [comment]
It stopps at the end 
will it try to connect with ipv6?


root@icinga2-01:/usr/lib/nagios/pluginsCustom# ./check_ssl_cert -H sirup.ch -d
[DBG] ROOT_CA =
[DBG] cURL binary needed. SSL Labs = , OCSP = 1
[DBG] cURL binary not specified
[DBG] cURL available: /usr/bin/curl
expect not available
timeout available (/usr/bin/timeout)
[DBG] perl available: /usr/bin/perl
[DBG] date available: /bin/date
found GNU date with timestamp support: enabling date computations
[DBG] check_ssl_cert version: 1.72.0
[DBG] OpenSSL binary: /usr/bin/openssl
[DBG] OpenSSL version: OpenSSL 1.1.0f  25 May 2017
[DBG] OpenSSL configuration directory: /usr/lib/ssl
[DBG] 0 root certificates installed by default
[DBG] System info: Linux icinga2-01.kozo.ch 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux
[DBG] Date computation: GNU
[DBG] '/usr/bin/openssl s_client' supports '-servername': using -servername sirup.ch
[DBG] '/usr/bin/openssl s_client' supports '-xmpphost': using -xmpphost sirup.ch
[DBG] temporary file /tmp/check_ssl_certK24QGe created
[DBG] temporary file /tmp/check_ssl_certNJQvcY created
[DBG] temporary file /tmp/check_ssl_certJDcG2d created
[DBG] temporary file /tmp/check_ssl_certpNZmfb created
downloading certificate to /tmp
[DBG] sirup.ch is not an IP address
[DBG] executing with timeout (45s): echo 'Q' | /usr/bin/openssl s_client   -connect sirup.ch:443 -servername sirup.ch -verify 6     2> /tmp/check_ssl_certNJQvcY 1> /tmp/check_ssl_certK24QGe
[DBG]   /usr/bin/timeout 45 /bin/sh -c "echo 'Q' | /usr/bin/openssl s_client   -connect sirup.ch:443 -servername sirup.ch -verify 6     2> /tmp/check_ssl_certNJQvcY 1> /tmp/check_ssl_certK24QGe"
[DBG] storing a copy of the retrieved certificate in sirup.ch.crt
[DBG] storing a copy of the OpenSSL errors in sirup.ch.error
parsing the x509 certificate file
[DBG] subject=CN = sirup.ch
[DBG] CN         = sirup.ch
[DBG] CA_O       = Let's Encrypt
[DBG] CA_CN      = Let's Encrypt Authority X3
[DBG] SERIAL     = 0324F0FEBE7359C2E1D0D9A82E50ECD51B1C
[DBG] FINGERPRINT= 6C:E6:02:F2:7C:0F:8F:77:39:68:28:66:D6:95:10:EB:4A:2E:23:3C
[DBG] OCSP_URI   = http://ocsp.int-x3.letsencrypt.org
[DBG] ISSUER_URI = http://cert.int-x3.letsencrypt.org/
[DBG]     Signature Algorithm: sha256WithRSAEncryption
[DBG] Date computations: GNU
The certificate will expire in 36 day(s)
[DBG] subjectAlternativeName = sirup.ch www.sirup.ch
[DBG] Checking expiration date
[DBG] Checking revokation via OCSP
[DBG] OCSP: fetching issuer certificate http://cert.int-x3.letsencrypt.org/ to /tmp/check_ssl_certJDcG2d
[DBG] executing with timeout (45s): /usr/bin/curl --silent --location http://cert.int-x3.letsencrypt.org/ > /tmp/check_ssl_certJDcG2d
[DBG]   /usr/bin/timeout 45 /bin/sh -c "/usr/bin/curl --silent --location http://cert.int-x3.letsencrypt.org/ > /tmp/check_ssl_certJDcG2d"
[DBG] OCSP: issuer certificate type:  data
[DBG] OCSP: converting issuer certificate from DER to PEM
[DBG] OCSP: storing a copy of the retrieved issuer certificate to cert.int-x3.letsencrypt.org
[DBG] OCSP: host = ocsp.int-x3.letsencrypt.org
[DBG] openssl ocsp supports the -header option
[DBG] openssl ocsp -header requires 'key=value'
[DBG] executing /usr/bin/openssl ocsp -no_nonce -issuer /tmp/check_ssl_certJDcG2d -cert /tmp/check_ssl_certK24QGe  -url http://ocsp.int-x3.letsencrypt.org  -header HOST=ocsp.int-x3.letsencrypt.org

**Comment by matteocorti** [comment]
You are testing with an old version 1.72.0. Please check again with 1.78.0.
