### ISSUE TITLE
long execution during check

### ISSUE THREAD

**Issue by sokol-44** [matteocorti/check_ssl_cert#105]
I got 10s wait time to get results.
On line 451
`
exec_with_timeout "$TIMEOUT" "echo '${HTTP_REQUEST}' | $OPENSSL s_client ${CLIENT} ${CLIENTPASS} -crlf -ign_eof -connect $HOST:$PORT ${SERVERNAME} -showcerts -verify 6 ${ROOT_CA} ${SSL_VERSION} ${SSL_VERSION_DISABLED} ${SSL_AU} 2> ${ERROR} 1> ${CERT}" `

Should be 
`exec_with_timeout "$TIMEOUT" "echo -e '${HTTP_REQUEST}' | ... `

Without **-e** echo will not interpret line endings and openssl will wait till natural/server close of connection

**Comment by matteocorti** [comment]
Thanks!
