### ISSUE TITLE
<Timeout exceeded.><Terminated by signal 9 (Killed).> after update to (version: r2.10.1-1) #102

### ISSUE THREAD

**Issue by syswombat** [matteocorti/check_ssl_cert#107]
same then there
<Timeout exceeded.><Terminated by signal 9 (Killed).> after update to (version: r2.10.1-1) #102
but closed to fast...

root@icinga2-01:/usr/lib/nagios/pluginsCustom# ./check_ssl_cert -H sirup.ch -d
[DBG] ROOT_CA =
[DBG] cURL binary needed. SSL Labs = , OCSP = 1
[DBG] cURL binary not specified
[DBG] cURL available: /usr/bin/curl
expect not available
timeout available (/usr/bin/timeout)
[DBG] perl available: /usr/bin/perl
[DBG] date available: /bin/date
found GNU date with timestamp support: enabling date computations
[DBG] check_ssl_cert version: 1.72.0
[DBG] OpenSSL binary: /usr/bin/openssl
[DBG] OpenSSL version: OpenSSL 1.1.0f  25 May 2017
[DBG] OpenSSL configuration directory: /usr/lib/ssl
[DBG] 0 root certificates installed by default
[DBG] System info: Linux icinga2-01.kozo.ch 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux
[DBG] Date computation: GNU
[DBG] '/usr/bin/openssl s_client' supports '-servername': using -servername sirup.ch
[DBG] '/usr/bin/openssl s_client' supports '-xmpphost': using -xmpphost sirup.ch
[DBG] temporary file /tmp/check_ssl_certK24QGe created
[DBG] temporary file /tmp/check_ssl_certNJQvcY created
[DBG] temporary file /tmp/check_ssl_certJDcG2d created
[DBG] temporary file /tmp/check_ssl_certpNZmfb created
downloading certificate to /tmp
[DBG] sirup.ch is not an IP address
[DBG] executing with timeout (45s): echo 'Q' | /usr/bin/openssl s_client   -connect sirup.ch:443 -servername sirup.ch -verify 6     2> /tmp/check_ssl_certNJQvcY 1> /tmp/check_ssl_certK24QGe
[DBG]   /usr/bin/timeout 45 /bin/sh -c "echo 'Q' | /usr/bin/openssl s_client   -connect sirup.ch:443 -servername sirup.ch -verify 6     2> /tmp/check_ssl_certNJQvcY 1> /tmp/check_ssl_certK24QGe"
[DBG] storing a copy of the retrieved certificate in sirup.ch.crt
[DBG] storing a copy of the OpenSSL errors in sirup.ch.error
parsing the x509 certificate file
[DBG] subject=CN = sirup.ch
[DBG] CN         = sirup.ch
[DBG] CA_O       = Let's Encrypt
[DBG] CA_CN      = Let's Encrypt Authority X3
[DBG] SERIAL     = 0324F0FEBE7359C2E1D0D9A82E50ECD51B1C
[DBG] FINGERPRINT= 6C:E6:02:F2:7C:0F:8F:77:39:68:28:66:D6:95:10:EB:4A:2E:23:3C
[DBG] OCSP_URI   = http://ocsp.int-x3.letsencrypt.org
[DBG] ISSUER_URI = http://cert.int-x3.letsencrypt.org/
[DBG]     Signature Algorithm: sha256WithRSAEncryption
[DBG] Date computations: GNU
The certificate will expire in 36 day(s)
[DBG] subjectAlternativeName = sirup.ch www.sirup.ch
[DBG] Checking expiration date
[DBG] Checking revokation via OCSP
[DBG] OCSP: fetching issuer certificate http://cert.int-x3.letsencrypt.org/ to /tmp/check_ssl_certJDcG2d
[DBG] executing with timeout (45s): /usr/bin/curl --silent --location http://cert.int-x3.letsencrypt.org/ > /tmp/check_ssl_certJDcG2d
[DBG]   /usr/bin/timeout 45 /bin/sh -c "/usr/bin/curl --silent --location http://cert.int-x3.letsencrypt.org/ > /tmp/check_ssl_certJDcG2d"
[DBG] OCSP: issuer certificate type:  data
[DBG] OCSP: converting issuer certificate from DER to PEM
[DBG] OCSP: storing a copy of the retrieved issuer certificate to cert.int-x3.letsencrypt.org
[DBG] OCSP: host = ocsp.int-x3.letsencrypt.org
[DBG] openssl ocsp supports the -header option
[DBG] openssl ocsp -header requires 'key=value'
[DBG] executing /usr/bin/openssl ocsp -no_nonce -issuer /tmp/check_ssl_certJDcG2d -cert /tmp/check_ssl_certK24QGe  -url http://ocsp.int-x3.letsencrypt.org  -header HOST=ocsp.int-x3.letsencrypt.org

**Comment by syswombat** [comment]
[DBG] executing /usr/bin/openssl ocsp -no_nonce -issuer /tmp/check_ssl_certVoABY2 -cert /tmp/check_ssl_cert8emZBx  -url http://ocsp.int-x3.letsencrypt.org  -header HOST=ocsp.int-x3.letsencrypt.org
**============There it takes 4 Minutes till feedback comes ==========================**
[DBG] OCSP: response = Response verify OK
[DBG] OCSP: response = /tmp/check_ssl_cert8emZBx: good
[DBG] OCSP: response =  This Update: Nov  6 22:00:00 2018 GMT
[DBG] OCSP: response =  Next Update: Nov 13 22:00:00 2018 GMT
SSL_CERT OK - x509 certificate 'kocher.photos' from 'Let's Encrypt Authority X3' valid until Jan 14 21:39:34 2019 GMT (expires in 67 days)|days=67;;;;
[DBG] cleaning up temporary files
[DBG]   /tmp/check_ssl_cert8emZBx
[DBG]   /tmp/check_ssl_certW1sPDw
[DBG]   /tmp/check_ssl_certVoABY2
[DBG]   /tmp/check_ssl_cert01nJdO

real    4m20.595s
user    0m0.016s
sys     0m0.000s

**Comment by matteocorti** [comment]
You are using version 1.72.0, the current version is 1.78.0. Please test with the latest version.

**Comment by syswombat** [comment]
No the file "check_ssl_cert" say 1.78.0 but it is also the only file i have on my server!

**Comment by syswombat** [comment]
strange - 
so again  and there is 1.78.0 but,  I do not complain about the plugin but, 
http://ocsp.int-x3.letsencrypt.org  needs a long time to send feedback. 

=================
# time ./check_ssl_cert -H imkerei-kocher.ch -d
[DBG] ROOT_CA =
[DBG] cURL binary needed. SSL Labs = , OCSP = 1
[DBG] cURL binary not specified
[DBG] cURL available: /usr/bin/curl
expect not available
timeout available (/usr/bin/timeout)
[DBG] perl available: /usr/bin/perl
[DBG] date available: /bin/date
found GNU date with timestamp support: enabling date computations
**[DBG] check_ssl_cert version: 1.78.0**
[DBG] OpenSSL binary: /usr/bin/openssl
[DBG] OpenSSL version: OpenSSL 1.1.0f  25 May 2017
[DBG] OpenSSL configuration directory: /usr/lib/ssl
[DBG] 0 root certificates installed by default
[DBG] System info: Linux icinga2-01.kozo.ch 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux
[DBG] Date computation: GNU
[DBG] '/usr/bin/openssl s_client' supports '-servername': using -servername imkerei-kocher.ch
[DBG] '/usr/bin/openssl s_client' supports '-xmpphost': using -xmpphost imkerei-kocher.ch
[DBG] temporary file /tmp/check_ssl_certeXvaJu created
[DBG] temporary file /tmp/check_ssl_certorrNZO created
[DBG] temporary file /tmp/check_ssl_cert2lFlNq created
[DBG] temporary file /tmp/check_ssl_certHr9FUt created
downloading certificate to /tmp
[DBG] imkerei-kocher.ch is not an IP address
[DBG] executing with timeout (15s): echo -e 'HEAD / HTTP/1.1
Host: imkerei-kocher.ch
User-Agent: check_ssl_cert/1.78.0
Connection: close

' | /usr/bin/openssl s_client   -crlf -ign_eof -connect imkerei-kocher.ch:443 -servername imkerei-kocher.ch -showcerts -verify 6     2> /tmp/check_ssl_certorrNZO 1> /tmp/check_ssl_certeXvaJu
[DBG]   /usr/bin/timeout 15 /bin/sh -c "echo -e 'HEAD / HTTP/1.1
Host: imkerei-kocher.ch
User-Agent: check_ssl_cert/1.78.0
Connection: close

' | /usr/bin/openssl s_client   -crlf -ign_eof -connect imkerei-kocher.ch:443 -servername imkerei-kocher.ch -showcerts -verify 6     2> /tmp/check_ssl_certorrNZO 1> /tmp/check_ssl_certeXvaJu"
[DBG] storing a copy of the retrieved certificate in imkerei-kocher.ch.crt
[DBG] storing a copy of the OpenSSL errors in imkerei-kocher.ch.error
parsing the x509 certificate file
[DBG] subject=CN = imkerei-kocher.ch
[DBG] CN         = imkerei-kocher.ch
[DBG] CA         = Let's Encrypt Authority X3
[DBG] CA         = DST Root CA X3
[DBG] SERIAL     = 03A5D54919798D6B9DA3EF67E097CC694573
[DBG] FINGERPRINT= C9:BB:69:26:D6:BB:C7:2D:1B:C0:4A:01:E2:63:27:3E:56:E9:B6:CA
[DBG] OCSP_URI   = http://ocsp.int-x3.letsencrypt.org
[DBG] ISSUER_URI = http://cert.int-x3.letsencrypt.org/
[DBG]     Signature Algorithm: sha256WithRSAEncryption
[DBG] Date computations: GNU
The certificate will expire in 61 day(s)
[DBG] subjectAlternativeName = imker-ausbildung.ch imkerei-kocher.ch stadt-imkerei.ch stadtimkerei.ch wbzv.ch www.imker-ausbildung.ch www.imkerei-kocher.ch www.stadt-imkerei.ch www.stadtimkerei.ch www.wbzv.ch
[DBG] Checking expiration date
[DBG] Checking revokation via OCSP
[DBG] OCSP: fetching issuer certificate http://cert.int-x3.letsencrypt.org/ to /tmp/check_ssl_cert2lFlNq
[DBG] executing with timeout (15s): /usr/bin/curl --silent --location http://cert.int-x3.letsencrypt.org/ > /tmp/check_ssl_cert2lFlNq
[DBG]   /usr/bin/timeout 15 /bin/sh -c "/usr/bin/curl --silent --location http://cert.int-x3.letsencrypt.org/ > /tmp/check_ssl_cert2lFlNq"
[DBG] OCSP: issuer certificate type:  data
[DBG] OCSP: converting issuer certificate from DER to PEM
[DBG] OCSP: storing a copy of the retrieved issuer certificate to cert.int-x3.letsencrypt.org
[DBG] OCSP: host = ocsp.int-x3.letsencrypt.org
[DBG] openssl ocsp supports the -header option
[DBG] openssl ocsp -header requires 'key=value'
[DBG] executing /usr/bin/openssl ocsp -no_nonce -issuer /tmp/check_ssl_cert2lFlNq -cert /tmp/check_ssl_certeXvaJu  -url http://ocsp.int-x3.letsencrypt.org  -header HOST=ocsp.int-x3.letsencrypt.org
[DBG] OCSP: response = Response verify OK
[DBG] OCSP: response = /tmp/check_ssl_certeXvaJu: good
[DBG] OCSP: response =  This Update: Nov 10 10:00:00 2018 GMT
[DBG] OCSP: response =  Next Update: Nov 17 10:00:00 2018 GMT
SSL_CERT OK - x509 certificate 'imkerei-kocher.ch' from 'Let's Encrypt Authority X3' valid until Jan 12 09:09:03 2019 GMT (expires in 61 days)|days=61;;;;
[DBG] cleaning up temporary files
[DBG]   /tmp/check_ssl_certeXvaJu
[DBG]   /tmp/check_ssl_certorrNZO
[DBG]   /tmp/check_ssl_cert2lFlNq
[DBG]   /tmp/check_ssl_certHr9FUt

real    4m32.015s
user    0m0.012s
sys     0m0.012s

**Comment by matteocorti** [comment]
Strange I get
```
real	0m11.500s
user	0m3.334s
sys	0m7.606s
```
also checking `http://ocsp.int-x3.letsencrypt.org`

One problem for sure is that at the moment the OCSP check is not wrapped and checked for a timeout. But we have to discover why it's taking so long.

**Comment by matteocorti** [comment]
The version that I am using is much older (I am on macOS). I'll check tomorrow with Linux if I can reproduce the issue.

**Comment by matteocorti** [comment]
It's strange. In my case it's faster but it fails:

```
[DBG] Checking revokation via OCSP
[DBG] OCSP: fetching issuer certificate http://cert.int-x3.letsencrypt.org/ to /var/folders/sq/sb7jrfk14qv7yyh9z55mszp40000gn/T/check_ssl_certXXXXXX.0m8k1ccs
[DBG] executing with timeout (15s): /usr/bin/curl --silent --location http://cert.int-x3.letsencrypt.org/ > /var/folders/sq/sb7jrfk14qv7yyh9z55mszp40000gn/T/check_ssl_certXXXXXX.0m8k1ccs
[DBG]   expect -c "set echo \"-noecho\"; set timeout 15; spawn -noecho /bin/sh -c "/usr/bin/curl --silent --location http://cert.int-x3.letsencrypt.org/ > /var/folders/sq/sb7jrfk14qv7yyh9z55mszp40000gn/T/check_ssl_certXXXXXX.0m8k1ccs"; expect timeout { exit 1 } eof { exit 0 }"
[DBG]   expect returned 0
[DBG] OCSP: issuer certificate type:  data
[DBG] OCSP: converting issuer certificate from DER to PEM
[DBG] OCSP: storing a copy of the retrieved issuer certificate to cert.int-x3.letsencrypt.org
[DBG] OCSP: host = ocsp.int-x3.letsencrypt.org
[DBG] openssl ocsp supports the -header option
[DBG] openssl ocsp -header requires 'key value'
[DBG] executing /opt/local/bin/openssl ocsp -no_nonce -issuer /var/folders/sq/sb7jrfk14qv7yyh9z55mszp40000gn/T/check_ssl_certXXXXXX.0m8k1ccs -cert /var/folders/sq/sb7jrfk14qv7yyh9z55mszp40000gn/T/check_ssl_certXXXXXX.0p7s5mmm  -url http://ocsp.int-x3.letsencrypt.org  -header HOST ocsp.int-x3.letsencrypt.org
[DBG] OCSP: response = Response Verify Failure
[DBG] OCSP: response = 4636423788:error:27069076:OCSP routines:OCSP_basic_verify:signer certificate not found:ocsp_vfy.c:92:
[DBG] OCSP: response = /var/folders/sq/sb7jrfk14qv7yyh9z55mszp40000gn/T/check_ssl_certXXXXXX.0p7s5mmm: good
[DBG] OCSP: response = 	This Update: Nov 10 10:00:00 2018 GMT
[DBG] OCSP: response = 	Next Update: Nov 17 10:00:00 2018 GMT
```
