### ISSUE TITLE
grep can fail with "Binary file xx matches"

### ISSUE THREAD

**Issue by arekm** [matteocorti/check_ssl_cert#116]
````
/usr/bin/timeout 15 /bin/sh -c 'echo '\''Q'\'' | /usr/bin/openssl s_client   -starttls pop3 -connect pop3.domena.pl:110 -servername pop3.domena.pl -verify 6 -CApath /etc/openssl/certs' > /dev/null 2> xx
`````

can lead to binary data in output (xx file). check_ssl_cert then greps such file looking for ascii strings.

Unfortunately grep can return error message because by default it expects ascii data only.

````
# LC_ALL=C grep a xx
Binary file xx matches
````

That leads to:

````
SSL_CERT CRITICAL pop3.domena.pl: Cannot verify certificate: Binary file /root/tmp/check_ssl_certdmyqjC matches|days=227;;;;
````

The solution is to always use "grep -a".

I'm seeing this issue on 1.80.1

**Comment by matteocorti** [comment]
I'll take a look although `grep -a` is not POSIX compliant

**Comment by matteocorti** [comment]
A solution could be to remove all the NULL characters first: https://unix.stackexchange.com/questions/19907/what-makes-grep-consider-a-file-to-be-binary

**Comment by matteocorti** [comment]
Hi

I am not able to reproduce the problem. Which locale are you using?

```
$ export LC_ALL=C
$ ./check_ssl_cert -H pop3.domena.pl -P pop3 -p 110
SSL_CERT OK - x509 certificate 'domena.pl' from 'Let's Encrypt Authority X3' valid until Apr  3 07:55:27 2019 GMT (expires in 70 days)|days=70;;;;
```

**Comment by arekm** [comment]
en_GB.UTF-8, C - can reproduce with both.

The difference comes from openssl binary.

openssl 1.1.1a binary puts nulls in output:
````
# /usr/bin/timeout 15 /bin/sh -c 'echo '\''Q'\'' | /usr/bin/openssl s_client   -starttls pop3 -connect pop3.domena.pl:110 -servername pop3.domena.pl -verify 6 -CApath /etc/openssl/certs' > /dev/null 2> xx
# xxd xx | tail -n 2
000000d0: 7365 7276 6572 2072 6561 6479 2e0d 0a00  server ready....
000000e0: 0000 0000 0000 0044 4f4e 450a            .......DONE.
# /usr/bin/openssl version
OpenSSL 1.1.1a  20 Nov 2018
````

while 1.0.2n doesn't do that:

````
# /usr/bin/timeout 15 /bin/sh -c 'echo '\''Q'\'' | /usr/bin/openssl s_client   -starttls pop3 -connect pop3.domena.pl:110 -servername pop3.domena.pl -verify 6 -CApath /etc/openssl/certs' > /dev/null 2> xx
# xxd xx |tail -n 2
000000e0: 6c20 7365 7276 6572 2072 6561 6479 2e0d  l server ready..
000000f0: 0a44 4f4e 450a                           .DONE.
# /usr/bin/openssl version
OpenSSL 1.0.2n  7 Dec 2017
````

**Comment by matteocorti** [comment]
Thanks for the info. I will try to reproduce it and see if the fix with the NULL removal works.

**Comment by matteocorti** [comment]
As I was not able to reproduce the problem I am not able to test if the new implementation solves the issue (it should as I am removing NULLs before 'grepping' files.
