### ISSUE TITLE
Feature - Warn On SSL Labs Grade

### ISSUE THREAD

**Issue by barakAtSoluto** [matteocorti/check_ssl_cert#117]
Hi,

Currently the check returns only CRITICAL if your SSL Labs grade falls beneath the wanted grade.
I'd like to have a feature which behaves like so:

when `warning_grade < critical_grade` an unknown will be thrown.
when `grade < critical_grade <= warn_grade` a critical will be thrown (original behaviour).
when `critical_grade <= grade <= warn_grade` a warn will be thrown.
when '`critical_grade <= warn_grade < grade` all is okay.

**Comment by matteocorti** [comment]
This would mean to have to command line parameters for the SSL labs check. Do I understand it right?

**Comment by barakAtSoluto** [comment]
See PR https://github.com/matteocorti/check_ssl_cert/pull/118.

Thank you.

**Comment by barakAtSoluto** [comment]
@matteocorti , currently there's 1 CLI param indicating the CRITICAL threshold for the SSL Labs check (and it also determines) whether or not to query SSL Labs.

So I agree with you about adding a param (also in the PR) but I guess this could be implemented in other ways.

**Comment by matteocorti** [comment]
Added in 1.81.0
