### ISSUE TITLE
check against CRL if OCSP not available

### ISSUE THREAD

**Issue by teclogi** [matteocorti/check_ssl_cert#121]
To be able to check the revocation status of a certificate which has been issued by an CA (for example internal CA) with no OCSP but a CRL, it would be nice to have a switch or a fallback to CRL.

Or if the OCSP is not available like now from GoDaddy:
`SSL_CERT CRITICAL xxx.xxx.xxx.xxx: ocsp: Use -help for summary.|days=900;30;5;;`

`Responder Error: unauthorized (6)`

**Comment by matteocorti** [comment]
Actually these are two issues:

- The CLR feature is in the pipeline
- The problem with GoDaddy: this is a bug since the error message should be better.

Do you have an example that I could check?

**Comment by teclogi** [comment]
Hi, 

thanks for the fast reply!
Here the url we try to validate for example:
[apps.mpc-group.com](url)

Even SSL Labs is throwing an OCSP error:
https://www.ssllabs.com/ssltest/analyze.html?d=apps.mpc-group.com&latest

![image](https://user-images.githubusercontent.com/27726999/53010967-8d512480-343f-11e9-981b-5fac8106b196.png)

Best regards,
Tim

**Comment by matteocorti** [comment]
I just checked and I get a better error message:

```
SSL_CERT CRITICAL apps.mpc-group.com: Responder Error: unauthorized (6)|days=634;;;;
```

Where `Responder Error: unauthorized (6)` is the message I get from OpenSSL (similar to SSLLabs)

Which version are you using?

**Comment by teclogi** [comment]
I just downloaded the current version today (VERSION=1.82.0)
`SSL_CERT CRITICAL apps.mpc-group.com: ocsp: Use -help for summary.|days=634;30;5;;`

Here my command:
`./check_ssl_cert -H 217.110.76.227 -p 443 -n apps.mpc-group.com --altnames --sni apps.mpc-group.com -c 5 -w 30 -v`

**Comment by matteocorti** [comment]
OK with the same command I get
```
SSL_CERT CRITICAL apps.mpc-group.com: OCSP error: 'Responder Error: unauthorized (6)'|days=634;30;5;;
```

Which version of OpenSSL are you using? Could you please post the output with `-d`?

**Comment by teclogi** [comment]
I´m using Debian 9.6 (with all available updates installed).

here the debug output:
```
[DBG] ROOT_CA =
[DBG] cURL binary needed. SSL Labs = , OCSP = 1
[DBG] cURL binary not specified
[DBG] cURL available: /usr/bin/curl
expect not available
timeout available (/usr/bin/timeout)
[DBG] perl available: /usr/bin/perl
[DBG] date available: /bin/date
found GNU date with timestamp support: enabling date computations
[DBG] check_ssl_cert version: 1.82.0
[DBG] OpenSSL binary: /usr/bin/openssl
[DBG] OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
[DBG] OpenSSL configuration directory: /usr/lib/ssl
[DBG] 0 root certificates installed by default
[DBG] System info: Linux mon-server 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
[DBG] Date computation: GNU
[DBG] '/usr/bin/openssl s_client' supports '-servername': using -servername apps.mpc-group.com
[DBG] '/usr/bin/openssl s_client' supports '-xmpphost': using -xmpphost 217.110.76.227
[DBG] temporary file /tmp/check_ssl_cert4NPZjw created
[DBG] temporary file /tmp/check_ssl_certHEr7wV created
[DBG] temporary file /tmp/check_ssl_certbgxdhV created
[DBG] temporary file /tmp/check_ssl_certjZ21G4 created
downloading certificate to /tmp
[DBG] 217.110.76.227 is an IPv4 address
[DBG] executing with timeout (15s): echo 'HEAD / HTTP/1.1\nHost: apps.mpc-group.com\nUser-Agent: check_ssl_cert/1.82.0\nConnection: close\n\n' | /usr/bin/openssl s_client   -crlf -ign_eof -connect 217.110.76.227:443 -servername apps.mpc-group.com -showcerts -verify 6     2> /tmp/check_ssl_certHEr7wV 1> /tmp/check_ssl_cert4NPZjw
[DBG]   /usr/bin/timeout 15 /bin/sh -c "echo 'HEAD / HTTP/1.1\nHost: apps.mpc-group.com\nUser-Agent: check_ssl_cert/1.82.0\nConnection: close\n\n' | /usr/bin/openssl s_client   -crlf -ign_eof -connect 217.110.76.227:443 -servername apps.mpc-group.com -showcerts -verify 6     2> /tmp/check_ssl_certHEr7wV 1> /tmp/check_ssl_cert4NPZjw"
[DBG] storing a copy of the retrieved certificate in 217.110.76.227.crt
[DBG] storing a copy of the OpenSSL errors in 217.110.76.227.error
parsing the x509 certificate file
[DBG] subject=OU = Domain Control Validated, CN = apps.mpc-group.com
[DBG] CN         = apps.mpc-group.com
[DBG] CA         = Go Daddy Secure Certificate Authority - G2
[DBG] CA         = Go Daddy Root Certificate Authority - G2
[DBG] SERIAL     = 261E2CD40195B6D7
[DBG] FINGERPRINT= DC:AF:F2:50:36:C6:39:FC:D7:CB:C5:DB:40:6A:B1:C1:30:B8:08:A5
[DBG] OCSP_URI   = http://ocsp.godaddy.com/
[DBG] ISSUER_URI = http://certificates.godaddy.com/repository/gdig2.crt
[DBG]     Signature Algorithm: sha256WithRSAEncryption
[DBG] Date computations: GNU
The certificate will expire in 633 day(s)
[DBG] subjectAlternativeName = apps.mpc-group.com www.apps.mpc-group.com
[DBG] check CN: apps.mpc-group.com
[DBG] CN check finished
[DBG] Checking expiration date
[DBG] executing: /usr/bin/openssl x509 -in /tmp/check_ssl_cert4NPZjw -noout -checkend 432000
[DBG] executing: /usr/bin/openssl x509 -in /tmp/check_ssl_cert4NPZjw -noout -checkend 2592000
[DBG] Checking revokation via OCSP
[DBG] OCSP: fetching issuer certificate http://certificates.godaddy.com/repository/gdig2.crt to /tmp/check_ssl_certbgxdhV
[DBG] executing with timeout (15s): /usr/bin/curl --silent --location http://certificates.godaddy.com/repository/gdig2.crt > /tmp/check_ssl_certbgxdhV
[DBG]   /usr/bin/timeout 15 /bin/sh -c "/usr/bin/curl --silent --location http://certificates.godaddy.com/repository/gdig2.crt > /tmp/check_ssl_certbgxdhV"
[DBG] OCSP: issuer certificate type:  data
[DBG] OCSP: converting issuer certificate from DER to PEM
[DBG] OCSP: storing a copy of the retrieved issuer certificate to gdig2.crt
[DBG] OCSP: host = ocsp.godaddy.com
[DBG] openssl ocsp supports the -header option
[DBG] openssl ocsp -header requires 'key=value'
[DBG] executing /usr/bin/openssl ocsp -no_nonce -issuer /tmp/check_ssl_certbgxdhV -cert /tmp/check_ssl_cert4NPZjw  -url http://ocsp.godaddy.com/  -header HOST=ocsp.godaddy.com
[DBG] OCSP: response = Responder Error: unauthorized (6)
[DBG] cleaning up temporary files
[DBG]   /tmp/check_ssl_cert4NPZjw
[DBG]   /tmp/check_ssl_certHEr7wV
[DBG]   /tmp/check_ssl_certbgxdhV
[DBG]   /tmp/check_ssl_certjZ21G4
SSL_CERT CRITICAL apps.mpc-group.com: ocsp: Use -help for summary.|days=633;30;5;;
```

**Comment by matteocorti** [comment]
Mmmm the error message is strange as the response from OCSP is detected:
```[DBG] OCSP: response = Responder Error: unauthorized (6)```

but the error message does not reflect it:
```SSL_CERT CRITICAL apps.mpc-group.com: ocsp: Use -help for summary.|days=633;30;5;;```

**Comment by matteocorti** [comment]
Ok thanks, I fixed the error message with the latest commit. I will leave the issue open as a new feature. I will take a look about CRLs when I have a little time

**Comment by teclogi** [comment]
Thank you, the error message looks better now!`

`SSL_CERT CRITICAL apps.mpc-group.com: OCSP error: 'Responder Error: unauthorized (6)'|days=633;30;5;;`

Looking forward to the CRL feature. ;)

**Comment by yasirugw** [comment]
I'm facing the same issue with 2 Cloudflare ssl enabled websites, but it is intermittent but very frequent. Debug output is like below. Any idea why? which side the issue is (cert/check_ssl_cert)?

`[DBG] executing /usr/bin/openssl ocsp -no_nonce -issuer /tmp/check_ssl_certaxNPGR -cert /tmp/check_ssl_certheIJNq  -url http://ocsp.digicert.com  -header HOST=ocsp.digicert.com`
`[DBG] OCSP: response = Responder Error: unauthorized (6)`
`[DBG] OCSP: not good. HTTP_PROXY = `
`[DBG] executing /usr/bin/openssl ocsp -no_nonce -issuer "/tmp/check_ssl_certaxNPGR" -cert "/tmp/check_ssl_certheIJNq" -url "http://ocsp.digicert.com" "" 2>&1`
`OCSP Error: Response verify OK`
`/tmp/check_ssl_certheIJNq: good`
`	This Update: Oct 30 10:54:31 2019 GMT`
`	Next Update: Nov  6 10:09:31 2019 GMT`

**Comment by matteocorti** [comment]
@yasirugw You should give me the possibility to reproduce the error. Can you please tell me which host are you testing and which arguments did you specify?

**Comment by matteocorti** [comment]
> > @yasirugw You should give me the possibility to reproduce the error. Can you please tell me which host are you testing and which arguments did you specify?
> 
> Hi @matteocorti , I cannot enter the domain name to public forums yet. I have sent you an email. Kindly check.

Thanks. I received the email and I cannot reproduce the problem.

**Comment by yasirugw** [comment]
> Thanks. I received the email and I cannot reproduce the problem.

It is intermittent. You have to try at least 5 times and you should get above error. I just checked and I got it my 3rd try.

**Comment by matteocorti** [comment]
> > Thanks. I received the email and I cannot reproduce the problem.
> 
> It is intermittent. You have to try at least 5 times and you should get above error. I just checked and I got it my 3rd try.

I tried several times. As I said in the email, I don't really have time to look at a sporadic issue. If you want help from the community and the authors, post a complete bug report.

**Comment by yasirugw** [comment]
> I tried several times. As I said in the email, I don't really have time to look at a sporadic issue. If you want help from the community and the authors, post a complete bug report.

Thanks for you time @matteocorti

**Comment by matteocorti** [comment]
CRL should work now.
