### ISSUE TITLE
OCSP check failing, even if there is no OSCP URI in the certificate

### ISSUE THREAD

**Issue by gwarf** [matteocorti/check_ssl_cert#122]
An host certificates checks fail with `Unable to fetch OCSP issuer certificate` even if there is no OCSP URI in the certificate.
We are using the IGTF CA bundle: https://dist.eugridpma.info/distribution/igtf/current/

```console
> openssl x509 -in creamce1.itep.ru.crt -noout -ocsp_uri
> ./check_ssl_cert -p 8443 -H creamce1.itep.ru -r /etc/grid-security/certificates
SSL_CERT UNKNOWN creamce1.itep.ru: Unable to fetch OCSP issuer certificate.
```

Looking at the debug output it seems that even if no `OCSP_URI`  is found the code is using the `ISSUER_URI`:
```console
(...)
' | /usr/bin/openssl s_client   -crlf -ign_eof -connect creamce1.itep.ru:8443 -servername creamce1.itep.ru -showcerts -verify 6 -CApath /etc/grid-security/certificates    2> /var/folders/f9/8y470pl537n6wf61hl_48c880000gn/T/check_ssl_certXXXXXX.wHDS8GTS 1> /var/folders/f9/8y470pl537n6wf61hl_48c880000gn/T/check_ssl_certXXXXXX.fuCEBoOL"
[DBG] storing a copy of the retrieved certificate in creamce1.itep.ru.crt
[DBG] storing a copy of the OpenSSL errors in creamce1.itep.ru.error
parsing the x509 certificate file
[DBG] subject= C = RU, O = RDIG, OU = hosts, OU = itep.ru, CN = creamce1.itep.ru
[DBG] CN         = creamce1.itep.ru
[DBG] CA         = Russian Data-Intensive Grid CA
[DBG] SERIAL     = 1E89
[DBG] FINGERPRINT= 55:B9:DA:AF:33:17:F5:15:AC:71:59:5F:D5:50:36:85:F1:35:B9:47
[DBG] OCSP_URI   =
[DBG] ISSUER_URI = http://ca.grid.kiae.ru/RDIG/ca.html
[DBG]     Signature Algorithm: sha256WithRSAEncryption
[DBG] Date computations: BSD
The certificate will expire in 122 day(s)
[DBG] subjectAlternativeName =
[DBG] Checking expiration date
[DBG] Checking revokation via OCSP
[DBG] OCSP: fetching issuer certificate http://ca.grid.kiae.ru/RDIG/ca.html to /var/folders/f9/8y470pl537n6wf61hl_48c880000gn/T/check_ssl_certXXXXXX.tOL3yB92
[DBG] executing with timeout (15s): /usr/bin/curl --silent --location http://ca.grid.kiae.ru/RDIG/ca.html > /var/folders/f9/8y470pl537n6wf61hl_48c880000gn/T/check_ssl_certXXXXXX.tOL3yB92
[DBG]   /usr/local/bin/timeout 15 /bin/sh -c "/usr/bin/curl --silent --location http://ca.grid.kiae.ru/RDIG/ca.html > /var/folders/f9/8y470pl537n6wf61hl_48c880000gn/T/check_ssl_certXXXXXX.tOL3yB92"
[DBG] OCSP: issuer certificate type:  HTML document text, ASCII text
[DBG] cleaning up temporary files
```

And as you can see http://ca.grid.kiae.ru/RDIG/ca.html doesn't lookg like an OCSP endpoint.

For other servers with either a correct `OCSP_URI` or no `ISSUER_URI` at all it works without any error.
So is this something that should be fixed in the code or at the CA level?
I've seen we can disable OCSP validated, but as the probe conf is shared among servers we would like avoid having to put custom parameters for some hosts.

Thanks for your help!

**Comment by matteocorti** [comment]
The certificate does specify an intermediate certificate (the `CA Issuers` URI field) which is invalid (is a simple error HTML page).

I will fix the code to generate a better error message but the CA has a problem

**Comment by gwarf** [comment]
Thanks @matteocorti!

 Indeed there is a problem with the CA, but we wonder why this code is executed even if there is no OCSP_URI at all in the certificate? 
I was also told that the message can be misleading as the certificate pointed by the ISSUER_URI could be a root certificate (and not always an intermediate certificate).
The following was proposed:
```sh
"CA Issuers URI (${ISSUER_URI}) does not point to a valid certificate"
```

**Comment by matteocorti** [comment]
The code is executed per default. The issuer certificate does not need to be an intermediate certificate, it could also be the root one. In this case the certificate specifies an issuer: 
http://ca.grid.kiae.ru/RDIG/ca.html but it's an HTML page not a certificate.

**Comment by gwarf** [comment]
Hi @matteocorti
Yes we agree, we are discussing with the CA owner to get this fixed.

My point was that the message https://github.com/matteocorti/check_ssl_cert/commit/ad30fed99ab17ed4cd56c303371c9f1cb42f8681#diff-e4df4a053a308dcefa564b468ceda471R2183 maybe misleading as it only refers to an intermediate certificate.

**Comment by matteocorti** [comment]
Hi, I corrected the error message, as you correctly say, it does not have to be an intermediate certificate. Thanks
