### ISSUE TITLE
Unable to verify OCSP response

### ISSUE THREAD

**Issue by eeertel** [matteocorti/check_ssl_cert#127]
I am currently using the script to test one certificate with this command line (Ubuntu):

 ./check_ssl_certificate_new.sh -r /etc/ssl/certs -w 90 -c 45 -H medone-radiology.thieme.com -v

Although the certificate is valid, the script response is critical ("Cannot verify certificate").
According to this link (https://community.letsencrypt.org/t/unable-to-verify-ocsp-response/7264/3) the solution is to add the -verify_other option to the openssl command. 
Do you think that the script can be enhanced to handle this case ?

Thank you in advance,
bye //emil.

**Comment by matteocorti** [comment]
I could but it's difficult to tell the users they should look for the certificate of the OCSP service. I will add the option.

**Comment by matteocorti** [comment]
The problem has nothing to do with OCSP:

```
 ./check_ssl_cert -H medone-radiology.thieme.com  --ignore-ocsp
SSL_CERT CRITICAL medone-radiology.thieme.com: Cannot verify certificate: unable to get local issuer certificate, unable to verify the first certificate|days=688;;;;
```

**Comment by matteocorti** [comment]
The problem is incomplete certificate chain. See for example https://www.ssllabs.com/ssltest/analyze.html?d=medone-radiology.thieme.com
