### ISSUE TITLE
Sporadic "Unable to fetch OCSP issuer certificate" 

### ISSUE THREAD

**Issue by mtdeguzis** [matteocorti/check_ssl_cert#128]
I am not totally sure if this is a bug or an issue with the entrust ca being used. We sporadically get this error from time to time, generating undue noise:

```
SSL_CERT UNKNOWN 1.2.3.4: Unable to fetch OCSP issuer certificate.
```

This recovers within 2-5 minutes (basically the next Icinga (e.g. like 'nagios') check).

Related: #50

**Comment by matteocorti** [comment]
Difficult to say without information. Could you please provide an example with the debugging output (`-d` option)?

**Comment by mtdeguzis** [comment]
It's hard to catch, bug should I just adjust our check to include `-d`? Andthen report back when i see it? I see you closed the ticket...?

**Comment by matteocorti** [comment]
I closed the ticket as I have no possibility to reproduce or analyse the problem. Without an example or a trace it does not make any sense to keep the issue open. As far as we know it could be anything, from a problem with the provider to network.

**Comment by mtdeguzis** [comment]
Ok, i'll try to get debug info. I have to be careful, as it's an internal cert.

**Comment by amenk** [comment]
In our case it was a DNS problem where the letsencrypt OCSP server could not be resolved sproadically. We were able to nail that down by just executing `check_ssl_cert` lots of times manually.
It might make sense to not send out warning emails on UNKOWN status.

**Comment by matteocorti** [comment]
Ok, with ```--ignore-ocsp``` you can skip the OCSP checks. We could add a ```--ignore-ocsp-problems``` to perform the checks but ignore the _unknown_ problems

**Comment by matteocorti** [comment]
Did you try with the ```--ignore-ocsp-timeout``` command line option?
