### ISSUE TITLE
Sporadic "Unable to load certificate" 

### ISSUE THREAD

**Issue by mtdeguzis** [matteocorti/check_ssl_cert#129]
I am not totally sure if this is a bug or an issue with the internal cert We sporadically get this error from time to time, generating undue noise:

```
SSL_CERT CRITICAL 1.2.3.4: unable to load certificate
47729023775888:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:707:Expecting: TRUSTED CERTIFICATE
````

Could this just be due to a fetch timeout? If it's not a bug and just a network/cert issue on our side, any arguments to adjust or add?

If it is some kind of network issue, it may be directly related to #128

**Comment by matteocorti** [comment]
The second line should not be there but it's difficult to say as you are not giving any information on what you are doing/testing.
