### ISSUE TITLE
Getting OCSP errors very frequently

### ISSUE THREAD

**Issue by ronaldegmar** [matteocorti/check_ssl_cert#130]
Using version 1.72, I got the following error:

SSL_CERT CRITICAL <my_site>: ocsp: Use -help for summary.

Using most current version 1.84, I got the following error:

SSL_CERT CRITICAL alumni.sha.cornell.edu: OCSP error: Response verify OK

This is the command I'm running:
$USER1$/check_ssl_cert --host $ARG1$ -w $ARG2$ -c $ARG3$ --rootcert /etc/ssl/certs --host-cn

Any method how to fix these OCSP errors?

**Comment by matteocorti** [comment]
Hi

I cannot reproduce the problem:

```
./check_ssl_cert -H  alumni.sha.cornell.edu
SSL_CERT OK - x509 certificate 'alumni.sha.cornell.edu' from 'InCommon RSA Server CA' valid until Feb  6 23:59:59 2021 GMT (expires in 639 days)|days=639;;;;
```

Please upgrade to the latest version (1.84) and publish the output with the debugging option `-d`
