### ISSUE TITLE
Extend patterns to accept grouping 

### ISSUE THREAD

**Issue by aslafy-z** [matteocorti/check_ssl_cert#132]
Activate grep Positive Lookbehind option to be able to do things like : `-i "^(Comodo|Symantec).*"`
see https://stackoverflow.com/a/24784580

This could be applied to all the pattern matching: Organization, Issuer, Common names ...

Could be done for Issuer in here by adding a `-P` in this grep: https://github.com/matteocorti/check_ssl_cert/blob/master/check_ssl_cert#L1894

**Comment by matteocorti** [comment]
Actually `grep -P` is not POSIX and not available on many platforms.

It could be possible to check for the grep version and then enable option.

I will take a look if I find some time.

**Comment by aslafy-z** [comment]
It seems like `-P` isn't needed afterall. We can use `-E` to enable the extended regex support, which is POSIX (see: https://www.unix.com/man-page/posix/1p/grep/).
