### ISSUE TITLE
Service state escalation incorrrect: returns WARN where CRITICAL is necessary

### ISSUE THREAD

**Issue by jmuecke** [matteocorti/check_ssl_cert#138]
**Describe the bug**
check_ssl_cert returns WARNING even though the check should return CRITICAL.

**To Reproduce**
Example: When you check a self-signed certificate and the certificate validity is below the threshhold the check returns WARN instead of CRITICAL. 
```
`./check_ssl_cert -H self-signed.badssl.com -w 700`
SSL_CERT WARN *.badssl.com: x509 certificate will expire in 666 day(s) on Jun 11 15:31:59 2021 GMT|days=666;700;;;
```
```
`./check_ssl_cert -H self-signed.badssl.com `
SSL_CERT CRITICAL *.badssl.com: Cannot verify certificate, self signed certificate|days=666;;;;
```

**Expected behavior**
check_ssl_cert should return the highest level error (WARN < CRITICAL). 

I would suggest to also return all occurred errors and not only the most/first critical error. I can make a PR for this. There I collect all errors and return the first occurred CRITICAL or WARN and submit other errors in the next lines.

PS: There are as well some errors with not quoted variables as you can find with `make test`. Example: https://github.com/matteocorti/check_ssl_cert/blob/a3431e81a6663865942eec70d9aa51afd06d7495/check_ssl_cert#L2052

**Comment by matteocorti** [comment]
Hi, this is indeed a bug. A PR would be nice, otherwise I'll take a look as soon as I find some time.

**Comment by matteocorti** [comment]
My version of shellckeck is not reporting the problems (which are there). Which version are you using?

**Comment by matteocorti** [comment]
I checked the file with a new shellcheck version (-o all) and fixed all the style problems

**Comment by jmuecke** [comment]
>  a bug. A PR would

I will try to do this on Tuesday or Wednesday.

> I checked the file with a new shellcheck version (-o all) and fixed all the style problems

Look's good. Thanks

**Comment by matteocorti** [comment]
Fixed
