### ISSUE TITLE
Avoid additional s_client call for --require-ocsp-stapling

### ISSUE THREAD

**Issue by dilyanpalauzov** [matteocorti/check_ssl_cert#142]
Passing `--require-ocsp-stapling` calls once more "openssl s_client”, with an additional “-status” parameter.  This causes additional load for both server and client.  Please consolidate that call to the other s_client call, so that a single connection needs to be establised.

**Comment by iasdeoupxe** [comment]
In addition this parameter will always send an HTTP HEAD request to the remote service even if the service is e.g. a SMTP one. In non HTTP services the final Q/QUIT command is missing as well.

If this functionality is reworked this could be considered as well.

**Comment by dilyanpalauzov** [comment]
What is this es-zett (S13)?
```diff
diff --git a/check_ssl_cert b/check_ssl_cert
--- a/check_ssl_cert
@@ -1645,7 +1649,7 @@ main() {
                 #   ($! means not to do it on the last line (as there should be one final newline))
                 # - finally the substitution replaces every newline with a space on
                 #   the pattern space
-                ERROR_MESSAGE="$(sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/; /g' "${ERROR}")"
+                ERROR_MESSAGE="$(sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/; /g' "${ERROR}")"ß
                 if [ -n "${VERBOSE}" ] ; then
                     echo "Error: ${ERROR_MESSAGE}"
                 fi

```

**Comment by matteocorti** [comment]
A typo :-(

**Comment by matteocorti** [comment]
Fixed.
