### ISSUE TITLE
--ecdsa --require-ocsp-stapling ignores --ecdsa

### ISSUE THREAD

**Issue by dilyanpalauzov** [matteocorti/check_ssl_cert#143]
A host can offer, depending on the used cipher, a RSA or ECDSA certificate and the certificates can have the MUST STAPLE extension.

To check for that extension in both certificates, one has to call `check_ssl_cert  --rsa --require-ocsp-stapling -H hostname` and `check_ssl_cert  --ecdsa --require-ocsp-stapling -H hostname`

Then  check_ssl_check calls `openssl s_client -status`.  But s_client does not request ECDSA or RSA, so the server returns any of them and check_ssl_check does not check for working MUST STAPLE stack in both RSA and ECDSA certificates.

**Comment by matteocorti** [comment]
Should be fixed in the latest commit. Is there test case that I could include in the test suite?

**Comment by dilyanpalauzov** [comment]
https://mail.aegee.org shall have MUST_STAPLE for both RSA and ECDSA

**Comment by dilyanpalauzov** [comment]
Nope.  https://mail.aegee.org offers only RSA.   https://autoconfig.aegee.org offers both RSA and ECDSA.
