### ISSUE TITLE
No issue: Thanks (cpu load)

### ISSUE THREAD

**Issue by BuildTheRobots** [matteocorti/check_ssl_cert#144]
This is not an issue, but I wanted to say thank you and couldn't think of a better way.

Apart from the project being extremely useful, the massive reduction in CPU load between 516e6e0 and e125962 is massive! 
On a small icinga system I was previously maxing out 4 cores, mostly due to openssl as being called from check_ssl_cert. Having just updated my entire system has a load average of 0.35.

Apologies for raising a bug about this, but I couldn't think of a better way. I did look though closed tickets but couldn't find anything related to cpu load.

Massive thanks :)

**Comment by matteocorti** [comment]
Hi
I don't remember optimising for CPU usage but if the performance improved, I'm happy to hear about it.
Matteo
