### ISSUE TITLE
The plugin return No certificate returned

### ISSUE THREAD

**Issue by PetrMa** [matteocorti/check_ssl_cert#161]
Hello,
after I made an upgrade from Debian 9 to Debian 10 I´ve got an error "No certificate returned" every time the plugin run.

Currently I have a version 
**check_ssl_cert version 1.96.0**

**./check_ssl_cert -H czprgnt141 --ignore-sig-alg --ignore-ocsp -A -c 15 -w 30**
SSL_CERT CRITICAL czprgnt141: No certificate returned

**./check_ssl_cert -H czprgnt141 --ignore-sig-alg --ignore-ocsp -A -c 15 -w 30 -v**
expect not available
timeout available (/usr/bin/timeout)
found GNU date with timestamp support: enabling date computations
downloading certificate to /tmp
Error: verify depth is 6; write:errno=104
SSL_CERT CRITICAL czprgnt141: No certificate returned

**openssl s_client -connect czprgnt141:443**
CONNECTED(00000003)
write:errno=104
no peer certificate available
No client certificate CA names sent
SSL handshake has read 0 bytes and written 283 bytes
Verification: OK
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)

Could you please help me? Before upgrade the plugin return correct data about the certificates from our servers.
PS: the same issue on previous installed version 1.37.
PS2: the servers with SSL certificate issued by public CA are OK. The problem is only with SHA1 certificates issued by local internal CA.

**Comment by matteocorti** [comment]
Could you please post the debugging output? (`-d` option)

And also the content of the certificate and error file generated with `-d`

**Comment by matteocorti** [comment]
What I found so far:

> the server or some middlebox (firewall, load balancer...) caused a RST (errno 104 is ECONNRESET) of the TCP connection (probably) as response to the ClientHello

**Comment by matteocorti** [comment]
It seems that there is problem either with the server or OpenSSL and given the error message I am tending to assume a problem with the setup (instead of a bug).

**Comment by PetrMa** [comment]
Hello,
there is a debug result of the plugin.
I hope this is plugin version independent issue. Mayber there is some change in openssl. The openssl was upgraded during the Debian upgrade from version OpenSSL 1.1.0k  28 May 2019 to OpenSSL 1.1.1c  28 May 2019

./check_ssl_cert -H czprgnt141 --ignore-sig-alg --ignore-ocsp -A -c 15 -w 30 -d
[DBG] -c specified: 15
[DBG] ROOT_CA =
[DBG] cURL binary not needed. SSL Labs = , OCSP =
expect not available
timeout available (/usr/bin/timeout)
[DBG] perl available: /usr/local/bin/perl
[DBG] date available: /bin/date
found GNU date with timestamp support: enabling date computations
[DBG] check_ssl_cert version: 1.96.0
[DBG] OpenSSL binary: /usr/bin/openssl
[DBG] OpenSSL version: OpenSSL 1.1.1c  28 May 2019
[DBG] OpenSSL configuration directory: /usr/lib/ssl
[DBG] 0 root certificates installed by default
[DBG] System info: Linux czprgux34 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux
[DBG] Date computation: GNU
[DBG] '/usr/bin/openssl s_client' supports '-servername': using -servername czprgnt141
[DBG] '/usr/bin/openssl s_client' supports '-xmpphost': using -xmpphost czprgnt141
[DBG] temporary file /tmp/check_ssl_cert8gwzhT created
[DBG] temporary file /tmp/check_ssl_certG4hBgy created
downloading certificate to /tmp
[DBG] czprgnt141 is not an IP address
[DBG] executing with timeout (15s): printf 'HEAD / HTTP/1.1\nHost: czprgnt141\nUser-Agent: check_ssl_cert/1.96.0\nConnection: close\n\n' | /usr/bin/openssl s_client    -crlf -ign_eof -connect czprgnt141:443 -serve
rname czprgnt141 -showcerts -verify 6      2> /tmp/check_ssl_certG4hBgy 1> /tmp/check_ssl_cert8gwzhT
[DBG]   /usr/bin/timeout 15 /bin/sh -c "printf 'HEAD / HTTP/1.1\nHost: czprgnt141\nUser-Agent: check_ssl_cert/1.96.0\nConnection: close\n\n' | /usr/bin/openssl s_client    -crlf -ign_eof -connect czprgnt141:443 -s
ervername czprgnt141 -showcerts -verify 6      2> /tmp/check_ssl_certG4hBgy 1> /tmp/check_ssl_cert8gwzhT"
[DBG] storing a copy of the retrieved certificate in /tmp/czprgnt141-443.crt
[DBG] storing a copy of the OpenSSL errors in /tmp/czprgnt141-443.error
Error: verify depth is 6; write:errno=104
[DBG] CRITICAL >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[DBG] prepend_critical_message: new message    = No certificate returned
[DBG] prepend_critical_message: HOST           = czprgnt141
[DBG] prepend_critical_message: CN             =
[DBG] prepend_critical_message: SNI            =
[DBG] prepend_critical_message: FILE           =
[DBG] prepend_critical_message: SHORTNAME      = SSL_CERT
[DBG] prepend_critical_message: MSG            =
[DBG] prepend_critical_message: CRITICAL_MSG   =
[DBG] prepend_critical_message: ALL_MSG 1      =
[DBG] prepend_critical_message: MSG 2          = SSL_CERT CRITICAL czprgnt141: No certificate returned
[DBG] prepend_critical_message: CRITICAL_MSG 2 = SSL_CERT CRITICAL czprgnt141: No certificate returned
[DBG] prepend_critical_message: ALL_MSG 2      =
    SSL_CERT CRITICAL czprgnt141: No certificate returned
[DBG] CRITICAL <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
[DBG] cleaning up temporary files
[DBG]   /tmp/check_ssl_cert8gwzhT
[DBG]   /tmp/check_ssl_certG4hBgy
[DBG] exiting with CRITICAL
[DBG] ALL_MSG =
    SSL_CERT CRITICAL czprgnt141: No certificate returned
[DBG] number of errors = 1
SSL_CERT CRITICAL czprgnt141: No certificate returned

**Comment by PetrMa** [comment]
Hello,
there is the result of the 2nd command:

verify depth is 6
CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 302 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---

[debug.zip](https://github.com/matteocorti/check_ssl_cert/files/3656322/debug.zip)

**Comment by matteocorti** [comment]
Ho as the problem can be reproduced with OpenSSL only, it does not to seem that it has something to do with the plugin.

The connection is dropped.

As the server is not public, I see no way how I could help to investigate the problem.

**Comment by PetrMa** [comment]
Hello,
I can confirm that this issue is depended on openssl library. I tried to downgrade the openssl from OpenSSL 1.1.1c  28 May 2019 back to OpenSSL 1.1.0k  28 May 2019 and plugin works fine.

./check_ssl_cert -H czprgnt141 --ignore-sig-alg --ignore-ocsp -A -c 15 -w 30
SSL_CERT OK - x509 certificate 'czprgnt141.ness.com' from 'Ness CZ CA 01' valid until Dec 19 08:19:32 2020 GMT (expires in 450 days)|days=450;30;15;;

Have you any idea, how to fix this issue on latest Debian 10?

**Comment by matteocorti** [comment]
Hi

I just installed Debian 10 and all the tests are successful. It does not seem a general problem.

Matteo

**Comment by PetrMa** [comment]
Hi, OK, so the 2nd idea is that new OpenSSL has some problem with SHA-1 certificates issued by local CA but I don´t have any idea :-(
All other certificates are checked without issue.

**Comment by matteocorti** [comment]
This could be but I cannot check on my side

**Comment by PetrMa** [comment]
Hi,
I found the issue. 
https://stackoverflow.com/questions/53058362/openssl-v1-1-1-ssl-choose-client-version-unsupported-protocol

Changed the settings MinProtocol = TLSv1.2 to MinProtocol = TLSv1.0 solved the issue.

Thanks for your help.
Petr

**Comment by BloodyIron** [comment]
Thanks for your notes here @matteocorti as I think I have a similar situation in libreNMS for OpenSSL 1.1.1f on Ubuntu 20.04. Ubuntu 22.04 bumps OpenSSL to 3.x so I should try that, thanks! (indirect solution yay)

As for @PetrMa TLSv1.0 is a known insecure protocol and should not be used.
