### ISSUE TITLE
Openssl 1.0.2 not supporting --rsa options

### ISSUE THREAD

**Issue by wimvr** [matteocorti/check_ssl_cert#167]
Version 1.0.2 of openssl does not support sigalgs RSA-PSS. When using the --rsa option, RSA-PSS is added in the sigalgs parameter, and openssl returns man page instead of executing.

Reproduction:
./check_ssl_cert -H www.example.com -c 5 -w 25 --rsa --altnames --host-cn --require-ocsp-stapling --ocsp-warning 36 --ocsp-critical 24

Response:
SSL_CERT CRITICAL www.example.com: No certificate returned

$ openssl version
OpenSSL 1.0.2t  10 Sep 2019

$ ./check_ssl_cert -V
check_ssl_cert version 1.98.0

OS: Gentoo Linux

**Comment by dilyanpalauzov** [comment]
Openssl 1.0.2 and 1.1.0 have this year their end of life.

Without RSA-PSS TLS1.3 with --rsa will not work.

But “No certificate returned” could mean, that the server has no RSA certificate.

**Comment by dilyanpalauzov** [comment]
TLS 1.3 support was added to openssl in version 1.1.1.

If `--tls1_3` is not explicitly requested, then the -sigalgs can be shortened by removing the “RSA-PSS” algorithms.

**Comment by dilyanpalauzov** [comment]
In the meantime, I changed by mind.  With openssl 1.1.1 if no specific protocol is requested, TLS 1.3 will be used, even when `--tls1_3` was not passed.

I see these options:
* if `--no-tls1_3` is passed, then RSA-PSS+ can be removed,
* if `--tls1_2/--tls1/--tls1_1` is passed, then RSA-PSS+ can be removed

**Comment by dilyanpalauzov** [comment]
The `./check_ssl_cert --help` emits:
```
      --ecdsa                      cipher selection: force ECDSA authentication
      --rsa                        cipher selection: force RSA authentication
```
These options are now not directly related to the cipher selerion: for TLS 1.3 the options do not do cipher selection.

**Comment by matteocorti** [comment]
They are, with `-ecds` the signature algorithms are set to `ECDSA+SHA1:ECDSA+SHA224:ECDSA+SHA384:ECDSA+SHA256:ECDSA+SHA512` and with `-rsa` to `RSA+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA224:RSA+SHA1` or `RSA-PSS+SHA512:RSA-PSS+SHA384:RSA-PSS+SHA256:RSA+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA224:RSA+SHA1`

**Comment by dilyanpalauzov** [comment]
I mean over TLS 1.3 the same cipher is used for RSA and ECDSA signatures.  But --help states, that different ciphers are used for RSA and ECDSA.

**Comment by matteocorti** [comment]
Maybe I did something wrong but at the moment they are not

 * with `--rsa` and TLS 1.3: `RSA-PSS+SHA512:RSA-PSS+SHA384:RSA-PSS+SHA256:RSA+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA224:RSA+SHA1`
 * with `--ecdsa` and TLS 1.3: `ECDSA+SHA1:ECDSA+SHA224:ECDSA+SHA384:ECDSA+SHA256:ECDSA+SHA512`

**Comment by dilyanpalauzov** [comment]
I object only the use of the word **cipher** in the output of `--help`.

**Comment by dilyanpalauzov** [comment]
Proposed wording
```
      --ecdsa                      signature algorithm selection: force ECDSA certificate
      --rsa                        signature algorithm selection: force RSA certificate
```
