### ISSUE TITLE
Argument checks consider mandatory arguments beginning with a - as an argument

### ISSUE THREAD

**Issue by matteocorti** [matteocorti/check_ssl_cert#171]
**Describe the bug**

Several options require an argument. If the argument is not specified the next option (beginning with -) is considered the argument

**To Reproduce**

`./check_ssl_cert -H -d`

generates

SSL_CERT CRITICAL -d: No certificate returned

**Expected behavior**

An error (unknown) should be generated

**System (please complete the following information):**

 - OS: any
 - OS Version: any
 - check_ssl_cert Version: 1.98.0

**Comment by dilyanpalauzov** [comment]
Indeed, `./check_ssl_cert --dane -H mail.aegee.org` does not work, one has to use `--dane 1 -H mail.aegee.org`.   The logic here shall mimic [getopt_long(3)](http://man7.org/linux/man-pages/man3/getopt.3.html),  If I remember correctly, after one-letter option with optional parameter, it must be glued immediately after the option.

E.g. if after -p the parameter is optional, one can call `X -p -y` to pass -p and -y as two switches and -p not receiving parameter, or `X -pp -y' to pass two switches, -p and -y and -p having a parameter.

For long option, the gluing does work (as far as I remember) by using = and then the value. E.g. if after --ab the parameter is optional, calling `X --ab -c` turns on ab without paramater, and `X --ab=-c -c` turns the option ab on with value -c, beside turning on the -c switch.

**Comment by dilyanpalauzov** [comment]
Corollary: after long options, either space or equal sign must be accepted, [bash completion](https://github.com/scop/bash-completion) had some code to deal with this

**Comment by matteocorti** [comment]
For the moment I will fix the bug and leave the processing of options with `=` for the future. Sadly there is no portable solution (Bash, GNU and BDS are not really handling getopts the same way).

**Comment by dilyanpalauzov** [comment]
I do not know what are the criteria for closing this, but  `./check_ssl_cert --dane  -H mail.aegee.org` fails with `SSL_CERT UNKNOWN: invalid option: mail.aegee.org`.  I would expect, that --dane without parameters verifies if any TLSA record matches according to OpenSSL, and `--dane 301` verifies, if any “TLSA 3 0 1 " record matches.  Currently the former behavior must be enforced with `./check_ssl_cert --dane 1 -H mail.aegee.org`

**Comment by matteocorti** [comment]
I am closing it since it works:

```
$ ./check_ssl_cert --dane -H mail.aegee.org
SSL_CERT OK - x509 certificate 'mail.aegee.org' from 'Let's Encrypt Authority X3' valid until Nov 19 14:48:50 2019 GMT (expires in 32 days)|days=32;;;;
```

**Comment by matteocorti** [comment]
You were right. There was a bug. I fixed it in the release 1.100.0

**Comment by dilyanpalauzov** [comment]
My /bin/sh is symlink to dash, installed in 2014.  With these modifications:
```diff
diff --git a/check_ssl_cert b/check_ssl_cert
--- a/check_ssl_cert
+++ b/check_ssl_cert
@@ -1146,17 +1146,20 @@ main() {
 
                # check the second parameter if it exist
                if [ $# -gt 1 ] ; then
+                   echo MMMM1"${2#?}"yy  "${2%${2#?}}"x
 
                    if [ "${2%${2#?}}"x = '-x' ] ; then
+                        echo MMM2
                        DANE=1
                        shift
                    else
+                        echo MMM3
                        DANE=$2
                        shift 2
                    fi
 
                else
-
+                    echo MMM4
                    DANE=1
                     shift
 
```
`./check_ssl_cert --dane -H mail.aegee.org` prints:

```
MMMM1Hyy x
MMM3
SSL_CERT UNKNOWN: invalid option: mail.aegee.org
```

**Comment by matteocorti** [comment]
I have to take a look. My goal is to keep the script POSIX compliant. So it should work also with dash.

On my machine (macOS) with dash I get a different error:

```
$ ./check_ssl_cert --dane -H mail.aegee.org
SSL_CERT UNKNOWN: invalid option: --dane
```

**Comment by dilyanpalauzov** [comment]
With most current dash from git://git.kernel.org/pub/scm/utils/dash/dash.git, everything works as expected with `$ ./check_ssl_cert --dane -H mail.aegee.org`.  But its dash.1 states:
```
DESCRIPTION
     dash is the standard command interpreter for the system.  The current
     version of dash is in the process of being changed to conform with the
     POSIX 1003.2 and 1003.2a specifications for the shell.
```
So dash is neither POSIX 1003.2 nor 1003.2a (I do not know right now, if this is significant here).

**Comment by matteocorti** [comment]
Mmmm with my version of dash (I didn't find a way to print dash version number) it works:

```
$ dash ./check_ssl_cert --dane -H mail.aegee.org
SSL_CERT OK - x509 certificate 'mail.aegee.org' from 'Let's Encrypt Authority X3' valid until Nov 19 14:48:50 2019 GMT (expires in 29 days)|days=29;;;;
```
