### ISSUE TITLE
Add HTTP/2 to the possible protocols

### ISSUE THREAD

**Issue by dilyanpalauzov** [matteocorti/check_ssl_cert#185]
I suspect my server that is serves HTTPS/1.1 reliably, but sometimes has problems with HTTP/2 .

Please add to the supported protocols HTTP2 and when using it pass `-alpn h2` to s_client.  I do not know if further changes are necessary, like encoding the request headers.

**Comment by matteocorti** [comment]
Hi, is there a server that I could use to test?

**Comment by matteocorti** [comment]
I tested with an HTTP/2-only server (rwserve.readwritetools.com) and I don't get any problem.

**Comment by matteocorti** [comment]
I re-read your comment: I understand now. You want an option to force HTTP/2.
OK, I'll take a look

**Comment by matteocorti** [comment]
It seems that `-alpn` will negotiate HTTP/2 and that different headers are not needed
