### ISSUE TITLE
unable to fetch the CA issuer certificate (unsupported protocol)

### ISSUE THREAD

**Issue by bitboy85** [matteocorti/check_ssl_cert#187]
**Describe the bug**\
I'm checking a MS Exchangeserver with a root CA of our company. I'm getting the above error.
The root ca is installed on the machine in /usr/local/share/ca-certificates/root-ca.crt and i already ran sudo update-ca-certificates. a copy of the root ca also exists in /etc/ssl/certs/.

**To Reproduce**\
unknown

**Expected behavior**\
The root-ca can be validated

**System (please complete the following information):**\
 - OS: Rasbian Buster
 - OS Version: Latest
 - check_ssl_cert Version: Latest

**Additional context/output**\
[DBG] storing a copy of the retrieved certificate in /tmp/hostname-443.crt
[DBG] storing a copy of the OpenSSL errors in /tmp/hostname-443.error
parsing the x509 certificate file
[DBG] ISSUERS =
[DBG]           ROOT-CA
unable to fetch the CA issuer certificate (unsupported protocol)

[DBG] Error: verify error:num=21:unable to verify the first certificate
[DBG] Error: verify return:1
[DBG] Error: read:errno=0
[DBG] CRITICAL >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[DBG] prepend_critical_message: new message    = Cannot verify certificate: unable to get local issuer certificate, unable to verify the first certificate

**Comment by matteocorti** [comment]
Which command line options are you using?

**Comment by matteocorti** [comment]
Could you please post the complete debugging output?

**Comment by bitboy85** [comment]
Command is: v./check_ssl_cert -H host.fqdn -v -d

**Comment by bitboy85** [comment]
Command is: ./check_ssl_cert -H host.fqdn -v -d
[Output.txt](https://github.com/matteocorti/check_ssl_cert/files/4127389/Output.txt)

**Comment by matteocorti** [comment]
The first problem I see:

[DBG] storing a copy of the retrieved certificate in /tmp/host.fqdn-443.crt
cp: regul‰re Datei '/tmp/host.fqdn-443.crt' kann nicht angelegt werden: Keine Berechtigung
[DBG] storing a copy of the OpenSSL errors in /tmp/host.fqdn-443.error
cp: regul‰re Datei '/tmp/host.fqdn-443.error' kann nicht angelegt werden: Keine Berechtigung
parsing the x509 certificate file

Try to use a writable dir with --temp

**Comment by bitboy85** [comment]
I forgot to mention that i tried with sudo too.
The cp works but the main issue is still there.

**Comment by matteocorti** [comment]
It seems that OpenSSL ist not able to validate. Can you please execute OpenSSL directly (as in the debugging output without the redirect)

```
/usr/bin/openssl s_client    -crlf -ign_eof  -connect host.fqdn:443 -servername host.fqdn -showcerts -verify 6     
```

**Comment by bitboy85** [comment]
This is the Output:

```
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 2211 bytes and written 478 bytes
Verification error: unable to verify the first certificate
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES128-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2

    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1580305613
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)
    Extended master secret: yes
---
read:errno=104
```

**Comment by matteocorti** [comment]
The error is coming from OpenSSL and has nothing to do with the plugin. This has to be solved by someone with access to the infrastructure.

**Comment by bitboy85** [comment]
If anyone else hit here by web search.
The solution seems to be to
1. Make sure the certificate is in crt format
2. copy it to a subfolder of /usr/local/share/ca-certificates/
3. run update-ca-certificates
4. To check: Your cert needs to be listed in the file /etc/ssl/certs/ca-certificates.crt

**Comment by matteocorti** [comment]
Thanks!
