### ISSUE TITLE
Getting error on run on check_ssl_cert -t 30 -w 10 -L 'A+' -H hostname.com

### ISSUE THREAD

**Issue by naveenlr92** [matteocorti/check_ssl_cert#195]
check_ssl_cert -t 30 -w 10 -L 'A+' -H hostname.com taking too much time to run,

it's showing error in Nagios "Cannot check status on SSL Labs: Too many new assessments too fast. Please slow down."

**Comment by matteocorti** [comment]
You specified `-L A+` which requires Qualy's SSL Labs`. Qualy's servers do not have enough capacity and answers "Too many new assessments too fast. Please slow down"/

You can

- wait that Qualy's answers
- remove the `-L` flag
