### ISSUE TITLE
nmap does not scan ipv6-only host

### ISSUE THREAD

**Issue by MEschenbacher** [matteocorti/check_ssl_cert#197]
**Describe the bug**\
The `-6` switch is not propagated to `nmap` when using a nmap-enabling-switch (e.g. `--no-require-ssl2`) on an IPv6-only host, instead and a warning is printed.

**To Reproduce**\
Execute `check_ssl_cert -H ipv6-only-host.example.org -p 1337 --require-no-ssl2 -6` on an ipv6-only host and see
```
Warning: Hostname ipv6-only-host.example.org resolves, but not to any IPv4 address. Try scanning with -6
Failed to resolve "ipv6-only-host.example.org".
WARNING: No targets were specified, so 0 hosts scanned.
SSL_CERT OK - x509 certificate '[...]' from 'Some CA' valid until some time GMT (expires in 1337 days)|days=1337;;;;
```

The same warning is printed when I omit the `-6` switch.

**Expected behavior**\
No warning to be printed and the check for e.g. `--require-no-ssl2` to be executed. I also expect the command to succeed when I omit the `-6` switch.

**System (please complete the following information):**\
 - OS: Debian 10
 - OS Version: Debian 10
 - check_ssl_cert Version: current master b76917145fa664c2bc31fb6723c8adf9da196483

**Comment by matteocorti** [comment]
Can you give an example I can test?

**Comment by MEschenbacher** [comment]
`ip6.kajt.de`

**Comment by matteocorti** [comment]
Failed to resolve "ip6.kajt.de".
WARNING: No targets were specified, so 0 hosts scanned.
SSL_CERT CRITICAL: ip6.kajt.de is invalid

**Comment by matteocorti** [comment]
It seems that nmap is not accepting hosts with IPv6 only addresses even with the `-6` switch

```
$ /usr/local/bin/nmap -6 -Pn -p "1337" -6 --script ssl-enum-ciphers ip6.kajt.de
Starting Nmap 7.80 ( https://nmap.org ) at 2020-05-18 17:29 CEST
Failed to resolve "ip6.kajt.de".
WARNING: No targets were specified, so 0 hosts scanned.
Nmap done: 0 IP addresses (0 hosts up) scanned in 0.27 seconds
```

**Comment by matteocorti** [comment]
Seems to work only if the FQDN is resolved

```
$ /usr/local/bin/nmap -6 -Pn -p "1337" -6 --script ssl-enum-ciphers 2a01:4f8:d0:8242::1
Starting Nmap 7.80 ( https://nmap.org ) at 2020-05-18 17:32 CEST
Nmap scan report for re.kajt.de (2a01:4f8:d0:8242::1)
Host is up (0.000084s latency).

PORT     STATE    SERVICE
1337/tcp filtered waste

Nmap done: 1 IP address (1 host up) scanned in 1.15 seconds
```

**Comment by MEschenbacher** [comment]
Hint: the host I provided uses port 443 (https).

The exact same command you posted (with port 443)
```
/usr/local/bin/nmap -6 -Pn -p "443" -6 --script ssl-enum-ciphers ip6.kajt.de
```
executes fine on my end. Do you have ipv6-connectivity?

**Comment by MEschenbacher** [comment]
```
nmap -6 -Pn -p "443" -6 --script ssl-enum-ciphers ip6.kajt.de
Starting Nmap 7.80 ( https://nmap.org ) at 2020-05-18 17:33 CEST
Nmap scan report for ip6.kajt.de (2a01:4f8:d0:8242::1)
Host is up (0.016s latency).
rDNS record for 2a01:4f8:d0:8242::1: re.kajt.de

PORT    STATE SERVICE
443/tcp open  https
| ssl-enum-ciphers: 
|   TLSv1.2: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (ecdh_x25519) - A
|       TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (dh 4096) - A
|       TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (dh 4096) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (ecdh_x25519) - A
|       TLS_DHE_RSA_WITH_AES_256_CCM_8 (dh 4096) - A
|       TLS_DHE_RSA_WITH_AES_256_CCM (dh 4096) - A
|       TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (dh 4096) - A
|       TLS_DHE_RSA_WITH_AES_256_CBC_SHA (dh 4096) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (ecdh_x25519) - A
|       TLS_DHE_RSA_WITH_AES_128_CCM_8 (dh 4096) - A
|       TLS_DHE_RSA_WITH_AES_128_CCM (dh 4096) - A
|       TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (dh 4096) - A
|       TLS_DHE_RSA_WITH_AES_128_CBC_SHA (dh 4096) - A
|     compressors: 
|       NULL
|     cipher preference: server
|     warnings: 
|       Key exchange (ecdh_x25519) of lower strength than certificate key
|_  least strength: A

Nmap done: 1 IP address (1 host up) scanned in 2.98 seconds
```

**Comment by matteocorti** [comment]
It does not in my case

```
$ /usr/local/bin/nmap -6 -Pn -p "443" -6 --script ssl-enum-ciphers ip6.kajt.de
Starting Nmap 7.80 ( https://nmap.org ) at 2020-05-18 17:44 CEST
Failed to resolve "ip6.kajt.de".
WARNING: No targets were specified, so 0 hosts scanned.
Nmap done: 0 IP addresses (0 hosts up) scanned in 0.31 seconds
```

But it seems I have a general problem

```
$ ping6 ip6.kajt.de
ping6: UDP connect: No route to host
```

I'll check on another host

**Comment by matteocorti** [comment]
Seems to work on Linux but not on macOS

**Comment by matteocorti** [comment]
I have an IPv6 problem

**Comment by MEschenbacher** [comment]
Can you confirm my bug report?

> It seems that nmap is not accepting hosts with IPv6 only addresses even with the `-6` switch
> 
> ```
> $ /usr/local/bin/nmap -6 -Pn -p "1337" -6 --script ssl-enum-ciphers ip6.kajt.de
> Starting Nmap 7.80 ( https://nmap.org ) at 2020-05-18 17:29 CEST
> Failed to resolve "ip6.kajt.de".
> WARNING: No targets were specified, so 0 hosts scanned.
> Nmap done: 0 IP addresses (0 hosts up) scanned in 0.27 seconds
> ```

Can you then confirm my bug report?

**Comment by matteocorti** [comment]
It's a local problem. With the latest commit the problem you reported should be corrected. Can you confirm?

**Comment by MEschenbacher** [comment]
I checked out the new master 029847a9433ed3298e96f0af1727b650126c43d2 and can confirm that `-6` gets now passed to nmap. Thank you for your quick reaction!

However I still get the same nmap warning if I omit `-6`
```
$ check_ssl_cert -H ip6.kajt.de -p 443 --require-no-ssl2
Failed to resolve "".
Warning: Hostname ip6.kajt.de resolves, but not to any IPv4 address. Try scanning with -6
Failed to resolve "ip6.kajt.de".
WARNING: No targets were specified, so 0 hosts scanned.
SSL_CERT OK - x509 certificate '*.kajt.de' from 'Let's Encrypt Authority X3' valid until Aug  8 04:24:20 2020 GMT (expires in 81 days)|days=81;;;;
```

I think this still an issue with nmap, which always assumes legacy-ip unless you tell it to use ipv6. Should we work around this behaviour in `check_ssl_cert`?

**Comment by matteocorti** [comment]
I'll take a look

**Comment by matteocorti** [comment]
Should be fixed. I first do a dry run of nmap to check if it's able to resolve. If not I try with -6

**Comment by MEschenbacher** [comment]
Works like a charm! Thank you once again :)

**Comment by matteocorti** [comment]
I’ll release a new version as soon as possible.

**Comment by matteocorti** [comment]
I released a new release. Thanks to you for the report
