### ISSUE TITLE
Check whether an ISSUER does not match

### ISSUE THREAD

**Issue by aslafy-z** [matteocorti/check_ssl_cert#199]
**Is your feature request related to a problem? Please describe.**
I'm unable to check whether a certificate is not issued by some organization.

**Describe the solution you'd like**
Either be able to use negative lookahead, or have a flag that invert the issuer match.

**Describe alternatives you've considered**
- Use negative lookahead regex but grep needs an additional flag (`-P` only available on GNU).

**Comment by aslafy-z** [comment]
Awesome! Thanks for this quick release.

**Comment by matteocorti** [comment]
Let me know if it works as intended
