### ISSUE TITLE
Checking all supplied chain certificates

### ISSUE THREAD

**Issue by lazyfrosch** [matteocorti/check_ssl_cert#200]
**Is your feature request related to a problem? Please describe.**

We use several wildcard certificates, that are also signed by a ~~now expired~~ renewed CA, where the old certificate version is shipped in the chain.

Basically OpenSSL seems to handle this correctly, but other TLS implementations can break when checking the presented chain certificate.

A write up:
https://ohdear.app/blog/resolving-the-addtrust-external-ca-root-certificate-expiration

**Describe the solution you'd like**

I guess it would be great when we check all the presented chain certificates for trust, and at least warn, if one of them is not valid or trusted.

---

This is merely a suggestion, to start discussion and here thoughts from the community.

**Comment by lazyfrosch** [comment]
For me at least [libgcrypt](https://directory.fsf.org/wiki/Libgcrypt) is having problems with this.

**Comment by matteocorti** [comment]
Hi. Do you have an example I could test?

**Comment by lazyfrosch** [comment]
I guess, https://nextcloud.netways.de - but we will remove the chain soonish. I can arrange further testing then.

**Comment by lazyfrosch** [comment]
Also a document by the CA in question: https://support.sectigo.com/Com_KnowledgeDetailPage?Id=kA03l00000117LT

**Comment by grizzlydev-sarl** [comment]
I did something to check the whole chain a while ago, but never had the time to make a pull request (https://github.com/grizzlydev-sarl/check_ssl_cert/blob/master/check_ssl_cert).
(We're also having problem with some of our old certificates because of expired element in the chain, so... maybe I'll make that pull request after all)

**Comment by lazyfrosch** [comment]
@grizzlydev-sarl nice, maybe we could add tests for trust and if the chain cert matches for the cert later.

**Comment by ingardm** [comment]
After this weekend this pull request would be most welcome :)

**Comment by ingardm** [comment]
> I started something to check the whole chain a while ago, but never had the time to finish and make a pull request (https://github.com/grizzlydev-sarl/check_ssl_cert/blob/master/check_ssl_cert).
> (We're also having problem with some of our old certificates because of expired element in the chain, so... maybe I'll make that pull request after all)

If element 1 is due to expire soon, the check will give a warning for element 1, instead of critical for expired element 3.

**Comment by grizzlydev-sarl** [comment]
Yeah, I noticed that. As I mentionned, I never got around to finish the implementation, and my modifications were based on an old version of the plugin. 
Anyways, I squashed everything, corrected the problem above and made the pull request.
