### ISSUE TITLE
check_ssl_cert is not working behind proxy, while check_http works

### ISSUE THREAD

**Issue by phamlankt** [matteocorti/check_ssl_cert#203]
Hello,

**Describe the bug**\
I would like to ask for your help to point out what I might do wrong here. So I used the check_http and check_ssl_cert to check for certificate validation behind a proxy. It works for check_http but not for check_ssl_cert. I got time out, it is like it can not get to the host.
# /usr/lib64/nagios/plugins/check_http -I 10.240.120.1 -p 3128  -S -j CONNECT -H myweb.mydomain.com -C 30 --continue-after-certificate        
SSL OK - Certificate '*.mydomain.com' will expire in 228 days on 2021-01-19 00:59 +0100/CET.
HTTP OK: HTTP/1.1 200 OK - 30719 bytes in 0.040 second response time |time=0.039702s;;;0.000000 size=30719B;;;0

# /tmp/check_ssl_cert --proxy 10.240.120.1:3128 -H  myweb.mydomain.com --ignore-ocsp
SSL_CERT CRITICAL myweb.mydomain.com: Timeout after 15 seconds
Error(s):
    SSL_CERT CRITICAL myweb.mydomain.com: No certificate returned
    SSL_CERT CRITICAL myweb.mydomain.com: SSL error:
    SSL_CERT CRITICAL myweb.mydomain.com: Timeout after 15 seconds

**To Reproduce**\
Steps to reproduce the behavior.

**Expected behavior**\
check_ssl_cert should work behind proxy, should not get time out

**System (please complete the following information):**\
 - OS: CentOS 8
 - OS Version: [e.g. 22]
 - check_ssl_cert Version: 1.113.0

Many thanks in advance!

**Comment by matteocorti** [comment]
Can you please post the debugging output (with the `-d` argument)?

**Comment by phamlankt** [comment]
Hi @matteocorti ,
Here is the debugging output, i just replace the real website with myweb.mydomain.com. Please help to check! Thanks. 
root@myserver ~]# /tmp/check_ssl_cert --proxy 10.240.120.1:3128 -H myweb.mydomain.com --ignore-ocsp -d
[DBG] Command line arguments: --proxy 10.240.120.1:3128 -H myweb.mydomain.com --ignore-ocsp -d
[DBG] ROOT_CA =
[DBG] cURL binary not needed. SSL Labs = , OCSP =
[DBG] nmap binary not needed. No disallowed protocols
expect not available
timeout available (/usr/bin/timeout)
[DBG] perl available: /usr/bin/perl
[DBG] date available: /usr/bin/date
found GNU date with timestamp support: enabling date computations
[DBG] check_ssl_cert version: 1.114.0
[DBG] OpenSSL binary: /usr/bin/openssl
[DBG] OpenSSL version: OpenSSL 1.1.1c FIPS  28 May 2019
[DBG] OpenSSL configuration directory: /etc/pki/tls
[DBG] 142 root certificates installed by default
[DBG]  System info: Linux myserver.tmsp.local 4.18.0-147.8.1.el8_1.x86_64 #1 SMP Thu Apr 9 13:49:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[DBG] Date computation: GNU
[DBG] '/usr/bin/openssl s_client' supports '-servername': using -servername myweb.mydomain.com
[DBG] '/usr/bin/openssl s_client' supports '-name': using myserver.tmsp.local
[DBG] '/usr/bin/openssl s_client' supports '-xmpphost': using -xmpphost myweb.mydomain.com
[DBG] temporary file /tmp/check_ssl_cert0ENgWV created
[DBG] temporary file /tmp/check_ssl_certCfsfs2 created
downloading certificate to /tmp
[DBG] myweb.mydomain.com is not an IP address
[DBG] executing with timeout (15s): printf 'HEAD / HTTP/1.1\nHost: myweb.mydomain.com\nUser-Agent: check_ssl_cert/1.114.0\nConnection: close\n\n' | /usr/bin/openssl s_client    -crlf -ign_eof  -connect myweb.mydomain.com:443 -servername myweb.mydomain.com -showcerts -verify 6       2> /tmp/check_ssl_certCfsfs2 1> /tmp/check_ssl_cert0ENgWV
[DBG] /usr/bin/timeout 15 /bin/sh -c "printf 'HEAD / HTTP/1.1\nHost: myweb.mydomain.com\nUser-Agent: check_ssl_cert/1.114.0\nConnection: close\n\n' | /usr/bin/openssl s_client    -crlf -ign_eof  -connect myweb.mydomain.com:443 -servername myweb.mydomain.com -showcerts -verify 6       2> /tmp/check_ssl_certCfsfs2 1> /tmp/check_ssl_cert0ENgWV"
[DBG] CRITICAL >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[DBG] prepend_critical_message: new message    = Timeout after 15 seconds
[DBG] prepend_critical_message: HOST           = myweb.mydomain.com
[DBG] prepend_critical_message: CN             =
[DBG] prepend_critical_message: SNI            =
[DBG] prepend_critical_message: FILE           =
[DBG] prepend_critical_message: SHORTNAME      = SSL_CERT
[DBG] prepend_critical_message: MSG            =
[DBG] prepend_critical_message: CRITICAL_MSG   =
[DBG] prepend_critical_message: ALL_MSG 1      =
[DBG] prepend_critical_message: MSG 2          = SSL_CERT CRITICAL myweb.mydomain.com: Timeout after 15 seconds
[DBG] prepend_critical_message: CRITICAL_MSG 2 = SSL_CERT CRITICAL myweb.mydomain.com: Timeout after 15 seconds
[DBG] prepend_critical_message: ALL_MSG 2      = \n    SSL_CERT CRITICAL myweb.mydomain.com: Timeout after 15 seconds
[DBG] CRITICAL <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
[DBG] storing a copy of the retrieved certificate in myweb.mydomain.com.crt
[DBG] Return value of the command = 124
[DBG] storing a copy of the retrieved certificate in /tmp/myweb.mydomain.com-443.crt
[DBG] storing a copy of the OpenSSL errors in /tmp/myweb.mydomain.com-443.error
[DBG] SSL error: verify depth is 6
[DBG] CRITICAL >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[DBG] prepend_critical_message: new message    = SSL error:
[DBG] prepend_critical_message: HOST           = myweb.mydomain.com
[DBG] prepend_critical_message: CN             =
[DBG] prepend_critical_message: SNI            =
[DBG] prepend_critical_message: FILE           =
[DBG] prepend_critical_message: SHORTNAME      = SSL_CERT
[DBG] prepend_critical_message: MSG            = SSL_CERT CRITICAL myweb.mydomain.com: Timeout after 15 seconds
[DBG] prepend_critical_message: CRITICAL_MSG   = SSL_CERT CRITICAL myweb.mydomain.com: Timeout after 15 seconds
[DBG] prepend_critical_message: ALL_MSG 1      = \n    SSL_CERT CRITICAL myweb.mydomain.com: Timeout after 15 seconds
[DBG] prepend_critical_message: MSG 2          = SSL_CERT CRITICAL myweb.mydomain.com: SSL error:
[DBG] prepend_critical_message: CRITICAL_MSG 2 = SSL_CERT CRITICAL myweb.mydomain.com: Timeout after 15 seconds
[DBG] prepend_critical_message: ALL_MSG 2      = \n    SSL_CERT CRITICAL myweb.mydomain.com: SSL error: \n    SSL_CERT CRITICAL myweb.mydomain.com: Timeout after 15 seconds
[DBG] CRITICAL <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Error: verify depth is 6
[DBG] CRITICAL >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[DBG] prepend_critical_message: new message    = No certificate returned
[DBG] prepend_critical_message: HOST           = myweb.mydomain.com
[DBG] prepend_critical_message: CN             =
[DBG] prepend_critical_message: SNI            =
[DBG] prepend_critical_message: FILE           =
[DBG] prepend_critical_message: SHORTNAME      = SSL_CERT
[DBG] prepend_critical_message: MSG            = SSL_CERT CRITICAL myweb.mydomain.com: SSL error:
[DBG] prepend_critical_message: CRITICAL_MSG   = SSL_CERT CRITICAL myweb.mydomain.com: Timeout after 15 seconds
[DBG] prepend_critical_message: ALL_MSG 1      = \n    SSL_CERT CRITICAL myweb.mydomain.com: SSL error: \n    SSL_CERT CRITICAL myweb.mydomain.com: Timeout after 15 seconds
[DBG] prepend_critical_message: MSG 2          = SSL_CERT CRITICAL myweb.mydomain.com: No certificate returned
[DBG] prepend_critical_message: CRITICAL_MSG 2 = SSL_CERT CRITICAL myweb.mydomain.com: Timeout after 15 seconds
[DBG] prepend_critical_message: ALL_MSG 2      = \n    SSL_CERT CRITICAL myweb.mydomain.com: No certificate returned\n    SSL_CERT CRITICAL myweb.mydomain.com: SSL error: \n    SSL_CERT CRITICAL myweb.mydomain.com: Timeout after 15 seconds
[DBG] CRITICAL <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
[DBG] cleaning up temporary files
[DBG] /tmp/check_ssl_cert0ENgWV
/tmp/check_ssl_certCfsfs2
[DBG] exiting with CRITICAL
[DBG] ALL_MSG = \n    SSL_CERT CRITICAL myweb.mydomain.com: No certificate returned\n    SSL_CERT CRITICAL myweb.mydomain.com: SSL error: \n    SSL_CERT CRITICAL myweb.mydomain.com: Timeout after 15 seconds
[DBG] number of errors = 3
SSL_CERT CRITICAL myweb.mydomain.com: Timeout after 15 seconds
Error(s):
    SSL_CERT CRITICAL myweb.mydomain.com: No certificate returned
    SSL_CERT CRITICAL myweb.mydomain.com: SSL error:
    SSL_CERT CRITICAL myweb.mydomain.com: Timeout after 15 seconds

**Comment by matteocorti** [comment]
OpenSSL `s_client` now has a `-proxy` option that should be used when present

**Comment by phamlankt** [comment]
sorry, so what should I change here?

**Comment by matteocorti** [comment]
It's not something you should do, it's something I should implement :-)

OpenSSL `s_client` does not support the `HTTP_PROXY` variable but has an own `-proxy` option.

I'll try to implement a fix a soon as possible

**Comment by matteocorti** [comment]
I just committed a fix. Can you please test again?

**Comment by matteocorti** [comment]
My error I’ll fix it as soon as possibile.

**Comment by matteocorti** [comment]
I just committed a fix. Can you please test again?

**Comment by phamlankt** [comment]
Hello @matteocorti , 

Thanks a lot for your work. The check via proxy is now working. However when i compare the output from command WITHOUT proxy (from another machine which has direct internet access) gives correct validation date for element 2 and element 3 in the chain.
[root@my-server check_ssl_cert]# ./check_ssl_cert  -H mydomain.com --ignore-ocsp -d
[DBG] Command line arguments: -H mydomain.com --ignore-ocsp -d
[DBG] -c specified: 15
[DBG] ROOT_CA =
[DBG] cURL binary not needed. SSL Labs = , OCSP =
[DBG] nmap binary not needed. No disallowed protocols
expect not available
timeout available (/usr/bin/timeout)
[DBG] perl available: /usr/bin/perl
[DBG] date available: /usr/bin/date
found GNU date with timestamp support: enabling date computations
[DBG] check_ssl_cert version: 1.115.0
[DBG] OpenSSL binary: /usr/bin/openssl
[DBG] OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
[DBG] OpenSSL configuration directory: /etc/pki/tls
[DBG] 140 root certificates installed by default
[DBG]  System info: Linux my-server 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[DBG] Date computation: GNU
[DBG] '/usr/bin/openssl s_client' supports '-servername': using -servername mydomain.com
[DBG] '/usr/bin/openssl s_client' supports '-name': using my-server
[DBG] '/usr/bin/openssl s_client' supports '-xmpphost': using -xmpphost mydomain.com
[DBG] temporary file /tmp/check_ssl_certr5Omte created
[DBG] temporary file /tmp/check_ssl_certbtcR79 created
downloading certificate to /tmp
[DBG] mydomain.com is not an IP address
[DBG] executing with timeout (120s): printf 'HEAD / HTTP/1.1\nHost: mydomain.com\nUser-Agent: check_ssl_cert/1.115.0\nConnection: close\n\n' | /usr/bin/openssl s_client    -crlf -ign_eof  -connect mydomain.com:443 -servername mydomain.com  -showcerts -verify 6       2> /tmp/check_ssl_certbtcR79 1> /tmp/check_ssl_certr5Omte
[DBG] /usr/bin/timeout 120 /bin/sh -c "printf 'HEAD / HTTP/1.1\nHost: mydomain.com\nUser-Agent: check_ssl_cert/1.115.0\nConnection: close\n\n' | /usr/bin/openssl s_client    -crlf -ign_eof  -connect mydomain.com:443 -servername mydomain.com  -showcerts -verify 6       2> /tmp/check_ssl_certbtcR79 1> /tmp/check_ssl_certr5Omte"
[DBG] storing a copy of the retrieved certificate in mydomain.com.crt
[DBG] Return value of the command = 0
[DBG] storing a copy of the retrieved certificate in /tmp/mydomain.com-443.crt
[DBG] storing a copy of the OpenSSL errors in /tmp/mydomain.com-443.error
parsing the x509 certificate file
[DBG] [DBG] ISSUERS =
[DBG]     COMODO RSA Organization Validation Secure Server CA
COMODO RSA Certification Authority
COMODO RSA Certification Authority
[DBG] subject= ....
[DBG] CN         = *.mydomain.com
[DBG] CA         = COMODO RSA Organization Validation Secure Server CA
[DBG] CA         = COMODO RSA Certification Authority
[DBG] CA         = COMODO RSA Certification Authority
[DBG] SERIAL     = 18B20E92045C094DBC7FB145E18E9DE1
[DBG] FINGERPRINT= 6A:C9:76:61:0E:CE:2E:10:F2:88:97:9B:0C:F9:A0:DD:22:46:09:e7
[DBG] OCSP_URI   = http://ocsp.comodoca.com
[DBG] ISSUER_URI = http://crt.comodoca.com/COMODORSAOrganizationValidationSecureServerCA.crt
[DBG]     Signature Algorithm: sha256WithRSAEncryption
[DBG] subjectAlternativeName = *.mydomain.com mydomain.com
[DBG] Checking expiration date
[DBG] Nb certificates in CA chain: 3
[DBG] Checking expiration date of element 1
[DBG] Validity date on cert element 1 is Jan 18 23:59:59 2021 GMT
[DBG] Date computations: GNU
[DBG] Computing number of hours until 'Jan 18 23:59:59 2021 GMT'
[DBG] Hours until Jan 18 23:59:59 2021 GMT: 5433
[DBG] executing: /usr/bin/openssl x509 -noout -checkend 1296000 on cert element 1
[DBG] executing: /usr/bin/openssl x509 -noout -checkend 1728000 on cert element 1
[DBG] Checking expiration date of element 2
[DBG] Validity date on cert element 2 is Feb 11 23:59:59 2029 GMT
[DBG] Date computations: GNU
[DBG] Computing number of hours until 'Feb 11 23:59:59 2029 GMT'
[DBG] Hours until Feb 11 23:59:59 2029 GMT: 76137
[DBG] executing: /usr/bin/openssl x509 -noout -checkend 1296000 on cert element 2
[DBG] executing: /usr/bin/openssl x509 -noout -checkend 1728000 on cert element 2
[DBG] Checking expiration date of element 3
[DBG] Validity date on cert element 3 is Jan 18 23:59:59 2038 GMT
[DBG] Date computations: GNU
[DBG] Computing number of hours until 'Jan 18 23:59:59 2038 GMT'
[DBG] Hours until Jan 18 23:59:59 2038 GMT: 154449
[DBG] executing: /usr/bin/openssl x509 -noout -checkend 1296000 on cert element 3
[DBG] executing: /usr/bin/openssl x509 -noout -checkend 1728000 on cert element 3
[DBG] output parameters: CA_ISSUER_MATCHED     = COMODO RSA Organization Validation Secure Server CA
[DBG] output parameters: CHECKEDNAMES          =
[DBG] output parameters: CN                    = *.mydomain.com
[DBG] output parameters: DATE                  = Jan 18 23:59:59 2021 GMT
[DBG] output parameters: DAYS_VALID            =  (expires in 226 days)
[DBG] output parameters: DYSPLAY_CN            = '*.mydomain.com'
[DBG] output parameters: OPENSSL_COMMAND       = x509
[DBG] output parameters: SELFSIGNEDCERT        =
[DBG] output parameters: SHORTNAME             = SSL_CERT
[DBG] output parameters: OCSP_EXPIRES_IN_HOURS =
[DBG] output parameters: SSL_LABS_HOST_GRADE   =
SSL_CERT OK - x509 certificate '*.mydomain.com' from 'COMODO RSA Organization Validation Secure Server CA' valid until Jan 18 23:59:59 2021 GMT (expires in 226 days)|days_chain_elem1=226;20;15;; days_chain_elem2=3172;20;15;; days_chain_elem3=6435;20;15;;
[DBG] cleaning up temporary files
[DBG]
/tmp/check_ssl_certr5Omte
/tmp/check_ssl_certbtcR79


But the command WITH proxy gives wrong validation date:
$ ./check_ssl_cert --proxy 10.240.120.1:3128 -H www.mydomain.com --ignore-ocsp -d
[DBG] Command line arguments: --proxy 10.240.120.1:3128 -H www.mydomain.com --ignore-ocsp -d
[DBG] -c specified: 15
[DBG] ROOT_CA =
[DBG] cURL binary not needed. SSL Labs = , OCSP =
[DBG] nmap binary not needed. No disallowed protocols
expect not available
timeout available (/usr/bin/timeout)
[DBG] perl available: /usr/bin/perl
[DBG] date available: /usr/bin/date
found GNU date with timestamp support: enabling date computations
[DBG] check_ssl_cert version: 1.115.0
[DBG] OpenSSL binary: /usr/bin/openssl
[DBG] OpenSSL version: OpenSSL 1.1.1c FIPS  28 May 2019
[DBG] OpenSSL configuration directory: /etc/pki/tls
[DBG] 142 root certificates installed by default
[DBG]  System info: Linux myPC.tmsp.local 4.18.0-147.5.1.el8_1.x86_64 #1 SMP Wed Feb 5 02:00:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[DBG] Date computation: GNU
[DBG] '/usr/bin/openssl s_client' supports '-servername': using -servername www.mydomain.com
[DBG] Adding -proxy 10.240.120.1:3128 to the s_client options
[DBG] '/usr/bin/openssl s_client' supports '-name': using myPC.tmsp.local
[DBG] '/usr/bin/openssl s_client' supports '-xmpphost': using -xmpphost www.mydomain.com
[DBG] temporary file /tmp/check_ssl_certwtlOiq created
[DBG] temporary file /tmp/check_ssl_certP2ZV2j created
downloading certificate to /tmp
[DBG] www.mydomain.com is not an IP address
[DBG] executing with timeout (120s): printf 'HEAD / HTTP/1.1\nHost: www.mydomain.com\nUser-Agent: check_ssl_cert/1.115.0\nConnection: close\n\n' | /usr/bin/openssl s_client    -crlf -ign_eof  -connect www.mydomain.com:443 -servername www.mydomain.com -proxy 10.240.120.1:3128 -showcerts -verify 6       2> /tmp/check_ssl_certP2ZV2j 1> /tmp/check_ssl_certwtlOiq
[DBG] /usr/bin/timeout 120 /bin/sh -c "printf 'HEAD / HTTP/1.1\nHost: www.mydomain.com\nUser-Agent: check_ssl_cert/1.115.0\nConnection: close\n\n' | /usr/bin/openssl s_client    -crlf -ign_eof  -connect www.mydomain.com:443 -servername www.mydomain.com -proxy 10.240.120.1:3128 -showcerts -verify 6       2> /tmp/check_ssl_certP2ZV2j 1> /tmp/check_ssl_certwtlOiq"
[DBG] storing a copy of the retrieved certificate in www.mydomain.com.crt
[DBG] Return value of the command = 0
[DBG] storing a copy of the retrieved certificate in /tmp/www.mydomain.com-443.crt
[DBG] storing a copy of the OpenSSL errors in /tmp/www.mydomain.com-443.error
parsing the x509 certificate file
[DBG] [DBG] ISSUERS =
[DBG]     ssl-inspect.mydomain.com
mydomain-SubCA
issuer=CN = mydomain-RootCA
cannot find the CA Issuers in the certificate: disabling OCSP checks
[DBG] subject=
PremiumSSL Wildcard, CN = *.mydomain.com
[DBG] CN         = *.mydomain.com
[DBG] CA         = ssl-inspect.mydomain.com
[DBG] CA         = mydomain-SubCA
[DBG] CA         = issuer=CN = mydomain-RootCA
[DBG] SERIAL     = 18B20E92045C094DBC7FB145E18E9DE1
[DBG] FINGERPRINT= 6A:C9:76:61:0E:CE:2E:10:F2:88:97:9B:0C:F9:A0:DD:22:46:09:e7
[DBG] OCSP_URI   =
[DBG] ISSUER_URI =
[DBG]         Signature Algorithm: sha256WithRSAEncryption
[DBG] subjectAlternativeName = *.mydomain.com mydomain.com
[DBG] Checking expiration date
[DBG] Nb certificates in CA chain: 3
[DBG] Checking expiration date of element 1
[DBG] Validity date on cert element 1 is Jan 18 23:59:59 2021 GMT
[DBG] Date computations: GNU
[DBG] Computing number of hours until 'Jan 18 23:59:59 2021 GMT'
[DBG] Hours until Jan 18 23:59:59 2021 GMT: 5433
[DBG] executing: /usr/bin/openssl x509 -noout -checkend 1296000 on cert element 1
[DBG] executing: /usr/bin/openssl x509 -noout -checkend 1728000 on cert element 1
[DBG] Checking expiration date of element 2
[DBG] Validity date on cert element 2 is Sep 25 10:31:46 2021 GMT
[DBG] Date computations: GNU
[DBG] Computing number of hours until 'Sep 25 10:31:46 2021 GMT'
[DBG] Hours until Sep 25 10:31:46 2021 GMT: 11420
[DBG] executing: /usr/bin/openssl x509 -noout -checkend 1296000 on cert element 2
[DBG] executing: /usr/bin/openssl x509 -noout -checkend 1728000 on cert element 2
[DBG] Checking expiration date of element 3
[DBG] Validity date on cert element 3 is Feb 20 12:44:47 2029 GMT
[DBG] Date computations: GNU
[DBG] Computing number of hours until 'Feb 20 12:44:47 2029 GMT'
[DBG] Hours until Feb 20 12:44:47 2029 GMT: 76342
[DBG] executing: /usr/bin/openssl x509 -noout -checkend 1296000 on cert element 3
[DBG] executing: /usr/bin/openssl x509 -noout -checkend 1728000 on cert element 3
[DBG] output parameters: CA_ISSUER_MATCHED     = ssl-inspect.mydomain.com
[DBG] output parameters: CHECKEDNAMES          =
[DBG] output parameters: CN                    = *.mydomain.com
[DBG] output parameters: DATE                  = Jan 18 23:59:59 2021 GMT
[DBG] output parameters: DAYS_VALID            =  (expires in 226 days)
[DBG] output parameters: DYSPLAY_CN            = '*.mydomain.com'
[DBG] output parameters: OPENSSL_COMMAND       = x509
[DBG] output parameters: SELFSIGNEDCERT        =
[DBG] output parameters: SHORTNAME             = SSL_CERT
[DBG] output parameters: OCSP_EXPIRES_IN_HOURS =
[DBG] output parameters: SSL_LABS_HOST_GRADE   =
SSL_CERT OK - x509 certificate '*.mydomain.com' from 'ssl-inspect.mydomain.com' valid until Jan 18 23:59:59 2021 GMT (expires in 226 days)|days_chain_elem1=226;20;15;; days_chain_elem2=475;20;15;; days_chain_elem3=3180;20;15;;
[DBG] cleaning up temporary files
[DBG]
/tmp/check_ssl_certwtlOiq
/tmp/check_ssl_certP2ZV2j

Below is the result via check from digicert.com
![image](https://user-images.githubusercontent.com/45233442/83946496-953dff00-a811-11ea-8571-eaf8d85ab14a.png)

**Comment by matteocorti** [comment]
When using the proxy you get another certificate (not from Comodo). As I cannot test it's difficult to say what is happening.

**Comment by phamlankt** [comment]
Thank you very much for your help. It took a while to have this fixed. I checked with the proxy team and after they removed the ssl inspection on the URL that i wanted to check the certificate, now it shows the correct results.
