### ISSUE TITLE
OCSP error

### ISSUE THREAD

**Issue by hgpit** [matteocorti/check_ssl_cert#210]
**Describe the bug**\
Receive the following from checking a GoDaddy valid wildcard certificate:

check_ssl_cert -s -H portal.hayley.co.uk -p 443 --sni portal.hayley.co.uk -w 28 -c 7 -v
expect available (/bin/expect)
timeout available (/bin/timeout)
found GNU date with timestamp support: enabling date computations
downloading certificate to /tmp
parsing the x509 certificate file
OCSP Error: Error querying OCSP responder
139849636566928:error:27076072:OCSP routines:PARSE_HTTP_LINE1:server response error:ocsp_ht.c:314:Code=404,Reason=Not Found
SSL_CERT CRITICAL *.hayley.co.uk: OCSP error (-v for details)|days_chain_elem1=695;28;7;; days_chain_elem2=3972;28;7;; days_chain_elem3=3999;28;7;; days_chain_elem4=5126;28;7;;

**To Reproduce**\
Just run the above

**Expected behavior**\
I admit I don't know a lot about this stuff, but I was expecting this check to return "OK" as this is an official, paid-for, valid certificate.

**System (please complete the following information):**\
 - OS: CentOS 7
 - check_ssl_cert Version: 1.118.0

**Additional context/output**\
I can run it with "--ignore-ocsp" to suppress the error, but I guess that defeats the point of the check :)

**Comment by matteocorti** [comment]
It not a but, there is an OCSP error: check https://www.ssllabs.com/ssltest/analyze.html?d=portal.hayley.co.uk&latest
