### ISSUE TITLE
Issuer CA name is empty when using --not-issued-by

### ISSUE THREAD

**Issue by skanx** [matteocorti/check_ssl_cert#216]
**Describe the bug**\
Issuer CA name is empty when using --not-issued-by and the certificate issuer does not match the supplied string.
Looking at the code, it looks like the issue is that CA_ISSUER_MATCHED variable is left empty when NOT_ISSUED_BY is set and CA_ISSUER_MATCHED is empty.

**To Reproduce**\
`check_ssl_cert -H github.com --not-issued-by 'arandomCA'`
>SSL_CERT OK - x509 certificate 'github.com' from '' valid until May 10 12:00:00 2022 GMT (expires in 654 days)|days_chain_elem1=654;20;15;; days_chain_elem2=3011;20;15;;

**Expected behavior**\
Issuer name should not be empty, but should be 'DigiCert SHA2 High Assurance Server CA' instead.
Expected output:
>SSL_CERT OK - x509 certificate 'github.com' from 'DigiCert SHA2 High Assurance Server CA' valid until May 10 12:00:00 2022 GMT (expires in 654 days)|days_chain_elem1=654;20;15;; days_chain_elem2=3011;20;15;;

**System (please complete the following information):**\
 - OS: Centos
 - OS Version: CentOS Linux release 7.8.2003 (Core)
 - check_ssl_cert Version: 1.120.0

**Additional context/output**\
Quick and dirty fix:
```
--- check_ssl_cert.2020-07-24-nm	2020-07-15 09:02:02.972627251 +0200
+++ check_ssl_cert	2020-07-24 16:45:09.954809379 +0200
@@ -2509,6 +2509,7 @@
             prepend_critical_message "invalid CA ('$(echo "${NOT_ISSUED_BY}" | sed "s/|/ PIPE /g")' matches '$(echo "${ISSUERS}" | sed -E -e "s/^(O|CN) ?= ?//" | tr '\n' '|' | sed "s/|\$//g" | sed "s/|/\\' or \\'/g")')"
         else
             ok="true"
+            CA_ISSUER_MATCHED="$(echo "${ISSUERS}" | grep -E "^CN ?= ?" | sed -E -e "s/^CN ?= ?//" | head -n1)"
         fi
 
     else
```

**Comment by matteocorti** [comment]
Thanks for the report and the patch. Fixed in 1.121.0
