### ISSUE TITLE
CN check is case-sensitive

### ISSUE THREAD

**Issue by mes85** [matteocorti/check_ssl_cert#22]
Browsers are not case-sensitive when verifying the CN of a certificate, but check_ssl_cert is:

root@xxx:~# ./check_ssl_cert-1.30.0/check_ssl_cert -H xxx.xxx.gad.local --host-cn
SSL_CERT CRITICAL xxx.xxx.GAD.local: invalid CN ('xxx.xxx.GAD.local' does not match 'xxx.xxx.gad.local')|days=501;;;;

root@xxx:~# ./check_ssl_cert-1.31.0/check_ssl_cert -H xxx.xxx.gad.local --host-cn
SSL_CERT CRITICAL xxx.xxx.GAD.local: invalid CN ('xxx.xxx.GAD.local' does not match 'xxx.xxx.gad.local')|days=501;;;;

I think it should be default to ignore the case while checking the CN.

**Comment by matteocorti** [comment]
It is indeed a bug as the domain name is case insensitive.

**Comment by matteocorti** [comment]
Do you have an host that I could use for testing?

**Comment by mes85** [comment]
This is basically the other way aroud, but reproduces the issue as well:

$ ./check_ssl_cert --ignore-ocsp -H www.google.com --host-cn
SSL_CERT OK - X.509 certificate for 'www.google.com' from 'Google Internet Authority G2' valid until Oct  5 13:16:00 2016 GMT (expires in 70 days)|days=70;;;;

$ ./check_ssl_cert --ignore-ocsp -H www.gooGle.com --host-cn
SSL_CERT CRITICAL www.google.com: invalid CN ('www.google.com' does not match 'www.gooGle.com')|days=70;;;;

A fix should take into account, that both hostnames (the supplied one and the one from the retrieved certificate) can contain mixed-case letters.

A fix should also be tested with subjAltNames.
