### ISSUE TITLE
--check-ssl-labs failed via proxy

### ISSUE THREAD

**Issue by phamlankt** [matteocorti/check_ssl_cert#223]
**Describe the bug**\
I was able to validate the SSL Certificate with this script through our proxy. But when i want to check the ssllab ranking, curl returned error 7. Looks like curl does not take the input proxy but goes directly then failed.

**To Reproduce**\
 ./check_ssl_cert  --proxy my_proxy:3128 -v  -H example.com  -t 120  -L C --check-ssl-labs-warn B
expect available (/usr/bin/expect)
timeout available (/usr/bin/timeout)
found GNU date with timestamp support: enabling date computations
downloading certificate to /tmp
parsing the x509 certificate file
Checking SSL Labs assessment
SSL_CERT UNKNOWN example.com: Error checking SSL Labs: curl returned 7, see 'man curl' for details

**Expected behavior**\
curl should use the provided proxy

**System (please complete the following information):**\
 - OS: Centos
 - OS Version: 8
 - check_ssl_cert Version: 1.118.0

**Additional context/output**\
Add any other context or output (e.g., from `check_ssl_cert -d -v`) about the problem here.

**Comment by matteocorti** [comment]
Please update to the latest version and provide the debugging output.

**Comment by phamlankt** [comment]
Hello,
I updated to the latest version and here is the debugging output:

$ ./check_ssl_cert -V
check_ssl_cert version 1.122.0

$ ./check_ssl_cert  --proxy my_proxy:3128   -H my_website  -t 120  -L C --check-ssl-labs-warn B -d
[DBG] Command line arguments: --proxy my_proxy:3128 -H my_website -t 120 -L C --check-ssl-labs-warn B -d
[DBG] -c specified: 15
[DBG] ROOT_CA =
[DBG] file version: file-5.33
[DBG] magic file from /etc/magic:/usr/share/misc/magic
[DBG] cURL binary needed. SSL Labs = C, OCSP = 1
[DBG] cURL binary not specified
[DBG] cURL available: /usr/bin/curl
[DBG] nmap binary not needed. No disallowed protocols
expect not available
timeout available (/usr/bin/timeout)
[DBG] perl available: /usr/bin/perl
[DBG] date available: /usr/bin/date
found GNU date with timestamp support: enabling date computations
[DBG] check_ssl_cert version: 1.122.0
[DBG] OpenSSL binary: /usr/bin/openssl
[DBG] OpenSSL version: OpenSSL 1.1.1c FIPS  28 May 2019
[DBG] OpenSSL configuration directory: /etc/pki/tls
[DBG] 142 root certificates installed by default
[DBG]  System info: Linux my_pc.tmsp.local 4.18.0-147.5.1.el8_1.x86_64 #1 SMP Wed Feb 5 02:00:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[DBG] Date computation: GNU
[DBG] '/usr/bin/openssl s_client' supports '-servername': using -servername my_website
[DBG] Adding -proxy my_proxy:3128 to the s_client options
[DBG] '/usr/bin/openssl s_client' supports '-name': using my_pc.tmsp.local
[DBG] '/usr/bin/openssl s_client' supports '-xmpphost': using -xmpphost my_website
[DBG] temporary file /tmp/check_ssl_certAZ0MIb created
[DBG] temporary file /tmp/check_ssl_cert6pehfH created
[DBG] temporary file /tmp/check_ssl_certM3vO6m created
[DBG] temporary file /tmp/check_ssl_certml6S2B created
downloading certificate to /tmp
[DBG] my_website is not an IP address
[DBG] executing with timeout (120s): printf 'HEAD / HTTP/1.1\nHost: my_website\nUser-Agent: check_ssl_cert/1.122.0\nConnection: close\n\n' | /usr/bin/openssl s_client    -crlf -ign_eof  -connect my_website:443 -servername my_website -proxy my_proxy:3128 -showcerts -verify 6       2> /tmp/check_ssl_cert6pehfH 1> /tmp/check_ssl_certAZ0MIb
[DBG] /usr/bin/timeout 120 /bin/sh -c "printf 'HEAD / HTTP/1.1\nHost: my_website\nUser-Agent: check_ssl_cert/1.122.0\nConnection: close\n\n' | /usr/bin/openssl s_client    -crlf -ign_eof  -connect my_website:443 -servername my_website -proxy my_proxy:3128 -showcerts -verify 6       2> /tmp/check_ssl_cert6pehfH 1> /tmp/check_ssl_certAZ0MIb"
[DBG] storing a copy of the retrieved certificate in my_website.crt
[DBG] Return value of the command = 0
[DBG] storing a copy of the retrieved certificate in /tmp/my_website-443.crt
[DBG] storing a copy of the OpenSSL errors in /tmp/my_website-443.error
parsing the x509 certificate file
[DBG] Skipping 0 element of the chain
[DBG] ISSUERS =
[DBG] issuer=C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Organization Validation Secure Server CA\nissuer=C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Certification Authority
[DBG] ISSUERS =
[DBG] O = COMODO CA Limited
[DBG] CN = COMODO RSA Organization Validation Secure Server CA
[DBG] O = COMODO CA Limited
[DBG] CN = COMODO RSA Certification Authority
[DBG] subject=C = my_subject
[DBG] CN         = *.my_CN
[DBG] CA         = O = COMODO CA Limited
[DBG] CA         = CN = COMODO RSA Organization Validation Secure Server CA
[DBG] CA         = O = COMODO CA Limited
[DBG] CA         = CN = COMODO RSA Certification Authority
[DBG] SERIAL     = my_Serial
[DBG] FINGERPRINT= my_fingerprint
[DBG] OCSP_URI   = http://ocsp.comodoca.com
[DBG] ISSUER_URI = http://crt.comodoca.com/COMODORSAOrganizationValidationSecureServerCA.crt
[DBG]         Signature Algorithm: sha256WithRSAEncryption
[DBG] subjectAlternativeName = *.my_subject
[DBG] Checking expiration date
[DBG] Nb certificates in CA chain: 2
[DBG] Skipping 0 element of the chain
[DBG] Checking expiration date of element 1
[DBG] Validity date on cert element 1 is Jan 18 23:59:59 2021 GMT
[DBG] Date computations: GNU
[DBG] Computing number of hours until 'Jan 18 23:59:59 2021 GMT'
[DBG] Hours until Jan 18 23:59:59 2021 GMT: 3042
[DBG] executing: /usr/bin/openssl x509 -noout -checkend 1296000 on cert element 1
[DBG] executing: /usr/bin/openssl x509 -noout -checkend 1728000 on cert element 1
[DBG] Checking expiration date of element 2
[DBG] Validity date on cert element 2 is Feb 11 23:59:59 2029 GMT
[DBG] Date computations: GNU
[DBG] Computing number of hours until 'Feb 11 23:59:59 2029 GMT'
[DBG] Hours until Feb 11 23:59:59 2029 GMT: 73746
[DBG] executing: /usr/bin/openssl x509 -noout -checkend 1296000 on cert element 2
[DBG] executing: /usr/bin/openssl x509 -noout -checkend 1728000 on cert element 2
Checking SSL Labs assessment
[DBG] executing /usr/bin/curl --silent "https://api.ssllabs.com/api/v2/analyze?host=my_website"
[DBG] curl returned 7: /usr/bin/curl --silent "https://api.ssllabs.com/api/v2/analyze?host=my_website"
[DBG] cleaning up temporary files
[DBG]
[DBG] /tmp/check_ssl_certAZ0MIb
[DBG] /tmp/check_ssl_cert6pehfH
[DBG] /tmp/check_ssl_certM3vO6m
[DBG] /tmp/check_ssl_certml6S2B
SSL_CERT UNKNOWN my_website: Error checking SSL Labs: curl returned 7, see 'man curl' for details
