### ISSUE TITLE
OCSP: Verify error:unable to get local issuer certificate

### ISSUE THREAD

**Issue by rainerduffner** [matteocorti/check_ssl_cert#224]
**Describe the bug**\
I can't seem to verify the ocsp response

**To Reproduce**\
sh check_ssl_cert -d --openssl /data/icinga/openssl/bin/openssl -H 217.71.91.232 --ocsp -r /home/local/ca-root-nss.crt  -w 30 -c 10  --noauth --altnames -n daten.auto-i-dat.ch --sni daten.auto-i-dat.ch

[DBG] OCSP: response = Response Verify Failure
[DBG] OCSP: response = 139775247193856:error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:crypto/ocsp/ocsp_vfy.c:93:Verify error:unable to get local issuer certificate
[DBG] OCSP: response = 139775247193856:error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:crypto/ocsp/ocsp_vfy.c:93:Verify error:unable to get local issuer certificate
[DBG] OCSP: response = /tmp/check_ssl_certtW9AhT: good
[DBG] OCSP: response = 	This Update: Sep 25 09:08:38 2020 GMT
[DBG] OCSP: response = 	Next Update: Sep 27 09:08:38 2020 GMT

**Expected behavior**\
On another system, this seems to work.
[DBG] executing /usr/bin/openssl ocsp -timeout "120" -no_nonce -issuer /tmp/check_ssl_certXXXXXX.KWhD7sp7 -cert /tmp/check_ssl_certXXXXXX.3W57nuxQ  -url http://ocsp.quovadisglobal.com  -header HOST=ocsp.quovadisglobal.com
[DBG] OCSP: response = Response verify OK
[DBG] OCSP: response = /tmp/check_ssl_certXXXXXX.3W57nuxQ: WARNING: Status times invalid.
[DBG] OCSP: response = 34371092480:error:2707307E:OCSP routines:OCSP_check_validity:status not yet valid:/usr/src/crypto/openssl/crypto/ocsp/ocsp_cl.c:351:
[DBG] OCSP: response = good
[DBG] OCSP: response =  This Update: Sep 24 10:13:27 2020 GMT
[DBG] OCSP: response =  Next Update: Sep 26 10:13:27 2020 GMT

**System (please complete the following information):**\
 - OS: Ubuntu
 - OS Version: 12
 - check_ssl_cert Version: 1.122.0

**Additional context/output**\
I compiled a more recent version of openssl (1.1.1g) and use that.
I copied over the root-certificates from the host where the ocsp check seems to succeed (which runs FreeBSD 12, for the record).

The openssl command works, if I manually supply the Root and Intermediate certificate via -CAfile as described here:
https://stackoverflow.com/questions/41701860/why-do-i-get-verify-errorunable-to-get-local-issuer-certificate-when-i-run-open

Yes, I know it's Ubuntu 12. But we can't "just replace" it or else I'd have done it in a weekend...

ssllabs does not show a problem with the chain.

What else can I do?

**Comment by matteocorti** [comment]
Does not seem to be a bug and cannot be reproduced.

```
$ openssl version
OpenSSL 1.1.1g  21 Apr 2020
$ ./check_ssl_cert  -H 217.71.91.232 --ocsp -w 30 -c 10 --noauth --altnames -n daten.auto-i-dat.ch --sni daten.auto-i-dat.ch
SSL_CERT OK - x509 certificate 'www.autoi.ch' (daten.auto-i-dat.ch) from 'QuoVadis Europe EV SSL CA G1' valid until Sep 10 15:10:00 2021 GMT (expires in 350 days)|days_chain_elem1=350;30;10;; days_chain_elem2=3583;30;10;;
```

The debugging output is also incomplete. On the system where is not working which is the `ocsp` command executed?

See
```
[DBG] executing /usr/bin/openssl ocsp -timeout "120" -no_nonce -issuer /tmp/check_ssl_certXXXXXX.KWhD7sp7 -cert /tmp/check_ssl_certXXXXXX.3W57nuxQ -url http://ocsp.quovadisglobal.com -header HOST=ocsp.quovadisglobal.com
```

On the working system.

**Comment by rainerduffner** [comment]
Sorry, here is the full ocsp section:

```
[DBG] OCSP: issuer certificate type:  data
[DBG] OCSP: converting issuer certificate from DER to PEM
[DBG] OCSP: storing a copy of the retrieved issuer certificate to /tmp/quovadiseuropeevsslcag1.crt
[DBG] OCSP: host = ocsp.quovadisglobal.com
[DBG] openssl ocsp supports the -header option
[DBG] /data/icinga/openssl/bin/openssl ocsp -header requires 'key=value'
[DBG] executing /data/icinga/openssl/bin/openssl ocsp -timeout "120" -no_nonce -issuer /tmp/check_ssl_certiWAeEt -cert /tmp/check_ssl_certAIwgUH  -url http://ocsp.quovadisglobal.com  -header HOST=ocsp.quovadisglobal.com
[DBG] OCSP: response = Response Verify Failure
[DBG] OCSP: response = 139845582391040:error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:crypto/ocsp/ocsp_vfy.c:93:Verify error:unable to get local issuer certificate
[DBG] OCSP: response = 139845582391040:error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:crypto/ocsp/ocsp_vfy.c:93:Verify error:unable to get local issuer certificate
[DBG] OCSP: response = /tmp/check_ssl_certAIwgUH: good
[DBG] OCSP: response = 	This Update: Sep 25 10:26:46 2020 GMT
[DBG] OCSP: response = 	Next Update: Sep 27 10:26:46 2020 GMT
[DBG] output parameters: CA_ISSUER_MATCHED     = QuoVadis Europe EV SSL CA G1
[DBG] output parameters: CHECKEDNAMES          = (daten.auto-i-dat.ch)
[DBG] output parameters: CN                    = www.autoi.ch
[DBG] output parameters: DATE                  = Sep 10 15:10:00 2021 GMT
[DBG] output parameters: DAYS_VALID            =  (expires in 350 days)
[DBG] output parameters: DYSPLAY_CN            = 'www.autoi.ch'
[DBG] output parameters: OPENSSL_COMMAND       = x509
[DBG] output parameters: SELFSIGNEDCERT        =
[DBG] output parameters: SHORTNAME             = SSL_CERT
[DBG] output parameters: OCSP_EXPIRES_IN_HOURS =
[DBG] output parameters: SSL_LABS_HOST_GRADE   =
SSL_CERT OK - x509 certificate 'www.autoi.ch' (daten.auto-i-dat.ch) from 'QuoVadis Europe EV SSL CA G1' valid until Sep 10 15:10:00 2021 GMT (expires in 350 days)|days_chain_elem1=350;30;10;; days_chain_elem2=3583;30;10;;
[DBG] cleaning up temporary files

``` 

I first thought it was the old root-certificates, then I thought it was the old openssl version....

**Comment by matteocorti** [comment]
Ok but now it gives an OK an not an error anymore

**Comment by matteocorti** [comment]
Seems a problem with QuoVadis (OCSP servers from QuoVadis had several problems in the past, we also use QuoVadis...)
