### ISSUE TITLE
Is expect still required for timeouts?

### ISSUE THREAD

**Issue by simmonmt** [matteocorti/check_ssl_cert#232]
https://github.com/matteocorti/check_ssl_cert/blob/master/README.md says:

check_ssl_cert requires 'expect' to enable timeouts. If expect is not present on your system timeouts will be disabled.

Is that still correct? https://github.com/matteocorti/check_ssl_cert/blob/master/check_ssl_cert looks like it knows how to use the timeout command, and in fact prefers to use timeout over expect.

**Comment by matteocorti** [comment]
Thanks. I fixed the old entry
