### ISSUE TITLE
Add no_cert_state flag to allow setting an unknown state when no cert has returned

### ISSUE THREAD

**Issue by yaron-idan** [matteocorti/check_ssl_cert#237]
**Is your feature request related to a problem? Please describe.**
We're sometimes getting false alerts when our checks fail intermittently and can't find the certificate they are trying to check. In our monitoring setup we check that the endpoint is behaving as expected in a separate check, and use check_ssl_cert purely to monitor for certificate expiration and SSL Labs grade. 

**Describe the solution you'd like**
A flag that will allow setting an unknown state if the cert is not returned (or any other custom state for that matter)

**Describe alternatives you've considered**
An ignore flag is a simpler option, but will support less use cases

If the feature makes sense, I'll be happy to write the PR for it. Thanks.

**Comment by matteocorti** [comment]
Hi
We can integrate the feature. I don't think it will have a broad use, but why not ...
Matteo

**Comment by matteocorti** [comment]
Implemented in a2d0eca
