### ISSUE TITLE
Support for BusyBox (was Wrong DATETYPE on Alpine Linux)

### ISSUE THREAD

**Issue by mjiderhamn** [matteocorti/check_ssl_cert#243]
**Describe the bug**\
On Alpine Linux, `date` is `BusyBox v1.31.1 () multi-call binary`, which supports `-d` but does however not support the `--version` parameter. This makes `check_ssl_cert` decide `DATETYPE` is `BSD`, resulting in error.

**To Reproduce**\
Use for example Docker image `alpine:3.12`.

**Expected behavior**\
`DATETYPE` should be `GNU` so that date computations can be made.

Alternatively, instead of `--force-perl-date` there could be a parameter that allows setting `DATETYPE`.

**System (please complete the following information):**\
 - OS: Alpine Linux
 - OS Version: 3.12.3
 - check_ssl_cert Version: 1.132.0

**Additional context/output**\
```
[DBG] date available: /bin/date
found BSD date with timestamp support: enabling date computations
[DBG] check_ssl_cert version: 1.132.0
...
[DBG] Date computation: BSD
... 
[DBG] Checking expiration date of element 1
[DBG] Validity date on cert element 1 is Sep 29 07:32:36 2021 GMT
[DBG] Date computations: BSD
[DBG] Computing number of hours until 'Sep 29 07:32:36 2021 GMT'
/bin/date: unrecognized option: j
BusyBox v1.31.1 () multi-call binary.

Usage: date [OPTIONS] [+FMT] [TIME]

Display time (using +FMT), or set time

	[-s,--set] TIME	Set time to TIME
	-u,--utc	Work in UTC (don't convert to local time)
	-R,--rfc-2822	Output RFC-2822 compliant date string
	-I[SPEC]	Output ISO-8601 compliant date string
			SPEC='date' (default) for date only,
			'hours', 'minutes', or 'seconds' for date and
			time to the indicated precision
	-r,--reference FILE	Display last modification time of FILE
	-d,--date TIME	Display TIME, not 'now'
	-D FMT		Use FMT (strptime format) for -d TIME conversion
```

**Comment by matteocorti** [comment]
I would rather try to detect the BusyBox date. I'll take a look.

**Comment by matteocorti** [comment]
Not so easy. BusyBox is not really able to parse the date provided by OpenSSL

```
BusyBox v1.32.0 (2020-07-27 14:11:30 UTC) multi-call binary.

Usage: date [OPTIONS] [+FMT] [TIME]

Display time (using +FMT), or set time

	[-s,--set] TIME	Set time to TIME
	-u,--utc	Work in UTC (don't convert to local time)
	-R,--rfc-2822	Output RFC-2822 compliant date string
	-I[SPEC]	Output ISO-8601 compliant date string
			SPEC='date' (default) for date only,
			'hours', 'minutes', or 'seconds' for date and
			time to the indicated precision
	-r,--reference FILE	Display last modification time of FILE
	-d,--date TIME	Display TIME, not 'now'
	-D FMT		Use FMT (strptime format) for -d TIME conversion

Recognized TIME formats:
	hh:mm[:ss]
	[YYYY.]MM.DD-hh:mm[:ss]
	YYYY-MM-DD hh:mm[:ss]
	[[[[[YY]YY]MM]DD]hh]mm[.ss]
	'date TIME' form accepts MMDDhhmm[[YY]YY][.ss] instead
```

OpenSSL delivers something like `Mar 16 07:28:25 2021 GMT`

**Comment by matteocorti** [comment]
Timezone is not supported

**Comment by mjiderhamn** [comment]
With 1.133.0 I'm getting

```
[DBG] Date computations: BUSYBOX
[DBG] Computing number of hours until 'Sep 29 19:21:40 2021 GMT'
sed: unrecognized option: s
BusyBox v1.31.1 () multi-call binary.

Usage: sed [-i[SFX]] [-nrE] [-f FILE]... [-e CMD]... [FILE]...
or: sed [-i[SFX]] [-nrE] CMD [FILE]...

        -e CMD  Add CMD to sed commands to be executed
        -f FILE Add FILE contents to sed commands to be executed
        -i[SFX] Edit files in-place (otherwise sends to stdout)
                Optionally back files up, appending SFX
        -n      Suppress automatic printing of pattern space
        -r,-E   Use extended regex syntax

If no -e or -f, the first non-option argument is the sed command string.
Remaining arguments are input files (stdin if none).
```

Give a try with
```
docker run --rm -it alpine:3.12 /bin/sh -c "apk add openssl file curl && curl -sL https://github.com/matteocorti/check_ssl_cert/releases/download/v1.133.0/check_ssl_cert-1.133.0.tar.gz | tar xvz -C /tmp && /tmp/check_ssl_cert-1.133.0/check_ssl_cert -H www.google.com -w 60 -c 15"
```

**Comment by matteocorti** [comment]
Mmmm it seems that `sed` on BusyBox behaves differently. I'll try to check all the tools. At the moment I installed BusyBox on Fedora but it seems that it will be easier to install Alpine Linux in a VM ... (this will take some time).

If you have a machine where I could temporarily test, contact me per email.

**Comment by matteocorti** [comment]
There are no problems with BusyBox `sed` I just invented a `-s` option which does not exist. Sorry ...

**Comment by matteocorti** [comment]
Now I get the following

```
grep: unrecognized option: after-context=1
```

**Comment by mjiderhamn** [comment]
> seems that it will be easier to install Alpine Linux in a VM ... (this will take some time).
> 
> If you have a machine where I could temporarily test, contact me per email.

I recommend using Docker image `alpine` as per above.

**Comment by matteocorti** [comment]
I need an environment where I can edit and then commit. I am running Alpine in a VM without any problems. With the latest commit it works. I still have to adapt the Makefile.

**Comment by mjiderhamn** [comment]
For future reference: 2a17bf7102e8a7fdfe353330b7143982df2d04c9

**Comment by matteocorti** [comment]
The only tests that are now failing are IPv6 (which I don't have on my machine) and two tests requiring dig (which I didn't find in the community repo). Seems that everything works. Let me know if you encounter other issues.

**Comment by mjiderhamn** [comment]
Works perfectly for my use case. Thank you!!!
