### ISSUE TITLE
invalid number of days

### ISSUE THREAD

**Issue by jonbn74** [matteocorti/check_ssl_cert#244]
Im trying to use your script with latest version of naemon. When running the script in a terminal everything works as expected but when I execute the script via thruk I get an error saying SSL_CERT UNKNOWN 192.168.1.2: invalid number of days 10

The command is check_ssl_cert -H 192.168.1.2 -p 21 -P ftp -A -c 10 -w 30

**System (please complete the following information):**\
 - OS: RHEL8
 - OS Version: 8.3
 - check_ssl_cert Version: 1.135.0
 - namon version: 1.2.2-7.5

**Comment by matteocorti** [comment]
Dear @jonbn74. Thanks for the report but it's impossible for me to debug:

 - no idea what `namon` could be
 - the server has a private IP address: I cannot test for myself
 - you give no debugging  output

**Comment by matteocorti** [comment]
Looking at the error message it could be that there is a space or a strange character in the specification of the number of critical days (10). I just committed a new version where quotes surround the given parameter.

**Comment by jonbn74** [comment]
Sorry, this was a typo, should be naemon, https://www.naemon.org

Running again with the new version the output is SL_CERT UNKNOWN 192.168.1.2: invalid number of days '10' via thruk

Will try to add debug information

**Comment by matteocorti** [comment]
Mmm, pretty strange:

I check with ```grep -q '^[0-9][0-9]*$' ``` and the check works with ```10```

```
$ echo 10 |  grep '^[0-9][0-9]*$' 
10
```

Is the 'via thruk' part of the plugin output?

**Comment by jonbn74** [comment]
'via thruk' is not part of the output. Your plugin works perfectly with nagios, could this be naemons fault ? It works as expected when I run the command line in the shell of the server.

**Comment by matteocorti** [comment]
It's very strange.The message comes from the validation of the ```-c``` command line argument.
Is naemons configured via files similarly to nagios? Can you post the plugin configuration?

**Comment by jonbn74** [comment]
Naemon is a nagios fork and should be compatible with nagios. Here is the plugin configuration ,

define command {
        command_name    check_ftp_cert
        command_line    $USER1$/chef-managed/check_ssl_cert -H $HOSTADDRESS$ -p 21 -P ftp -A -w 30 -c 10
}

**Comment by matteocorti** [comment]
Are you sure that there are no strange characters before or after the 10 (tabs, other blanks) that Naemon could pass to the command?

**Comment by jonbn74** [comment]
no, no characters after the 10

**Comment by matteocorti** [comment]
Then I really have no idea what is passed to the plugin ....

**Comment by matteocorti** [comment]
What if you append another option at the end? Or if you try to change the order of the parameters (e.g., -A at the end?)

**Comment by jonbn74** [comment]
We have solved this mistery. I turns out that /bin was not in PATH for the naemon user which seems to have this weird effect on your plugin. After adding /bin to path everything works as it should.

**Comment by matteocorti** [comment]
Ok this was a strange one :-)

The check

```
        if ! echo "${CRITICAL_DAYS}" | grep -q '^[0-9][0-9]*$' ; then
            unknown "invalid number of days '${CRITICAL_DAYS}'"
        fi
```

was failing not because `grep` was returning 0 but because `grep` could not be executed.

I could add a check for `grep`

**Comment by matteocorti** [comment]
Thanks for the help in debugging. I added a check in the plugin (so that a better error message is printed out)

```
SSL_CERT UNKNOWN www.google.com: cannot execute grep: please check the PATH variable (/Users/corti/perl5/perlbrew/bin:/Users/corti/perl5/perlbrew/perls/perl-5.32.0/bin:/opt/local/bin:/opt/local/sbin:/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/2.6.0/bin/:/opt/local/bin:/opt/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/Users/corti/bin)
```
