### ISSUE TITLE
Selective proxy settings

### ISSUE THREAD

**Issue by marcoschum** [matteocorti/check_ssl_cert#252]
**Issue**
With the new `--no-proxy` settings, proxy is unavailable for all operations.

Therefor the 'fetch issuer certificate' with curl no longer works (runs into timeout):
_/usr/bin/curl --silent --location "http://trust.quovadisglobal.com/qvsslg2.crt" > /tmp/xyz_
(with the option of the custom curl bin, there is a workaround for that issue)

And the ocsp check no longer works (also runs into a timeout):
_/usr/bin/openssl ocsp -no_nonce -issuer /tmp/xyz_
(unfortunately, there is no easy workaround for this issue)

**Possible solution**
More selective proxy options:
`--no-proxy-s_client` # disables proxy for the openssl s_client command
`--no-proxy-ocsp`      # disables proxy for the openssl ocsp command
`--no-proxy-curl`       # disables proxy for all curl commands

In our scenario, we would use the `--no-proxy-s_client` option to fetch the certificate without proxy, but then keep the proxy settings for the issuer cert check and ocsp check.

**Comment by matteocorti** [comment]
This would require to set and unset the different HTTP_PROXY variables at the right moment.
If someone wants to take a look feel free to submit a pull request.
