### ISSUE TITLE
Feature: ability to use curl --resolve

### ISSUE THREAD

**Issue by lukastribus** [matteocorti/check_ssl_cert#271]
**Is your feature request related to a problem? Please describe.**
For a number of reasons the IP address listed in DNS record may not be reachable for the box where this script runs. Examples are:

- Missing NAT hairpinning support in NAT Routers
- Firewall restrictions/walled gardens
- hosts with multiple IP addresses/interface, but SSL services is not listening on all of them.
- other strange Intranet/Enterprise scenarios

**Describe the solution you'd like**
At least for HTTP, allow us to use `curl --resolve`, forcing a specific `host:port` to a specific `ip:port` combination, ignoring DNS.

**Describe alternatives you've considered**

- use both `--sni name` and `--cn name` and run against the reachable IP address, ignoring DNS (untested); probably not compatible with certificates that only have SAN's and no CN's
- make a generic option which allows to add arbitrary curl options, as opposed to address this specific case

**Additional context**
Although we would prefer having clean and straightforward setups, sometimes we have to handle more complicated setups, even if we don't like the design. They still (or especially) need monitoring.

**Comment by lukastribus** [comment]
Got it, not sure why I thought curl is used for pretty much everything.


Actually now that I'm thinking about it, maybe that's what I can already accomplish with:

    check_ssl_cert -H 192.168.0.5 --sni example.org --cn example.org --altnames


```
~$ ./check_ssl_cert -H facebook.com --sni google.com --cn google.com --altnames
SSL_CERT CRITICAL *.facebook.com: invalid CN ('*.facebook.com' does not match 'google.com')|days_chain_elem1=41;20;15;; days_chain_elem2=2762;20;15;;
~$
```

I will test this some more and then probably close this issue.


// doesn't really matter at this point:

`openssl s_client` can work like that by specifying the correct SNI (of course) and `verify_hostname` to specify with name to validate against, for example:

I need to connect to to port 443 of facebook.com, but sending SNI google.com and expecting the same (this makes no sense for the use-cases involved though):

    openssl s_client -connect facebook.com:443 -servername google.com -verify_hostname google.com


Or, for the actual use-case: my company website `example.org` is hosted on a public IP address, which I can't reach because it's hosted on my own network and my NAT router doesn't handle it (NAT hairpinning), so I need to divert my checks to the private IP address of the server, as opposed to the public IP from DNS:

    openssl s_client -connect 192.168.0.5:443 -servername example.org -verify_hostname example.org

(my real use-case is even more complicated, it involves a corporate network, where the (public) certificate is not Internet facing and not on the IP address published in DNS).

Another workaround could be to just put this into /etc/hosts, but that's a manual configuration that doesn't scale very well, when we are talking about a nagios monitoring box.

**Comment by matteocorti** [comment]
I see your point. Let me know if it works. Are you able to access public IPs on the net for OCSP and revocation checks?
I could add a simple ```--resolve``` option to always use the IP address and add the ```--sni``` option.

I would then need your help to test for me (I could try to get a machine on a network with a similar setup)

**Comment by matteocorti** [comment]
I just prepared a simple implementation without any validation.

**Comment by lukastribus** [comment]
Yes, that looks good. I would expect validation by default though, just like without the --resolve directive (and indeed that is my use-case, the certificates are proper public certificates):

```
~$ ./check_ssl_cert.1 --resolve facebook.com -H google.com
SSL_CERT OK - x509 certificate '*.facebook.com' from 'DigiCert SHA2 High Assurance Server CA' valid until May 10 23:59:59 2021 GMT (expires in 41 days)|days_chain_elem1=41;20;15;; days_chain_elem2=2762;20;15;;
~$ echo $?
0
~$
```

**Comment by matteocorti** [comment]
I have to check why the SNI is ignored

**Comment by lukastribus** [comment]
In this case SNI is the same as the HOST (-H), but we should always validate against the HOST, not the SNI, right?

    check_ssl_cert -H google.com --sni example.org

Should validate the certificate against `google.com`, our HOST, not the sni value we send to the backend server.

**Comment by matteocorti** [comment]
Yes you are right.... The solution was too easy. I'll check tomorrow if I find the time (it's pretty late now).

**Comment by matteocorti** [comment]
The last check-in should implement the new feature. Can you please test and tell me if it solves your problem?

**Comment by lukastribus** [comment]
The redirect and contacts the proper server, but just like yesterday at fa80b21d3d it doesn't look like its properly validating, no:

```
~$ ./check_ssl_cert --resolve google.com -H facebook.com
SSL_CERT OK - x509 certificate '*.google.com' from 'GTS CA 1O1' valid until Jun  3 14:40:35 2021 GMT (expires in 63 days)|days_chain_elem1=63;20;15;; days_chain_elem2=258;20;15;;
~$ echo $?
0
~$
~$ ./check_ssl_cert --resolve github.com -H microsoft.com
SSL_CERT OK - x509 certificate 'github.com' from 'DigiCert High Assurance TLS Hybrid ECC SHA256 2020 CA1' valid until Mar 30 23:59:59 2022 GMT (expires in 364 days)|days_chain_elem1=364;20;15;; days_chain_elem2=3547;20;15;;
~$ echo $?
0
~$

```

**Comment by matteocorti** [comment]
check_ssl_cert does not check the CN per default. You need to specify -N

**Comment by matteocorti** [comment]
But maybe I should make the check per default and add an option to ignore a mismatch.

**Comment by lukastribus** [comment]
Oh, I did not realize that.

`--cn <name>` implies that too, so I saw that behavior while using the workaround above and assumed this would be the default.

Whether you want to change that now ... depends on what you think your users expect. I assume this would break some configurations.

**Comment by matteocorti** [comment]
The CN is now always checked (can be ignored via option)

**Comment by lukastribus** [comment]
Thanks!

**Comment by matteocorti** [comment]
Thanks to you. The request makes sense and the change led to an important feature (the CN should match).

**Comment by matteocorti** [comment]
As soon as the tests are finished, I'll release a new version
