### ISSUE TITLE
Renegotiation test broken with STARTTLS

### ISSUE THREAD

**Issue by slavkoja** [matteocorti/check_ssl_cert#272]
**Describe the bug**\

When STARTTLS protocol is used (SMTP in my case), the renegotiation check runs without `--starttls` option

**To Reproduce**\
Run check 
```
/usr/lib/nagios/plugins/check_ssl_cert -H bonifac.skk -p 25 -P smtp -d
...
downloading certificate to /tmp
[DBG] bonifac.skk is not an IP address
[DBG] executing with timeout (120s): printf 'QUIT
[DBG] ' | /usr/bin/openssl s_client    -crlf -ign_eof -starttls smtp -connect bonifac.skk:25 -servername bonifac.skk   -verify 6       -name bonifac 2> /tmp/UTAlGM 1> /tmp/yzuXlH
[DBG] /usr/bin/timeout 120 /bin/sh -c "printf 'QUIT
[DBG] ' | /usr/bin/openssl s_client    -crlf -ign_eof -starttls smtp -connect bonifac.skk:25 -servername bonifac.skk   -verify 6       -name bonifac 2> /tmp/UTAlGM 1> /tmp/yzuXlH"
[DBG] storing a copy of the retrieved certificate in bonifac.skk.crt
[DBG] Return value of the command = 0
[DBG] storing a copy of the retrieved certificate in /tmp/bonifac.skk-25.crt
[DBG] storing a copy of the OpenSSL errors in /tmp/bonifac.skk-25.error
Checking TLS renegotiation
[DBG] executing with timeout (120s): printf 'R
[DBG] ' | openssl s_client -connect bonifac.skk:25 2>&1 | grep -F -q err
[DBG] /usr/bin/timeout 120 /bin/sh -c "printf 'R
[DBG] ' | openssl s_client -connect bonifac.skk:25 2>&1 | grep -F -q err"
...
```

**Expected behavior**\

Use`-starttls' option for appropriate protocols.

**System (please complete the following information):**\

 - check_ssl_cert Version: 1.145.0

**Additional context/output**\

IMO, the TLS renegotiation has nothing to do with TLS certificate check, thus it have not been run by default, only when requested.

**Comment by matteocorti** [comment]
Thanks, I'll take a look at the bug.
I would rather keep it on per default as the plugin is becoming more and more a TLS check (instead of just the certificate).
Why would you skip it?

**Comment by slavkoja** [comment]
To be honest, i noticed that it exists, because my MTA reports unexpected input, as the TLS connection is done on tcp/25 port, and only after debian testing's package upgrade. I didn't care about it before, thus i do not know if it was executed or not.

When i now checked renegotiation with `openssl` against my local `exim`, i got:
```
Secure Renegotiation IS NOT supported
```
I even do not know if it is good or not...

**Comment by matteocorti** [comment]
The OpenSSL message refers to the OpenSSL binary (which is new and does not support Renegatiation). But to check the server a connection is needed. See  https://www.mcafee.com/blogs/enterprise/tips-securing-ssl-renegotiation/

**Comment by slavkoja** [comment]
As i wrote early, i do not know. Here is renegotiation output:
```
echo R | openssl s_client -starttls smtp -connect bonifac.skk:25 -servername bonifac.skk -msg
... cut
RENEGOTIATING
139818507564352:error:1420410A:SSL routines:SSL_renegotiate:wrong ssl version:../ssl/ssl_lib.c:2135:
>>> ??? [length 0005]
    17 03 03 00 13
>>> TLS 1.3 [length 0001]
    15
>>> TLS 1.3, Alert [length 0002], warning close_notify
    01 00
```

**Comment by matteocorti** [comment]
Can you please test the new release?

**Comment by slavkoja** [comment]
Seems to work now

**Comment by matteocorti** [comment]
Thanks!
