### ISSUE TITLE
wildcard regex does not match underscores in subdomains

### ISSUE THREAD

**Issue by ctriegg-mak** [matteocorti/check_ssl_cert#275]
**Describe the bug**

If a subdomain specified via `-n` does contain an underscore and a wildcard certificate is installed the regular expression for checking if the names match will not match.

**To Reproduce**

Have a subdomain `foo_bar.acme.com` and deliver a wildcard certificate for `*.acme.com` when checking.

**Expected behavior**

The name should match with a wildcard certificate

**System (please complete the following information):**

 - check_ssl_cert Version: `1.140.0`

**Additional context/output**

I know that some RFCs advise against using underscores in the subdomain but there are many domains with underscores in the wild and some of our customers use them and will not stop using them soon. At the Moment we patched the script for ourselves but it would be better to have a solution with the same code as upstream. 

If it's acceptable to change the regular expressions or to introduce a switch to do so I will be happy to provide a PR.

**Comment by matteocorti** [comment]
Hi

thanks for the report. I think that it's acceptable to change the regex to handle the underscore. It's not a task of the plugin to complain if a domain or host name is not compliant. If the script is used, it means that the host exists. Therefore we should handle it.

A PR would be nice, as I don't have a use case to test. As you volunteered I assign the bug to you (I hope it's OK).

Matteo

**Comment by ctriegg-mak** [comment]
Hi

I'm happy to provide a contribution. I will submit it within the next week.

**Comment by matteocorti** [comment]
Thanks
