### ISSUE TITLE
Add option to disable performance output

### ISSUE THREAD

**Issue by Rohlik** [matteocorti/check_ssl_cert#276]
**Describe the solution you'd like**

Add parameter, for example `--no-perf` to disable performance data in plugin output.

**Additional context**

In some use cases are performance data undesirable so there should be some method how to disable them.

**Comment by Rohlik** [comment]
This was super fast. Thank you!

**Comment by matteocorti** [comment]
It was less thank 10 lines of code. It was more work to update the documentation as to implement the feature :-)
