### ISSUE TITLE
Unable to get issuer cert error when issuer cert URI contains parens

### ISSUE THREAD

**Issue by jffgrnfld** [matteocorti/check_ssl_cert#278]
**Describe the bug**

If the issuer cert URI contains parenthesis () characters - they are stripped from the argument passed to curl that attempts to download this cert, and thus it fails.

**To Reproduce**

Find a certificate chain that has an issuer cert with a URI that contains parenthesis.

**System:**

 - OS: CentOS 6
 - check_ssl_cert Version: 2.1.0

**Comment by matteocorti** [comment]
It would be nice to have a test case. Otherwise I have to implement and test blindly.

**Comment by jffgrnfld** [comment]
My case is with internal servers (Active Directory systems) - so sadly I cannot easily give you a test case that you can publicly access.

Here's the relevant output from the debug.  The URI of the issuer has a "(1)" at the end, but the parens get stripped so it just lists it as a "1" instead.

[DBG] /usr/bin/timeout 120 /bin/sh -c "printf 'R\n' | openssl s_client -connect tumnus.ad.calvin.edu:443 2>&1 | grep -F -q err"
[DBG]   end time = 1619721200
[DBG]   new timeout = 120
[DBG] Skipping 0 element of the chain
[DBG] ISSUERS =
[DBG] issuer= DC = edu, DC = calvin, DC = ad, CN = CalvinCollege-ad-CA
[DBG] ISSUERS =
[DBG] CN = CalvinCollege-ad-CA
[DBG] subject= CN = TUMNUS.ad.calvin.edu
[DBG] CN         = TUMNUS.ad.calvin.edu
[DBG] CA         = CN = CalvinCollege-ad-CA
[DBG] SERIAL     = 36000A34A6E4272F3270241DA30001000A34A6
[DBG] FINGERPRINT= CC:8E:E1:0E:22:1A:2A:7F:DF:AE:EA:A0:58:52:71:66:7C:98:CB:DC
[DBG] OCSP_URI   =
[DBG] ISSUER_URI = http://adage.ad.calvin.edu/CertEnroll/adage.ad.calvin.edu_CalvinCollege-ad-CA1.crt
[DBG]     Signature Algorithm: sha512WithRSAEncryption
[DBG] subjectAlternativeName = TUMNUS.ad.calvin.edu
[DBG] check CN: TUMNUS.ad.calvin.edu
[DBG] COMMON_NAME = tumnus.ad.calvin.edu
[DBG] ALTNAMES    = 1
[DBG]  CN check finished
[DBG] Checking expiration date
[DBG] Number of certificates in CA chain: 1
[DBG] Skipping 0 element of the chain
[DBG] ------------------------------------------------------------------------------
[DBG] Checking expiration date of element 1
[DBG] Validity date on cert element 1 is May 24 14:07:01 2022 GMT
[DBG] Date computations: GNU
[DBG] Computing number of hours until 'May 24 14:07:01 2022 GMT'
[DBG] Hours until May 24 14:07:01 2022 GMT: 9355
[DBG] executing: /usr/bin/openssl x509 -noout -checkend 0 on cert element 1
[DBG] executing: /usr/bin/openssl x509 -noout -checkend 2592000 on cert element 1
[DBG] executing: /usr/bin/openssl x509 -noout -checkend 5184000 on cert element 1
[DBG] ------------------------------------------------------------------------------
[DBG] Checking OCSP status of element 1
[DBG] temporary file /tmp/48GkAm created
[DBG] Storing the chain element in /tmp/48GkAm
[DBG] Checking revokation via OCSP
[DBG] Issuer hash: ddbc78f4
[DBG] Chain element issuer URIs: http://adage.ad.calvin.edu/CertEnroll/adage.ad.calvin.edu_CalvinCollege-ad-CA1.crt
[DBG] checking issuer URIs: http://adage.ad.calvin.edu/CertEnroll/adage.ad.calvin.edu_CalvinCollege-ad-CA1.crt
[DBG] OCSP: fetching issuer certificate http://adage.ad.calvin.edu/CertEnroll/adage.ad.calvin.edu_CalvinCollege-ad-CA1.crt to /tmp/zmL3V4
[DBG] executing with timeout (120s): /usr/bin/curl    --silent --location \"http://adage.ad.calvin.edu/CertEnroll/adage.ad.calvin.edu_CalvinCollege-ad-CA1.crt\" > /tmp/zmL3V4

**Comment by matteocorti** [comment]
Thanks. I'll take a look tomorrow

**Comment by matteocorti** [comment]
I can confirm the bug and I committed (2166860) a possible fix. Can you please test?

**Comment by jffgrnfld** [comment]
Confirmed.  That fixes it.  Thanks!

- Jeff
