### ISSUE TITLE
Starting with 2.0.0, "-H" option requires FQDN?

### ISSUE THREAD

**Issue by esabol** [matteocorti/check_ssl_cert#280]
Let's say my server's FQDN is `somehost.fqdn.com`.

Prior to version 2.0.0, I could just specify `-H somehost` and check_ssl_cert worked.

Starting with version 2.0.0 (and tested with the current 2.1.1 release), I have to specify `-H somehost.fqdn.com`. If I just specify, `-H somehost`, I get the following:
```
SSL_CERT CRITICAL somehost.fqdn.com: invalid CN ('somehost.fqdn.com' does not match 'somehost')|days_chain_elem1=xxx;7;3;; days_chain_elem2=yyy;7;3;; 
```
If I add `--debug`, I see lines like this with version 2.1.1:
```
[DBG] subject= CN = somehost.fqdn.com
[DBG] CN         = somehost.fqdn.com
[DBG] CA         = O = Let's Encrypt
[DBG] CA         = CN = R3
[DBG] CA         = CN = DST Root CA X3
[DBG] SERIAL     = [REDACTED]
[DBG] FINGERPRINT= [REDACTED]
[DBG] OCSP_URI   = http://r3.o.lencr.org
[DBG] ISSUER_URI = http://r3.i.lencr.org/
[DBG]     Signature Algorithm: sha256WithRSAEncryption
[DBG] subjectAlternativeName = somealias1.fqdn.com somealias2.fqdn.com ... somehost.fqdn.com someotheralias1.fqdn.com someotheralias2.fqdn.com ...
[DBG] check CN: somehost.fqdn.com
[DBG] COMMON_NAME = somehost
[DBG] ALTNAMES    = 1
[DBG] ===============================
[DBG] checking altnames against somehost
[DBG] check Altname: somealias1.fqdn.com
[DBG] check Altname: somealias2.fqdn.com
...etc...
[DBG] CRITICAL >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[DBG] prepend_critical_message: new message    = invalid CN ('somehost.fqdn.com' does not match 'somehost')
[DBG] prepend_critical_message: HOST_NAME      = somehost
[DBG] prepend_critical_message: HOST_ADDR      = somehost
[DBG] prepend_critical_message: CN             = somehost.fqdn.com
[DBG] prepend_critical_message: SNI            =
[DBG] prepend_critical_message: FILE           =
[DBG] prepend_critical_message: SHORTNAME      = SSL_CERT
[DBG] prepend_critical_message: MSG            =
[DBG] prepend_critical_message: CRITICAL_MSG   =
[DBG] prepend_critical_message: ALL_MSG 1      =
[DBG] prepend_critical_message: MSG 2          = SSL_CERT CRITICAL somehost.fqdn.com: invalid CN ('somehost.fqdn.com' does not match 'somehost')
...etc...
```
This is corresponding `--debug` output using version 1.146.0:
```
[DBG] subject= CN = somehost.fqdn.com
[DBG] CN         = somehost.fqdn.com
[DBG] CA         = O = Let's Encrypt
[DBG] CA         = CN = R3
[DBG] CA         = CN = DST Root CA X3
[DBG] SERIAL     = [REDACTED]
[DBG] FINGERPRINT= [REDACTED]
[DBG] OCSP_URI   = http://r3.o.lencr.org
[DBG] ISSUER_URI = http://r3.i.lencr.org/
[DBG]     Signature Algorithm: sha256WithRSAEncryption
[DBG] subjectAlternativeName = somealias1.fqdn.com somealias2.fqdn.com ... somehost.fqdn.com someotheralias1.fqdn.com someotheralias2.fqdn.com ...
[DBG] Checking expiration date
...etc...
```
Now why does this matter? Well, all of our many servers are defined in Nagios without the FQDN and all of the other Nagios plugins we use work without the FQDN....

Would you consider changing check_ssl_cert so that it would work with the short hostnames again?

Thanks!

**Comment by esabol** [comment]
Basically, if the argument to the `-H` option does not include a period, append the output of either of the following two commands to the provided hostname:

`hostname --fqdn | cut -d. -f2-`
or
``nslookup `hostname` | grep ^Name: | cut -d. -f2-``

**Comment by matteocorti** [comment]
Thanks for the suggestion. I'll include

```
nslookup 'hostname' | grep ^Name | head -n 1 | cut -d. -f2-
```

**Comment by esabol** [comment]
Upgraded to 2.1.2, and it works great. Thanks!

You ended up doing `nslookup ${HOST}`, I see. Pedantically, I feel the domain should be determined by the local host. In practice, I guess it doesn't matter much.

Just for comparative reference, Puppet uses `hostname -f` on Linux, FreeBSD, and macOS. (`hostname -f` apparently has broader support than `hostname --fqdn` which is GNU-only.) If that doesn't work, it uses `dnsdomainname` (a Unix standard command that I'll admit I've never even heard of before). And, if that doesn't work, it finally resorts to parsing `/etc/resolv.conf`. That's probably overkill for check_ssl_cert, but I thought I'd mention it in case it's useful in the future. Here's the (Ruby) code: 
https://github.com/Jimdo/facter/blob/master/lib/facter/domain.rb#L21

**Comment by matteocorti** [comment]
You are right. I'll update as soon as possible

**Comment by matteocorti** [comment]
* Mmmm `hostname -f` ist just for the local host.
 * `dnsdomainname` is not available on a lot of platforms
 * Parsing `resolve.conf` could be an option but not on macOS

**Comment by matteocorti** [comment]
Using `hostname` can also not be what a user want. I can have an hostname like `myhost.example.org` with different domains in `resolv.conf` to search (like `example.com`.

So even if the machine where the script is running is `myhost.example.org` I am using `www` as an host name and it resolves to `www.example.com` and not `www.example.org` (the domain I am using).

I suppose that a user would like the script to behave as all the other tools (`www` being resolved using the specified search domains).

But maybe I misunderstood ...
