### ISSUE TITLE
--check-ssl-labs-warn without --check-ssl-labs results in "integer expression expected" error

### ISSUE THREAD

**Issue by esabol** [matteocorti/check_ssl_cert#282]
After upgrading to 2.1.3, I thought I'd try the `--check-ssl-labs*` options and encountered this:
```
% ./check_ssl_cert-2.1.3/check_ssl_cert -H REDACTED -P https -p 443 -w 7 -c 3 --check-ssl-labs-warn B
./check_ssl_cert-2.1.3/check_ssl_cert: line 2483: [: : integer expression expected
```
I guess it makes sense that `--check-ssl-labs-warn` requires `--check-ssl-labs`, but I feel that the error condition could be reported better.

**Comment by matteocorti** [comment]
Fixed, I did not force the critical. If someone just wants the warning why not.

**Comment by esabol** [comment]
Even better! Thanks!

**Comment by matteocorti** [comment]
Version 2.1.4 released
