### ISSUE TITLE
Cert files in /tmp not cleaned up? Or permissions should allow usage by multiple users?

### ISSUE THREAD

**Issue by esabol** [matteocorti/check_ssl_cert#283]
When I execute check_ssl_cert, it leaves the following files in /tmp:
```
-rw-------. 1 nagios   nagios          1314 May  6 17:51 dstrootcax3.p7c
-rw-------. 1 nagios   nagios          1586 May  6 17:51 r3.i.lencr.org
```
Debug output shows that the "cleaning up temporary files" step doesn't clean up these files, so they persist between runs.

Because of the permissions on these files, another user who tries to execute check_ssl_cert on the same server will get errors:
```
[...]
[DBG] OCSP: storing a copy of the retrieved issuer certificate to /tmp/dstrootcax3.p7c
cp: cannot create regular file `/tmp/dstrootcax3.p7c': Permission denied
[...]
[DBG] OCSP: storing a copy of the retrieved issuer certificate to /tmp/r3.i.lencr.org
cp: cannot create regular file `/tmp/r3.i.lencr.org': Permission denied
[...]
```
Setting $TMPDIR to a different directory eliminates these "Permission denied" errors. Is that the recommended usage?

**Comment by matteocorti** [comment]
Dear Ed

This is intended as a feature in debug mode. The certificates are stored in the current directory so that can be analyzed.

What do you suggest? Create them with a special option? Change the permissions?

Matteo

**Comment by esabol** [comment]
> This is intended as a feature in debug mode.

Ah, OK, so it's only a problem if you specify `--debug`?

> The certificates are stored in the current directory so that can be analyzed.

Except my current working directory when I execute check_ssl_cert is not /tmp/ (but I generally prefer them being saved to $TMPDIR, so forget I mentioned that discrepancy)....

> What do you suggest? Create them with a special option? Change the permissions?

Well, ideally, I suppose they should have 666 permissions if and only if they are saved in /tmp or /var/tmp so as to not cause issues when other users execute check_ssl_cert, but now that I know it's intentional and that it only happens if you use `--debug`, I'm fine with the status quo.

**Comment by matteocorti** [comment]
Strange, it seems indeed that is not what I thought. I'll take a look

**Comment by matteocorti** [comment]
It just for debugging but in the wrong directory

**Comment by matteocorti** [comment]
I fixed the bug and introduced a new option `--debug-cert` to store the certificates in the current directory
`-d` now does not clutter anymore
