### ISSUE TITLE
Certificate with "data" or "Certificate" in file name erroronously detected as DER format

### ISSUE THREAD

**Issue by prupert** [matteocorti/check_ssl_cert#289]
**Describe the bug**

Certificate with "data" or "Certificate" in file name erroronously detected as DER format because `file` output has filename in it's output and the plugin checks for `grep -q -E '(data|Certificate)'`

Fix it easilly by using the `-b` flag for `file` (for brief output without filename).

Patch:

Change line 1472 https://github.com/matteocorti/check_ssl_cert/blob/v2.3.4/check_ssl_cert#L1472
```
elif "${FILE_BIN}" "${FILE}" | grep -q -E '(data|Certificate)' ; then
```
to:
```
elif "${FILE_BIN}" -b "${FILE}" | grep -q -E '(data|Certificate)' ; then
```

Possibly `${FILE_BIN}` output is also used incorrectly in other places.

We also noticed that `"${OPENSSL}" x509 -inform der -in "${FILE}" -out "${CERT}"` on line 1475 is NOT checked for errors and the script continues to run with incorrect input.

**Comment by matteocorti** [comment]
I'll take a look. Thanks
