### ISSUE TITLE
OCSP check not working

### ISSUE THREAD

**Issue by matteocorti** [matteocorti/check_ssl_cert#3]
See for example

    ./check_ssl_cert -H www.google.com -r ./check_ssl_cert --ocsp
    Error querying OCSP responder
    140735307825232:error:27076072:OCSP routines:PARSE_HTTP_LINE1:server response error:ocsp_ht.c:314:Code=400,Reason=Bad Request
    SSL_CERT WARN www.google.com: |days=76;;;;

**Comment by motokochan** [comment]
OCSP seems to work fine on at least some environments when I just ran a check. Following is the output from a CentOS 7 system:

```./check_ssl_cert -H www.google.com --ocsp
SSL_CERT OK - X.509 certificate for 'www.google.com' from 'Google Internet Authority G2' valid until Mar  9 00:00:00 2016 GMT (expires in 65 days)|days=65;;;;```

The OCSP check doesn't work properly on OS X, possibly because of the older OpenSSL (0.9.8za on my test machine).

What system are you using to run your command?

**Comment by ChrisRut** [comment]
I am running into a similar issue, I am also on CentOS7 and I am running the latest release (https://github.com/matteocorti/check_ssl_cert/releases/tag/v1.26.0):
```
# ./check_ssl_cert -H www.google.com --openssl /usr/bin/openssl --ocsp
Error connecting BIO
Error querying OCSP responsder
139796137310112:error:2006A066:BIO routines:BIO_get_host_ip:bad hostname lookup:b_sock.c:149:host=clients1.google.com
SSL_CERT WARN www.google.com:
```

**Comment by matteocorti** [comment]
There are several bugs in the OCSP handling but what is also strange is the the URI specified in the Certificate delivers a 404

http://clients1.google.com/ocsp

**Comment by matteocorti** [comment]
Fixed with version 1.30.0

**Comment by tomstockton** [comment]
Which version of openssl should I use in order to use the OCSP checks?

When running in debug mode (with versions 1.0.1t and 1.0.2h) I see
```
openssl ocsp does not support the -header option: disabling OCSP checks
```

Looks like the `-header` option is in version '1.1.0' however when I try to use this version I get the following error:

```
# /usr/local/bin/openssl version
OpenSSL 1.1.0-pre5 (beta) 19 Apr 2016
# ./check_ssl_cert -H www.github.com -d --openssl /usr/local/bin/openssl
Invalid command 'list-standard-commands'; type "help" for a list.
SSL_CERT UNKNOWN: /usr/local/bin/openssl ist not an openssl executable
```

**Comment by matteocorti** [comment]
Which system are you using? I have the option in 1.0.2h

The message you are getting with 1.1.0 is also strange. What happens with `/usr/local/bin/openssl list-standard-commands`
