### ISSUE TITLE
Renegotiation check times out

### ISSUE THREAD

**Issue by matteocorti** [matteocorti/check_ssl_cert#303]
**Describe the bug**

The renegotiation check

```
printf 'R\n' | /usr/bin/openssl s_client  -connect IP:443 2>&1 | grep -F -q err
```

times out on FreeBSD

**Additional context/output**

It seems that we need ```-crlf``` to the connection options

**Comment by peternewman** [comment]
This still times out for me on some hosts checking from Ubuntu and the -crlf option is present.

It appears to be down to the webserver as it varies depending on what I'm checking, but the ignore option is working at least...

**Comment by matteocorti** [comment]
Hi, do you have a public IP that I could use for some tests?
Which version of Ubuntu?

**Comment by peternewman** [comment]
> Hi, do you have a public IP that I could use for some tests?

I don't unfortunately, but happy to run tests internally (although I appreciate that may be rather painful to diagnose).

> Which version of Ubuntu?

I've tried various, interestingly on 20.04.2 it works although the whole process takes just over a minute:
```
[DBG] checking TLS renegotiation
[DBG] executing with timeout (80s): printf 'R
[DBG] ' | /usr/bin/openssl s_client  -crlf -connect foo.example.com:443 2>&1 | grep -F -q err
[DBG]   start time = 1647641229
[DBG] /usr/bin/timeout 80 /bin/sh -c "printf 'R
[DBG] ' | /usr/bin/openssl s_client  -crlf -connect foo.example.com:443 2>&1 | grep -F -q err"
[DBG]   end time = 1647641289
[DBG]   new timeout = 20
TLS renegotiation OK
```

If I wind the timeout down to 25s to suit my Nagios install, it times out before renegotiating.

` time ./check_ssl_cert -H foo --verbose --debug -t 25`

Which is probably because of this:
```
time printf 'R
> ' | /usr/bin/openssl s_client  -crlf -connect foo.example.com:443 2>&1 | grep -F -q err

real    1m0.051s
user    0m0.009s
sys     0m0.006s
```

**Comment by peternewman** [comment]
Not the cause, but another issue, if I run a modified version of that command (i.e. that command will fail because another cert in the chain has expired):
```
time printf 'R
' | /usr/bin/openssl s_client  -crlf -connect foo.example.com:443 2>&1 | grep -F err
verify error:num=10:certificate has expired
140051202172568:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:s3_pkt.c:656:

real    1m0.049s
user    0m0.008s
sys     0m0.000s
```

**Comment by peternewman** [comment]
Having updated my cert chain, it's still giving this failure (or would if it wasn't in quiet mode):
```
time printf 'R
' | /usr/bin/openssl s_client  -crlf -connect foo.example.com:443 2>&1 | grep -F err
139876551812760:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:s3_pkt.c:656:

real    1m0.050s
user    0m0.004s
sys     0m0.000s
```

Perhaps easier to reproduce, the same thing happens with an SSL secured RDP connection (checking port 3389).

**Comment by matteocorti** [comment]
Can you please post the whole debugging output? I suspect that there is an earlier critical warning that is then postponed. In this case I should skip the renegotiation check. Or maybe do the renegotiation check only if everything else works.

**Comment by matteocorti** [comment]
I tested with Ubuntu 20.04.2 and a couple of servers but could not reproduce the problem ...

**Comment by MrCaffeen** [comment]
I have managed to replicate this on one of my servers, but the issue seems to be not with the checking script but with the server being checked. I have most of my checks running and completed in 15 seconds or less. But one service on a server takes over 1min on the TLS checking. 
From what I can see it looks to be stalling on the TLS renegotiation, but that could be because of the supported TLS protocols set on the server being checked.

**Comment by matteocorti** [comment]
> I have managed to replicate this on one of my servers, but the issue seems to be not with the checking script but with the server being checked. I have most of my checks running and completed in 15 seconds or less. But one service on a server takes over 1min on the TLS checking.
> From what I can see it looks to be stalling on the TLS renegotiation, but that could be because of the supported TLS protocols set on the server being checked.

Is it a machine that I could use to debug the issue?

**Comment by matteocorti** [comment]
As there is no way to reproduce the problem, I'll close the ticket.
