### ISSUE TITLE
CAA check if empty --issuer used

### ISSUE THREAD

**Issue by osgpcq** [matteocorti/check_ssl_cert#305]
**Is your feature request related to a problem? Please describe.**
The goal is to test if the certificate issuer is one of CAA DNS records of the domain:
titi.com.           3600    IN      CAA     0 issue "letsencrypt.org"
titi.com.           3600    IN      CAA     0 issue "godaddy.com"
titi.com.           3600    IN      CAA     0 issue "digicert.com"

**Describe the solution you'd like**
If I understood correctly the --issuer needs a chain input to check chains in the certificate.
Would be nice to add the possibility for the input of --issuer to be extracted from the DNS CAA records.

**Describe alternatives you've considered**
I check the DANE solution but look more related services.
And anyway I think it could be useful to check it.

**Additional context**
-

**Comment by matteocorti** [comment]
Hi

It's a nice idea but I am not really sure how I could validate it. Let's take google:

```
google.com has CAA record 0 issue "pki.goog"
```

In the certificate I see

```
        Issuer: C = US, O = Google Trust Services LLC, CN = GTS CA 1C3
```

Is there a way to get the some data automatically from ```pki.goog```? Or should I assume that the issuer used by pki.goog  has to be exacty the same as google.com?

**Comment by osgpcq** [comment]
Hi,
In fact, checking your answer, I think I misinterpreted the CAA record use... :(

Look like the record is used on the CA certificate delivery side and not on the client-side to check if the cert:
https://en.wikipedia.org/wiki/DNS_Certification_Authority_Authorization
`Certificate authorities implementing CAA perform a DNS lookup for CAA resource records, and if any are found, ensure that they are listed as an authorized party before issuing a digital certificate.`

So really sorry for the sound ! :(

**Comment by matteocorti** [comment]
Ok thanks anyway
