### ISSUE TITLE
Check certs on disk

### ISSUE THREAD

**Issue by varac** [matteocorti/check_ssl_cert#309]
Sometimes it's neccessary to check cert files on disk, i.e. the TLS cert used in a Radius setup.
Please support this use case as well.

**Comment by matteocorti** [comment]
Check the ```--file``` option.

e.g.

```
./check_ssl_cert -H localhost --file /path/to/the/certificate.crt
```

**Comment by varac** [comment]
Oh how awesome, I was confused by the mandatory `-H ` option. Thx !

**Comment by matteocorti** [comment]
Anyway: I committed a new version wich automatically assumes localhost if ```-file``` is specified. Not enough for a new release but will come with the next one. Thanks for the hint

**Comment by varac** [comment]
Great!
