### ISSUE TITLE
Confusing error message when the cert SAN has a typo in it

### ISSUE THREAD

**Issue by peternewman** [matteocorti/check_ssl_cert#363]
**Describe the bug**

Given a cert with a SAN with a typo (note .cm not .com here), I get the following logging:

```
[DBG] check CN                   foo.example.com
[DBG] COMMON_NAME              = 192.168.0.1 foo.example.com foo
[DBG] ALTNAMES                 = 1
[DBG] SUBJECT_ALTERNATIVE_NAME = foo.example.cm foo 192.168.0.1
CRITICAL error: invalid CN ('foo.example.com' does not match 'foo.example.com, foo')
```

Whereas I'd expect/desire:
`CRITICAL error: invalid CN ('foo.example.cm' does not match 'foo.example.com, foo')`

Or certainly something that doesn't say "a does not match a" when it clearly does!

I've looked at the code a bit and I feel like I'm missing something obvious but can't see a clear fix, maybe because it's checking by the COMMON_NAME field against the SUBJECT_ALTERNATIVE_NAME rather than the other way round.

I don't know if this has arisen from #355 ?

**To Reproduce**

Have a cert with a typo and check for the valid version.

**Expected behavior**

Report the SAN which doesn't match

**System (please complete the following information):**

 - OS: Ubuntu
 - OS version: [e.g. 22]
 - check_ssl_cert version: latest
 - OpenSSL version (```openssl version```): [e.g., 3.0.0]

**Comment by matteocorti** [comment]
Seems worse than just a problem with the error message.

I habe a certificate with the following config:

```
[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no
[req_distinguished_name]
C = CH
ST = ZH
L = Zurich
O = ETH
OU = ID
CN = matteo.ethz.ch
[v3_req]
keyUsage = keyEncipherment, dataEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names
[alt_names]
DNS.1 = www.matteo.ethz.ch
DNS.2 = ftp.matteo.ethz.cn
DNS.3 = test.matteo.ethz.ch
```

created with ``` openssl req -x509 -nodes -days 730 -newkey rsa:2048 -keyout typo.pem -out typo.pem -config typo.conf -extensions 'v3_req'```

And

```
$ ./check_ssl_cert --file ./typo.pem -s --cn ftp.matteo.ethz.ch --cn matteo.ethz.ch
SSL_CERT CRITICAL matteo.ethz.ch: invalid CN ('matteo.ethz.ch' does not match 'ftp.matteo.ethz.ch matteo.ethz.ch')|days_chain_elem1=729;20;15;; 
```

**Comment by matteocorti** [comment]
> 

Which command line options are you using to check?

**Comment by peternewman** [comment]
> ```
> $ ./check_ssl_cert --file ./typo.pem -s --cn ftp.matteo.ethz.ch --cn matteo.ethz.ch
> SSL_CERT CRITICAL matteo.ethz.ch: invalid CN ('matteo.ethz.ch' does not match 'ftp.matteo.ethz.ch matteo.ethz.ch')|days_chain_elem1=729;20;15;; 
> ```

Note how mine had a comma within the match list, whereas yours doesn't, although we are using slightly different args.

> Which command line options are you using to check?

Mine would have been something like (I see `--cn/-n` are identical):
`./check_ssl_cert -H 192.168.0.1 -n 192.168.0.1 -n foo.example.com -n foo --altnames`

I understand altnames is now optional.

**Comment by peternewman** [comment]
Okay, simpler example that I can share and you can replicate hopefully (I was doing it behind a proxy, but hopefully it should behave the same):
```
./check_ssl_cert -H admin.digicert.com -n content.digicert.com --cn aphid.digicert.com -n aws.digicert.com --cn login.digicert.com
SSL_CERT CRITICAL www.digicert.com: invalid CN ('www.digicert.com' does not match 'aphid.digicert.com, aws.digicert.com')|days_chain_elem1=46;20;15;; days_chain_elem2=2409;20;15;;
```
_Note my deliberate typos for their ws and api!_

With the following debug:
```
[DBG] subjectAlternativeName = www.digicert.com digicert.com admin.digicert.com api.digicert.com content.digicert.com login.digicert.com order.digicert.com ws.digicert.com
[DBG] check CN                   www.digicert.com
[DBG] COMMON_NAME              = admin.digicert.com content.digicert.com aphid.digicert.com aws.digicert.com login.digicert.com
[DBG] ALTNAMES                 = 1
```

Which I think clarifies that what it actually wants to say is that none of "www.digicert.com digicert.com admin.digicert.com api.digicert.com content.digicert.com login.digicert.com order.digicert.com ws.digicert.com" matches "aphid.digicert.com, aws.digicert.com". i.e. it's correctly collecting the names I've asked it to check which don't match, but it's only showing me the CN during it's report, despite the fact I've also asked it to match the SAN.

How's the check actually supposed to work? Shouldn't it actually be saying:
`'www.digicert.com digicert.com admin.digicert.com api.digicert.com content.digicert.com login.digicert.com order.digicert.com ws.digicert.com' does not match 'aphid.digicert.com, aws.digicert.com'`
or even:
`'aphid.digicert.com, aws.digicert.com' not found in 'www.digicert.com digicert.com admin.digicert.com api.digicert.com content.digicert.com login.digicert.com order.digicert.com ws.digicert.com'`
