### ISSUE TITLE
Re-add the ability to check IPs in SANs (optionally) since it was removed in #301

### ISSUE THREAD

**Issue by peternewman** [matteocorti/check_ssl_cert#364]
**Is your feature request related to a problem? Please describe.**

I can't check that IP addresses correctly exist in SANs since #301 .

**Describe the solution you'd like**

Could it be added back as an option (maybe disabled by default).

**Describe alternatives you've considered**

Not checking IPs in SANs (as currently)

**Comment by matteocorti** [comment]
Do you have an example with debugging output? You have an IP address as a SAN?

**Comment by matteocorti** [comment]
It's a bug:

```
SSL_CERT OK - github.com:443, https, x509 certificate 'github.com' (github.com 129.132.98.12) from 'DigiCert Inc' valid until Mar 15 23:59:59 2023 GMT (expires in 356 days)|days_chain_elem1=356;20;15;; days_chain_elem2=3307;20;15;;
```

Should be a critical

**Comment by peternewman** [comment]
> Do you have an example with debugging output?

I'll try and generate one in due course. I was trying to generate a local cert (well extend your existing test), but I couldn't get it to add a SAN IP or otherwise...

> You have an IP address as a SAN?

Someone else set them up, I'm just trying to monitor them, but they're securing RDP access to servers so I assume the theory is it will work and won't complain whether you connect via the hostname, FQDN or IP.

> It's a bug:
> 
> ```
> SSL_CERT OK - github.com:443, https, x509 certificate 'github.com' (github.com 129.132.98.12) from 'DigiCert Inc' valid until Mar 15 23:59:59 2023 GMT (expires in 356 days)|days_chain_elem1=356;20;15;; days_chain_elem2=3307;20;15;;
> ```
> 
> Should be a critical

What was your command line, it seems like you've found a reverse bug of what I want.

If I run:
`./check_ssl_cert -H github.com -n github.com -n 127.0.0.1 -n www.github.com
SSL_CERT OK - github.com:443, https, x509 certificate 'github.com' (github.com github.com 127.0.0.1 www.github.com) from 'DigiCert Inc' valid until Mar 15 23:59:59 2023 GMT (expires in 355 days)|days_chain_elem1=355;20;15;; days_chain_elem2=3306;20;15;;`

Then it's both not complaining 127.0.0.1 isn't present as a SAN, but also (and probably worse) it's including it in the output as suggesting it's a SAN. Although adding foo.github.com to the list is caught as expected.

Related, if I check GitHub's IP:
```
./check_ssl_cert -H 140.82.121.4 -n github.com -n 127.0.0.1 -n www.github.com
SSL_CERT OK - 140.82.121.4:443, https, x509 certificate 'github.com' (140.82.121.4 github.com 127.0.0.1 www.github.com) from 'DigiCert Inc' valid until Mar 15 23:59:59 2023 GMT (expires in 355 days)|days_chain_elem1=355;20;15;; days_chain_elem2=3306;20;15;;
```

It shows it in the bracketed list, despite it not being a SAN (which I sort of assumed was what that showed).

**Comment by matteocorti** [comment]
The whole code for the CN and SAN check is a mess (was written to check the CN, then extended for SANs and messed up).

As soon as I find some time in the next day I'll rewrite it completely.

**Comment by peternewman** [comment]
Thanks. I could probably fix it to cover this case, but if you think it needs a rewrite it might be better left to you. In the meantime I've opened #374 with some tests to catch the case above.

If I ever manage to generate a cert with a SAN and stick an IP in it I'll add a positive test too.
