### ISSUE TITLE
Support "Authority Information Access" (AIA)

### ISSUE THREAD

**Issue by code-and-such** [matteocorti/check_ssl_cert#366]
**Is your feature request related to a problem? Please describe.**

All current browsers supports AIA (the "Authority Information Access" extension). The server only delivers the site cert, and then the AIA information in the cert tells the browser where it can find the issuer. The browser then proceeds to fetch it from there.
Since this kind of alarm very often is about figuring out whether a browser would choke, then I find it reasonable that it support this extension. 

A complicating factor is that openssl s_client, which it seems that you depend on do not support this out of box. To do this kind of check, several invocations, or even tools (like curl) would need to be involved. There are blogposts out there how it can be done, and those would be possible to turn into scripts. It would be ideal if openssl themselves included this, of course. I did the lazy thing and placed my ticket here - but it's not unlikely that there is a ticket in their tracker already.

**Describe the solution you'd like**

A flag to enable this feature. I'm not sure it should be enabled by default - many older clients (older java versions, curl, wget, openssl s_client) do not support it out of box. 

**Describe alternatives you've considered**

Script it myself. But going from a maintained solution, like this one, to a home brewed one, is not overly appealing. 

I do not feel I have the time right now to generate a PR - and it's not unlikely that it would ugly up the code to an unacceptable degree.

**Comment by matteocorti** [comment]
Maybe I understood you wrongly but the plugin is already getting the OCSP URI and the issuer URI from the cert.

Do you have an example of a case when is not working?

**Comment by matteocorti** [comment]
Anyway the is already checking it. And it makes sense as OCSP has to checked. The behavior can also be optionally disabled.

**Comment by matteocorti** [comment]
> I'm sorry, I did not understand what you are saying.
> 
> 
> 
> Are you saying AIA is already implemented and considered?
> 
> So a server without incorrect configuration (missing intermediate certificates) will return OK to nagios because of AIA (but fail in clients not implementing AIA)?
> 
> 
> 
> 

It is already implemented. If not working let me know.

**Comment by lukastribus** [comment]
I think there is come confusion here.

AIA has nothing to do with OCSP or CRL at all, AIA is not about revocation checking.

If AIA is implemented, which command line argument disables it - I cannot find it.

**Comment by lukastribus** [comment]
Right, AIA provides multiple different informations, OCSP is part of that, I did not know that. However that is not the point.

The point is that the OP is talking about fetching intermediate certificates from remote URIs for miss-configured servers (without intermediate certificates or the wrong ones), through AIA provided URI (the `CA issuers` URI from your github.com output presumably).

I believe this is not implemented and I believe this should NOT be implemented, because its only hiding server configuration issues, which we can argue can be useful in a browser but imho does not belong in a monitoring tool, because in my monitoring I want to actual detect configuration issues.

**Comment by lukastribus** [comment]
My only intention was to make sure we are talking about the same thing. I'm actually advocating to *not* implement this.

**Comment by matteocorti** [comment]
I know. I would just like to check if some browsers are using the information and what could happen.

**Comment by code-and-such** [comment]
I figured out what happens on our side. Apparently our certs to not use OCSP, but only have the CA Issuers part. Using your example about it would be 

```
            Authority Information Access: 
                CA Issuers - URI:http://cacerts.digicert.com/DigiCertTLSHybridECCSHA3842020CA1-1.crt
```
rather than 
```
            Authority Information Access: 
                OCSP - URI:http://ocsp.digicert.com
                CA Issuers - URI:http://cacerts.digicert.com/DigiCertTLSHybridECCSHA3842020CA1-1.crt
```
Apparently browsers buy that too.

**Comment by matteocorti** [comment]
The plugin should work. Do you have a URL that I could test?
