### ISSUE TITLE
Not all of the last 24 hours is necessarily today

### ISSUE THREAD

**Issue by peternewman** [matteocorti/check_ssl_cert#375]
**Describe the bug**

Since:
https://github.com/matteocorti/check_ssl_cert/commit/d6aa200cbabc702daea207337d33fbf19be0162d

"is expired (was valid until Apr 17 18:19:20 2022 GMT, today)"
However I'm writing this on:
Mon 18 Apr 2022

I'd argue that it was valid until Apr 17th, yesterday, and it would only be today since midnight.

**To Reproduce**

Check an expired certificate which expired in the last 24 hours, but before midnight.

I was going to try and add a test but it seemed a bit fiddly to do...

**Expected behavior**

"is expired (was valid until Apr 17 18:19:20 2022 GMT, yesterday)"

I'm aware there's a whole world of pain around timezones etc, so maybe changing it to say "last 24 hours"/"last 48 hours" might be easier?

**System (please complete the following information):**

 - check_ssl_cert version: 2.22.0

**Comment by matteocorti** [comment]
I agree, for a correct behaviour I should also consider time zones, and on some platforms, it could be a nightmare. I will follow your suggestion and keep it simple.
