### ISSUE TITLE
--check-ciphers and --check-ciphers-warnings return no data on non-standard ports for nmap < 7.60

### ISSUE THREAD

**Issue by EdCates** [matteocorti/check_ssl_cert#378]
**Describe the bug**

When using the --check-ciphers and --check-ciphers-warnings, the test returns with "empy nmap result while checking ciphers"

**To Reproduce**

1. Set up an SSL service on a non-standard port. _eg_ 9031
2. ./check_ssl_cert -H host.name --check-ciphers-warning -p 9031

**Expected behavior**
Returns "SSL_CERT OK..." or other meaningful output

**System (please complete the following information):**

 - OS: RHEL
 - OS version: 7.2
 - check_ssl_cert version: 2.25.0
 - OpenSSL version (```openssl version```): 1.0.2k-fips
 - Nmap version: 6.47
 
**Additional context/output**

According to [this nmap issue](https://github.com/nmap/nmap/issues/168#issuecomment-113149806), this is expected behavior for older versions of nmap (< 7.60).  It would work with older versions if check_ssl_cert's nmap call, '--script ssl-enum-ciphers',  were changed to '--script +ssl-enum-ciphers', and that change is still compatible with newer nmap versions (tested with nmap 7.92 on CentOS 7.9).

`[ecates@host check_ssl_cert-2.25.0]$ nmap -v

Starting Nmap 6.47 ( http://nmap.org ) at 2022-04-27 12:47 EDT
Read data files from: /usr/bin/../share/nmap
WARNING: No targets were specified, so 0 hosts scanned.
Nmap done: 0 IP addresses (0 hosts up) scanned in 0.04 seconds
[ecates@host check_ssl_cert-2.25.0]$ /usr/bin/nmap -Pn --script ssl-enum-ciphers host.name -p 9031

Starting Nmap 6.47 ( http://nmap.org ) at 2022-04-27 12:48 EDT
Nmap scan report for host.name (x.x.x.x)
Host is up (0.00038s latency).
PORT     STATE SERVICE
9031/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 0.07 seconds

[ecates@host check_ssl_cert-2.25.0]$ /usr/bin/nmap -Pn --script +ssl-enum-ciphers host.name -p 9031

Starting Nmap 6.47 ( http://nmap.org ) at 2022-04-27 12:50 EDT
Nmap scan report for host.name (x.x.x.x)
Host is up (0.00038s latency).
PORT     STATE SERVICE
9031/tcp open  unknown
| ssl-enum-ciphers:
|   TLSv1.0: No supported ciphers found
|   TLSv1.1: No supported ciphers found
|   TLSv1.2:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 - strong
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 - strong
|       TLS_RSA_WITH_AES_128_CBC_SHA256 - strong
|       TLS_RSA_WITH_AES_128_GCM_SHA256 - strong
|     compressors:
|       NULL
|_  least strength: strong

Nmap done: 1 IP address (1 host up) scanned in 0.19 seconds`

`[ecates@otherhost ~]$ nmap -v
Starting Nmap 7.92 ( https://nmap.org ) at 2022-04-25 00:10 EDT
Read data files from: /usr/bin/../share/nmap
WARNING: No targets were specified, so 0 hosts scanned.
Nmap done: 0 IP addresses (0 hosts up) scanned in 0.02 seconds

[ecates@otherhost ~]$ nmap -Pn --script +ssl-enum-ciphers  host.name -p 9031
Starting Nmap 7.92 ( https://nmap.org ) at 2022-04-25 00:10 EDT
Nmap scan report for host.name (x.x.x.x)
Host is up (0.042s latency).

PORT     STATE SERVICE
9031/tcp open  unknown
| ssl-enum-ciphers:
|   TLSv1.2:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (secp256r1) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
|     compressors:
|       NULL
|     cipher preference: client
|   TLSv1.3:
|     ciphers:
|       TLS_AKE_WITH_AES_128_GCM_SHA256 (secp256r1) - A
|       TLS_AKE_WITH_AES_256_GCM_SHA384 (secp256r1) - A
|     cipher preference: client
|_  least strength: A

Nmap done: 1 IP address (1 host up) scanned in 1.57 seconds`

**Comment by matteocorti** [comment]
Thanks, can you please test? I don't habe a RHEL 7 machine at the moment to test

**Comment by EdCates** [comment]
> Thanks, can you please test? I don't habe a RHEL 7 machine at the moment to test

Sorry, Just getting up and seeing this. I'll give it a test.

**Comment by matteocorti** [comment]
Sorry

**Comment by matteocorti** [comment]
Fixed

**Comment by EdCates** [comment]
No worries, it happens.  Thanks for being so on top of the responses!  

Confirmed it's working for me now.
