### ISSUE TITLE
xmpp check fails with "unsupported protocol"

### ISSUE THREAD

**Issue by arekm** [matteocorti/check_ssl_cert#388]
**Describe the bug**

There are two sections in script that need to be synchronized.

Both return: ````unknown "Error: unsupported protocol ${PROTOCOL}"````

Currently only one script section supports "xmpp" protocol but the other is not which causes "unsupported protocol".
Same for xmpp-server, didn't check other protocols.

**To Reproduce**

````
./check_ssl_cert -H jabber.org -P xmpp
SSL_CERT UNKNOWN: Error: unsupported protocol xmpp
````

**Expected behavior**

after adding
````
            xmpp | xmpp-server )
                    ;;
````
into second section:

````
 ./check_ssl_cert -H jabber.org -P xmpp
SSL_CERT OK - jabber.org:, xmpp, x509 certificate 'jabber.org' from 'Let's Encrypt' valid until Jun 27 15:05:56 2022 GMT (expires in 32 days)|days_chain_elem1=32;20;15;; days_chain_elem2=1208;20;15;; days_chain_elem3=858;20;15;;
````

**System (please complete the following information):**

 - check_ssl_cert version: 2.27.0

**Comment by matteocorti** [comment]
The error is because the script does not know the default port it should use for XMPP.
I'll fix it. As a workaround, you can just specify the port with --port.

**Comment by arekm** [comment]
xmpp uses different variable XMPPPORT which is set in script to default 5222 and -p overrides it (along with PORT variable)

````
XMPPPORT="5222"
````


````
xmpp | xmpp-server)
            exec_with_timeout "echo 'Q' | ${OPENSSL} s_client ${INETPROTO} ${CLIENT} ${CLIENTPASS} -starttls ${PROTOCOL} -showcerts -connect ${HOST_ADDR}:${XMPPPORT} ...
````

Dropping XMPPORT and using PORT only cleanup would make sense.

**Comment by matteocorti** [comment]
Thanks, makes sense.
