### ISSUE TITLE
ipv6 ip doesn't work with --resolve

### ISSUE THREAD

**Issue by jinbo75** [matteocorti/check_ssl_cert#396]
**Describe the bug**

when I supply ipv6 address as --resolve, I got an error: SSL_CERT CRITICAL wildcard.prod.sentinelcloud.com: xxxx:xxxx:0:4bed:: is not a valid hostname

**To Reproduce**

`./check_ssl_cert -H FQDN.com --resolve xxxx:xxxx:0:4bed:: -w 30 -c 5 -s`

**Expected behavior**

it should work.

**System (please complete the following information):**

 - OS: Ubuntu 20
 - OS version: 20
 - check_ssl_cert version: [e.g. 1.19.0]
 - OpenSSL version (```openssl version```): 2.31.0

**Additional context/output**

none

**Comment by matteocorti** [comment]
It's a minor issue: OpenSSL expects the IPv6 in brackets. Using [IPv6] seems to work. I'll add the brackets if not present.

**Comment by jinbo75** [comment]
Thank you, Matteo! adding parenthesis works! I think you can simply update the user manual.
`--resolve ip_address [if it is ipv6, wrap the address with brackets eg. "[1234:3248:0:0::]"`

**Comment by matteocorti** [comment]
I patched the plugin. It's more intuitive to just give the IPv6 address. And it's a quick fix. Now both work (with and without)
