### ISSUE TITLE
Warning and Criticals don't work for me

### ISSUE THREAD

**Issue by jreitmayer** [matteocorti/check_ssl_cert#41]
Thank you for your plug in. Its a a huge help for our organization. I have several web servers that host multiple websites. I am trying to make your plugin pull the SSL cert from the server for specific websites and check the date before it expires. I have it pulling the SSL cert but it says the cert is OK instead of warning or critical days I set in the command. Can you help me?

Here is my command: 

./check_ssl_cert -H xxx.somedomain.com -N webserver.domain.com -w 30 -c 15

SSL_CERT OK - X.509 certificate for 'xxx.somedomain.com' from 'InCommon RSA Server CA' valid until Feb 26 23:59:59 2017 GMT (expires in 25 days)|days=25;;;;

I appreciate any help you can give. Thanks
Jeff

**Comment by matteocorti** [comment]
Dear Jeff

I cannot reproduce the problem. For example

```
./check_ssl_cert -H www.google.com -w 80 -c 10 -N www.google.com
SSL_CERT WARN www.google.com: certificate will expire on Apr 12 18:50:00 2017 GMT|days=70;80;10;;
```

Which version of the plugin are you using? Can you post the output of the command with the `-d` option?

**Comment by jreitmayer** [comment]
./check_ssl_cert -H something.domain.com -N webserver.domain.com -w 30 -c 15 -d
SSL_CERT OK - X.509 certificate for 'something.domain.com' from 'InCommon RSA Server CA' valid until Feb 26 23:59:59 2017 GMT (expires in 25 days)|days=25;;;;

./check_ssl_cert -V
check_ssl_cert version 1.38.1

as you can see. the certificate for this server expires in less than 30 days. I should be getting a warning from the check. Changing the warning and critical to different days doesn't change the behavior.

**Comment by ciscoqid** [comment]
On 2/1/2017 10:43 AM, Jeff wrote:
>
> ./check_ssl_cert -H something.domain.com -N webserver.domain.com -w 30 -c 15 -d
> SSL_CERT OK - X.509 certificate for 'something.domain.com' from 'InCommon RSA Server CA'
> valid until Feb 26 23:59:59 2017 GMT (expires in 25 days)|days=25;;;;
>
> ./check_ssl_cert -V
> check_ssl_cert version 1.38.1
>
> as you can see. the certificate for this server expires in less than 30 days. I should
> be getting a warning from the check. Changing the warning and critical to different days
> doesn't change the behavior.
>

Interesting.  Works on our wildcard, and includes the thresholds in the perfdata.

[mnagel@colby check_ssl_cert-1.38.1]$ ./check_ssl_cert -H hq-fw01 -w 150 -c 120
SSL_CERT WARN *.willingminds.com: certificate will expire on Jun 11 23:59:59 2017
GMT|days=130;150;120;;

Also on a non-wildcard:

[mnagel@colby check_ssl_cert-1.38.1]$ ./check_ssl_cert -H www.google.com -w 90 -c 60
SSL_CERT WARN www.google.com: certificate will expire on Apr 19 10:08:00 2017
GMT|days=76;90;60;;

It is the -N that is causing it to take the wrong path, it seems:

[mnagel@colby check_ssl_cert-1.38.1]$ ./check_ssl_cert -H www.google.com -N www.google.com
-w 90 -c 60   
SSL_CERT OK - X.509 certificate for 'www.google.com' from 'Google Internet Authority G2'
valid until Apr 19 10:08:00 2017 GMT (expires in 76 days)|days=76;;;;

Mark

-- 
Mark D. Nagel, CCIE #3177 Emeritus <mnagel@willingminds.com>
Principal Consultant, Willing Minds LLC (http://www.willingminds.com)
cell: 949-279-5817, desk: 714-495-4001, fax: 714-844-4698

** For faster support response time, please
** email support@willingminds.com or call 714-495-4000

**Comment by jreitmayer** [comment]
So is that a bug then? I'm not sure how to make this command work with a wild card. I have multiple web servers with multiple domain URLs and SSL certs I need monitored

**Comment by ciscoqid** [comment]
On 2/1/2017 11:21 AM, Jeff wrote:
>
> So is that a bug then? I'm not sure how to make this command work with a wild card. I
> have multiple web servers with multiple domain URLs and SSL certs I need monitored
>

It is a bug, nothing to do with wildcard.  Something in the way the -N option is handled. 
I have not traced through the code yet....

Mark

-- 
Mark D. Nagel, CCIE #3177 Emeritus <mnagel@willingminds.com>
Principal Consultant, Willing Minds LLC (http://www.willingminds.com)
cell: 949-279-5817, desk: 714-495-4001, fax: 714-844-4698

** For faster support response time, please
** email support@willingminds.com or call 714-495-4000

**Comment by jreitmayer** [comment]
Well at least I know I'm not doing something wrong then. I look forward to how i can help further. Thanks.

**Comment by matteocorti** [comment]
It is indeed a bug and have to do with the order of the options:

```
corti@mac-mini-1 check_ssl_cert> ./check_ssl_cert -H www.google.com -w 80 -c 10 -N www.google.com
SSL_CERT WARN www.google.com: certificate will expire on Apr 12 18:50:00 2017 GMT|days=69;80;10;;
corti@mac-mini-1 check_ssl_cert> ./check_ssl_cert -H www.google.com -N www.google.com -w 80 -c 10
SSL_CERT OK - X.509 certificate for 'www.google.com' from 'Google Internet Authority G2' valid until Apr 12 18:50:00 2017 GMT (expires in 69 days)|days=69;;;;
```

**Comment by matteocorti** [comment]
Also the `-d` option is ignored in your example

**Comment by matteocorti** [comment]
I got it: `-N` does not take any argument. `-n` is. So the domain is considered the next one. I have to go and publish a fix tomorrow.

**Comment by matteocorti** [comment]
I just fixed the problem

```
$ ./check_ssl_cert -H www.google.com -N -w 80 -c 10
SSL_CERT WARN www.google.com: certificate will expire on Apr 19 10:08:00 2017 GMT|days=76;80;10;;
$ ./check_ssl_cert -H www.google.com -n www.google.com -w 80 -c 10
SSL_CERT WARN www.google.com: certificate will expire on Apr 19 10:08:00 2017 GMT|days=76;80;10;;
$ ./check_ssl_cert -H www.google.com -N www.google.com -w 80 -c 10
SSL_CERT UNKNOWN: invalid option: www.google.com
```

I do not have time to release a new version this evening but I will do it as soon as possible. The plugin is working just use `-n`.

**Comment by jreitmayer** [comment]
ok but when I use the -n option i get back the call for the webservers certificate, not the certificate for the site running on the server. These are IIS boxes and have multiple websites running on them. 

Here is the example.

./check_ssl_cert -H stuactonline-test.dsa.reldom.tamu.edu -n apisrv.dsa.reldom.tamu.edu -w 30 -c 15
SSL_CERT OK - X.509 certificate for 'apisrv.dsa.reldom.tamu.edu' from 'InCommon RSA Server CA' valid until Jun  1 23:59:59 2017 GMT (expires in 120 days)|days=120;30;15;;

**Comment by ciscoqid** [comment]
On 2/1/2017 11:58 AM, Jeff wrote:
>
> ok but when I use the -n option i get back the call for the webservers certificate, not
> the certificate for the site running on the server. These are IIS boxes and have
> multiple websites running on them.
>
> Here is the example.
>
> ./check_ssl_cert -H stuactonline-test.dsa.reldom.tamu.edu -n apisrv.dsa.reldom.tamu.edu
> -w 30 -c 15
> SSL_CERT OK - X.509 certificate for 'apisrv.dsa.reldom.tamu.edu' from 'InCommon RSA
> Server CA' valid until Jun 1 23:59:59 2017 GMT (expires in 120 days)|days=120;30;15;;
>

You are selecting the correct certificate via SNI using the -n option so you can monitor
all the certs on the same IP.  That one doesn't expire until Jun 1.

Mark

-- 
Mark D. Nagel, CCIE #3177 Emeritus <mnagel@willingminds.com>
Principal Consultant, Willing Minds LLC (http://www.willingminds.com)
cell: 949-279-5817, desk: 714-495-4001, fax: 714-844-4698

** For faster support response time, please
** email support@willingminds.com or call 714-495-4000

**Comment by jreitmayer** [comment]
So for the -n Option I would use the website address again instead of the hosting web server?

**Comment by ciscoqid** [comment]
On 2/1/2017 12:03 PM, Jeff wrote:
>
> So for the -n Option I would use the website address again instead of the hosting web
> server?
>

Yes, or just leave it off.  If you don't give it the CN is assumed to be the -H param.

Mark

-- 
Mark D. Nagel, CCIE #3177 Emeritus <mnagel@willingminds.com>
Principal Consultant, Willing Minds LLC (http://www.willingminds.com)
cell: 949-279-5817, desk: 714-495-4001, fax: 714-844-4698

** For faster support response time, please
** email support@willingminds.com or call 714-495-4000

**Comment by jreitmayer** [comment]
Very odd. I have another hosting web server with a certificate going out at the end of the month.  check it against that and it says its not going out of date. I'll keep working on it.
