### ISSUE TITLE
Make nmap installation optional

### ISSUE THREAD

**Issue by stefan6419846** [matteocorti/check_ssl_cert#414]
**Is your feature request related to a problem? Please describe.**

When running the script, I am forced to provide/install the *nmap* tool. Setting `DISABLE_NMAP=1` (which seems to be an internal, undocumented mechanism) will never run *nmap* itself, but checks if it is available.

**Describe the solution you'd like**

If `DISABLE_NMAP=1` is passed, the *nmap* availability check should be skipped.

**Describe alternatives you've considered**

As the only check with passing `DISABLE_NMAP=1` is the `command -v NMAP_BIN` call, I am able to provide a dummy binary or even use `--nmap-bin /usr/bin/bash`, but a clean solution would be better in my opinion.

**Comment by matteocorti** [comment]
The ```DISABLE_NMAP``` is there in case a proxy is used. I could just set it if ```nmap``` is not available and warn the user.

Without ```nmap```:

 * There are no connection checks. If something is not working the plugin will just timeout.
 * No ciphers are be checked

**Comment by stefan6419846** [comment]
As long as the user is aware of the side-effects, I see no issues with just warning in this case.
