### ISSUE TITLE
Handling of one valid and one expired certificate for the same scope

### ISSUE THREAD

**Issue by stefan6419846** [matteocorti/check_ssl_cert#416]
**Is your feature request related to a problem? Please describe.**

I recently stumbled upon an issue with one certificate where I was being served with a certificate file with the following content:

* One valid wildcard certificate which is valid since day X (X = day in the past).
* One expired wildcard certificate which has been valid until day X + 5 days.
* The corresponding root certificates.

The wildcard certificates cover the same sites. Running `check_ssl_cert` for this certificate file will fail due to the expired certificate, although the same sites are already covered by the new valid one. Web browsers show no issues either.

**Describe the solution you'd like**

If there are two certificates with the same wildcard definition inside a certificate file, I would like to be able to ignore the expired certificate automatically, as the common web browsers will allow this as well.

**Describe alternatives you've considered**

The certificate file could be regenerated to only include the valid certificate, but this might not be under my control.

**Comment by matteocorti** [comment]
Dear Stefan,

Makes sense. Do you have an example that I could use for testing?

Matteo

**Comment by stefan6419846** [comment]
As I do not have a public demo, I just sent you an e-mail to the address in your profile, which includes a sample file.

**Comment by lukastribus** [comment]
I'm not sure I agree.

We are using this plugin to check for SSL misconfiguration.

check_ssl_cert already ignores if the server sends the root CA with the chain, which is completely useless and only leads to slowdowns. The intermediate certificate is required, not the root CA.

Now we are talking about ignoring expired certificates.

Whether those misconfigurations lead to browser errors or "only" slowdowns and compatibility issues with software other than browser, I want to be able to detect all of it in my monitoring, because that is the point of monitoring those SSL services.

**Comment by matteocorti** [comment]
Dear Lukas

> I'm not sure I agree.
> 
> We are using this plugin to check for SSL misconfiguration.
> 
> check_ssl_cert already ignores if the server sends the root CA with the chain, which is completely useless and only leads to slowdowns. The intermediate certificate is required, not the root CA.

You are right. I could issue at least a warning (and then add an option to ignore it if needed).
 
> Now we are talking about ignoring expired certificates.

Yes and no: the plugin checks a file with two certificates: they should at least be checked separately.

> Whether those misconfigurations lead to browser errors or "only" slowdowns and compatibility issues with software other than browser, I want to be able to detect all of it in my monitoring, because that is the point of monitoring those SSL services.

This is also my idea. But I would like to consider the case, and maybe add an option to ignore the problem if the user wants.

But I agree with you. The default should be the correct case (both for the CA as for the multiple certificates)

**Comment by stefan6419846** [comment]
> Thanks. I didn't receive it. Can you please try again?

Done.

> I'm not sure I agree.
> 
> We are using this plugin to check for SSL misconfiguration.
> 
> check_ssl_cert already ignores if the server sends the root CA with the chain, which is completely useless and only leads to slowdowns. The intermediate certificate is required, not the root CA.
> 
> Now we are talking about ignoring expired certificates.
> 
> Whether those misconfigurations lead to browser errors or "only" slowdowns and compatibility issues with software other than browser, I want to be able to detect all of it in my monitoring, because that is the point of monitoring those SSL services.

This probably depends on the use-case (in my case: checking for expiring certificates in the near future) and making this an option which has to be enabled explicitly should not be an issue for me.

**Comment by matteocorti** [comment]
Mmmm google.com is also delivering the root cert. I am not really sure which the default should be:

 * issue a CRITICAL or WARNING if the root cert is delivered (and add an option --allow-root-certificate to ignore the issue)
 * add an option --check-chain and issue the CRITICAL or WARNING if specified.

**Comment by lukastribus** [comment]
Thinking about this some more, it's actually not that straightforward.

A new CA (such as Google or Let's Encrypt) will have it's Root CA crosssigned by an existing CA. That is the only way to bootstrap a CA (or a root cert renewal).

For example:
Googles `GTS Root R1` is crosssigned by `GlobalSign Root CA`

`GTS Root R1` must be provided by the TLS server, so that clients that only have `GlobalSign Root CA` in the root CA store can validate the certificate.

We could check how "Chain issues" on `sslabs.com` or `testssl.sh` works, but the increased complexity may not be worth it.

**Comment by matteocorti** [comment]
From https://success.qualys.com/support/s/article/000003197

> **Instructions**
> When scanning through [SSL Labs](https://www.ssllabs.com/ssltest/), it shows "Chain issues  Contains anchor"
> 
> It means that you have added Intermediate as well as Root CA, when you only need the Intermediate as the client will already have Root CA (will be already trusted by browser in browser certificate store).
> You can get the same info using openssl command:
> 
> ```
> echo "" | openssl s_client -connect [test.stomt.com](http://test.stomt.com/):443 2>&1 | grep -A 6 "Certificate chain"
> ```
> 
> It's not an issue in the sense that the anchor is not allowed, but that the extra certificate (which serves no purpose) is increasing the handshake latency. 
> Because of TCP slow start, the first bytes on a connection are the slowest. Hence, you can minimize the size of the handshake so that HTTP bytes can start flowing as soon as possible. So the issue is not so much "can the extra certificate fit into the initial window" (it most likely can, even with the old setting of 3 network segments), but "what other, more useful, data could we be sending instead".

As this is not an issue, I would just issue a warning in verbose mode.

**Comment by lukastribus** [comment]
> As this is not an issue, I would just issue a warning in verbose mode.

Yes, I agree.

**Comment by matteocorti** [comment]
@stefan6419846 I got your file, thanks. A quick fix would be to ignore an error if a valid certificate was already parsed. But this would depend on the order of the certificates in the file. A better solution (which I am tending to implement) will require to buffer all the errors.

Anyway: I have the same doubt as above:
 - I could just issue a warning in verbose mode
 - I could issue a CRITICAL state and add a command line option to ignore the problem

**Comment by matteocorti** [comment]
I just published a new release with the following changes:
 * if multiple certificate are present: the expired ones are ignored if at least one valid certificate is present in the chain (not nice, but accepted by the browsers). A warning is issued in verbose mode
 * if the root certificate is unnecessarily present in the chain, a warning is issued in verbose mode
 * if ```--check-chain``` is specified, the script will exit with a CRITICAL status if one of both cases (root cert or double certificate) is present in the chain.

**Comment by lukastribus** [comment]
I don't think this is working quite right:

```
$ check_ssl_cert -w 3 -c 1 -H github.com --check-chain -v
TLS renegotiation OK
The certificate for this site contains a Subject Alternative Name extension
Certificate element 1 (github.com) is valid for 160 days
OCSP check for element 1 OK
Certificate element 2 (DigiCert TLS Hybrid ECC SHA384 2020 CA1) is valid for 3111 days
OCSP check for element 2 OK
Both a valid and an expired certificate were found
CRITICAL error: Both a valid and an expired certificate were found
Both a valid and an expired certificate were found
CRITICAL error: Both a valid and an expired certificate were found
The certificate was successfully verified
The certificate contains signed certificate timestamps (SCT)
The certificate validity (365) is shorter then the maximum (397)
SSL_CERT CRITICAL github.com: Both a valid and an expired certificate were found|days_chain_elem1=160;3;1;; days_chain_elem2=3111;3;1;;
Error(s):
    SSL_CERT CRITICAL github.com: Both a valid and an expired certificate were found
    SSL_CERT CRITICAL github.com: Both a valid and an expired certificate were found
$
```

**Comment by matteocorti** [comment]
I'll take a look

**Comment by matteocorti** [comment]
Mmm I see two problems:
 * There are not "two" certificates
 * I should just check for expired certificates and not certificates which do not comply with --critical and --warning
Or do you see the second issue differently?

**Comment by matteocorti** [comment]
The problem was in the handling of a loop I had a wrong idea :-)
Fix coming soon

**Comment by lukastribus** [comment]
I think line 2216 still contains the debug string `XX 100`

```
$ ./check_ssl_cert -V
check_ssl_cert version 2.51.0
$ ./check_ssl_cert -H incomplete-chain.badssl.com
XX 100
SSL_CERT CRITICAL *.badssl.com: x509 certificate element 1 (*.badssl.com) is expired (was valid until May 17 12:00:00 2022 GMT, 142 days ago)|days_chain_elem1=-142;20;15;;
$
```

**Comment by matteocorti** [comment]
@lukastribus Thanks for the suggestions and debugging (and sorry for the mess ...)

**Comment by lukastribus** [comment]
It's always a pleasure discussing improvements here with you regarding this excellent plugin, so thank you for that :)
