### ISSUE TITLE
SNI Problems

### ISSUE THREAD

**Issue by matteocorti** [matteocorti/check_ssl_cert#42]
See https://sni.velox.ch for a list of SNI examples.

```
./check_ssl_cert -H alice.sni.velox.ch --ignore-ocsp -n bob.sni.velox.ch --Atlantis -n carol.sni.velox.ch
```
issues a critical status (which is correct) but with only one alternative name

```
./check_ssl_cert -H alice.sni.velox.ch --ignore-ocsp -n bob.sni.velox.ch --altnames -d
```

The result is OK as `bob.sni.velox.ch` is used for `-servername ` but `bob` is not in the certificate delivered for `alice`

**Comment by matteocorti** [comment]
At the moment the SSL provider for this site (and ours) (QuoVadis) has problems with OCSP (for this reason all the tests use `--ignore-ocsp`

**Comment by tinuzz** [comment]
Please see my comment on commit 2f3d8bc. I think this fix is wrong and it _breaks_ SNI checks rather than fixing anything.

Regards,
Martijn.
