### ISSUE TITLE
Problems working in FreeBSD jail

### ISSUE THREAD

**Issue by Peter2121** [matteocorti/check_ssl_cert#430]
**Describe the bug**

`check_ssl_cert` does not work correctly inside FreeBSD jail

**To Reproduce**

Start `check_ssl_cert` inside FreeBSD jail, for example:
`./check_ssl_cert -H 172.17.14.12 -c 10 -w 29 -t 20 -P h2`

**Expected behavior**

The certificate is OK, so `SSL_CERT OK` is expected

**System (please complete the following information):**

 - OS: FreeBSD (jail)
 - OS version: 13.1
 - check_ssl_cert version: 2.54.0
 - OpenSSL version (```openssl version```): 1.1.1o

There are two problems on FreeBSD:

1. `nmap` started with default arguments does not work inside jails. To workaround the problem, one should use `--unprivileged` option

2. `tr` does not work correctly with binary files. To workaround the problem one should set `LC_ALL=C` environment variable.

Everything seems to be working correctly after applying the patch provided. Probably, there is a more elegant way to fix the problems ;)

[check_ssl_cert.patch.txt](https://github.com/matteocorti/check_ssl_cert/files/10091139/check_ssl_cert.patch.txt)

**Comment by matteocorti** [comment]
Thanks! I just have to check if the ```--unpriviledged``` option is always available.

**Comment by matteocorti** [comment]
Fixed in 2.55.0
