### ISSUE TITLE
Support "--protocol dns" for DNS-over-TLS

### ISSUE THREAD

**Issue by gloomytrousers** [matteocorti/check_ssl_cert#433]
**Is your feature request related to a problem? Please describe.**

I've just implemented a DNS-over-TLS (DoT) listener in BIND (supported from [BIND 9.18](https://bind9.readthedocs.io/en/v9_18_4/notes.html#notes-for-bind-9-18-0)). I would like to check the certificate using this plugin.

**Describe the solution you'd like**

The `--protocol` argument should support a new value, probably `dns` or `dot`.

**Describe alternatives you've considered**

`--protocol https` appears to work correctly for this case (perhaps the proposed `dns` value should be an alias for this) - it's not obvious though, I only discovered this by accident.

**Additional context**

I haven't tried DNS-over-HTTP (yet) but I assume `--protocol https` would work fine, and would be an obvious value to choose in this case.

**Comment by matteocorti** [comment]
https://en.m.wikipedia.org/wiki/DNS_over_TLS

**Comment by matteocorti** [comment]
Just published version 2.57.0 with support for DNS over TLS. Let me know if it works as itended

**Comment by gloomytrousers** [comment]
Thank you, that was quick! It appears to work perfectly.
