### ISSUE TITLE
stray backslashes

### ISSUE THREAD

**Issue by waja** [matteocorti/check_ssl_cert#435]
In Debian was introduced `grep` 3.8, which changed it's behaviour [cause](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1019724#10):

>   Regular expressions with stray backslashes now cause warnings, as
  their unspecified behavior can lead to unexpected results.
  For example, '\a' and 'a' are not always equivalent
  <https://bugs.gnu.org/39678>.  Similarly, regular expressions or
  subexpressions that start with a repetition operator now also cause
  warnings due to their unspecified behavior; for example, *a(+b|{1}c)
  now has three reasons to warn.  The warnings are intended as a
  transition aid; they are likely to be errors in future releases.

This also affects `check_ssl_cert` and we got a [patch](https://salsa.debian.org/nagios-team/nagios-plugins-contrib/-/merge_requests/7.patch) against 2.27. Unfortunately it does not apply cleanly against `master`. It would be cool to get this fixed, cause it might hit `check_ssl_cert` sometime in the future (when this `grep` variant is rolling more and more into production).

Thanks Jan

**Comment by matteocorti** [comment]
Dear Jan

The issue is known and several stray backslashes were already removed.

I'll take a look

Matteo

**Comment by matteocorti** [comment]
Dear Jan

I fixed another one but should now be OK

Can you please check with the latest version?

Matteo

**Comment by waja** [comment]
jepp ... should be all fixed. thanks!

**Comment by matteocorti** [comment]
Thanks anyway for the patch!
