### ISSUE TITLE
multiple issuer URIs breaking OCSP revokation checking

### ISSUE THREAD

**Issue by ponchofiesta** [matteocorti/check_ssl_cert#46]
OCSP revokation checking breaks if there are multiple issuer URIs. You would need to use only one of them or some kind of loop.

This is the part of the debug log (with curl output)
```
[DBG] OCSP: fetching issuer certificate http://cdp1.pca.dfn.de/tu-berlin-ca/pub/cacert/cacert.crt
http://cdp2.pca.dfn.de/tu-berlin-ca/pub/cacert/cacert.crt to /tmp/check_ssl_cert0BdFcl
curl: (3) Illegal characters found in URL
[DBG] OCSP: issuer certificate type:  empty
SSL_CERT UNKNOWN XXX.de: Unable to fetch OCSP issuer certificate.
```

For now I fixed it by adding this before line 1626: `if [ -z "${ISSUER_CERT}" ]; then`:
```
ISSUER_URI=$(echo "${ISSUER_URI}" | head -n1)
```

**Comment by matteocorti** [comment]
Thanks. I fixed it and released a new version. A solution checking all the URIs in case one of them is not working could be better but for the moment this will work.
