### ISSUE TITLE
proxy with no-proxy-s_client

### ISSUE THREAD

**Issue by exodus1984** [matteocorti/check_ssl_cert#467]
When using a proxy it should be possible to enable no-proxy-s_client.
At the moment I had to add "export http_proxy=http://..." to the script and start with "--no-proxy-s_client"

no-proxy_s_client imo != no-proxy :)

If I run with no-proxy-s_client and proxy I get "Only one of --proxy or --no_proxy can be specified"

VERSION=2.71.0

Regards! :)

**Comment by matteocorti** [comment]
Fixed with release 2.72.0
