### ISSUE TITLE
No longer able to use pattern to match the CN

### ISSUE THREAD

**Issue by variablenix** [matteocorti/check_ssl_cert#47]
I recently updated openssl to the latest version 1.1.0.e. Since the update I've had strange SSL issues with almost everything depending on SSL. I have multiple virtual hosts on a single box and have been using `check_ssl_cert` to validate each sub/domain's SSL certificates using

`check_ssl_cert -H domain4.net -n domain4.net` 

This has all been successful prior to updating openssl where `check_ssl_cert` would return an `OK` status. Now since the openssl update `check_ssl_cert` is failing for any domain **except** the primary domain name that shows up in reverse DNS.

```
SSL_CERT CRITICAL domain4.net: invalid CN ('*.maindomain.net' does not match 'domain4.net')|days=1067;;;;
```

It seems that using `-n` should still continue to return `OK` statuses, but I am not sure what exactly changed with openssl that would suddenly cause this. 
```
  -n,--cn name               pattern to match the CN of the certificate (can be specified multiple times)
```

I have not had success even with the latest `check_ssl_cert-1.44.0` release.

**Comment by matteocorti** [comment]
Hi

Problem confirmed on Debian with 1.1.0e. I'll check what the problem is ...

Matteo

**Comment by matteocorti** [comment]
The problem does not seem related to the plugin but with this site and the new OpenSSL

```
$ /usr/bin/openssl s_client   -connect domain4.net:443 
CONNECTED(00000003)
3072903488:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../ssl/record/rec_layer_s3.c:1385:SSL alert number 80
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 176 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1493731057
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```
