### ISSUE TITLE
Timeout not affecting Check SSL Labs?

### ISSUE THREAD

**Issue by ChiyoDragon** [matteocorti/check_ssl_cert#472]
**Describe the bug**

When performing a check against SSL Labs using the script, it has been observed that the timeout occurs around 60 seconds even though the timeout has been explicitly set to 300 seconds in the script. This behavior is inconsistent with the expected behavior where the script should wait for 300 seconds before timing out.

**To Reproduce**
`/usr/lib/nagios/plugins/check_ssl_cert.sh -H xxx.com --check-ssl-labs A  --timeout 300 `

Steps to reproduce the behavior.

**Expected behavior**

Possibility to set the timeout also for check ssl labs

**System (please complete the following information):**

 - OS: Debian 12
 - check_ssl_cert version: 2.7.4

**Additional context/output**

`Timeout after 56 seconds (SSL Lab assesstment)`

**Comment by matteocorti** [comment]
Thanks for the report.

Would it be possible to get a copy of the debugging output? If possible with the timestamps?

```
--debug --debug-time 
```


Thanks
