### ISSUE TITLE
Plugin run into timeout

### ISSUE THREAD

**Issue by fluxX04** [matteocorti/check_ssl_cert#49]
Newest version of the plugin.
Debian: 8.8
Nagios Version: 4.2.4

The plugin runs always into a timeout.
Over the commandline:
`sudo -u nagios ./check_ssl_cert -H hostname`
 working fine and i get a response but when nagios itself executes the command i get the error
`(Service check timed out after 60.01 seconds)`

Command:
```bash
define command{
	command_name	check_ssl_cert
	command_line	$USER1$/check_ssl_cert -H hostname
}
```
(defined already the hostname in the command to be sure it's not a other problem)

Debug:
```
**** BEGIN MACRO PROCESSING ***********
'$USER1$/check_ssl_cert -H hostname'
Done.  Final output: '/usr/local/nagios/libexec/check_ssl_cert -H hostname'
**** END MACRO PROCESSING *************
```

All other commands are working fine.

Any solutions?
Greetz

**Comment by matteocorti** [comment]
Hi

actually there should be nothing different by executing the plugin in Nagios or on the command line. As the plugin is a Shell script and not a Perl script we can also exclude the known problems with embedded Perl.

You could try [capture_plugin.pl](http://www.waggy.at/nagios/capture_plugin.htm) and configure the plugin with the `-d` option to see if there is something suspicious in the log files.

**Comment by fluxX04** [comment]
Hi,

thanks for the response! Yeah there should be no difference and thats the strange thing.
I tried the caputre_plugin.pl but the plugin didn't returend an output into captured-plugins.log
But again when i execute it from the commandline it works and an output is in the log file.
To test if i configure the capture_plugin.pl right, i added it to other nagios commands and they worked fine and returned an output into the log file.

Debug:
```
Processing: '$USER1$/capture_plugin.pl $USER1$/check_ssl_cert -d -H hostname'
Done.  Final output: '/usr/local/nagios/libexec/capture_plugin.pl /usr/local/nagios/libexec/check_ssl_cert -d -H hostname'
```
I think the plugin gets executed because there are some tmp files in `/tmp/` from the check_ssl_cert plugin also the downloaded cert. But idk why nagios says that the plugin timed out.

Greetz

**Comment by matteocorti** [comment]
Actually is pretty strange but without additional information I cannot do much. As the plugin is running on the command line I see no reason why it should not work. Can you please try to execute it from another directory with the full path (as done by Nagios)?
