### ISSUE TITLE
check_ssl_cert - 2229: verbose: not found

### ISSUE THREAD

**Issue by sts** [matteocorti/check_ssl_cert#494]
I'm getting the following error while an ocsp server returns an internalerror:

./check_ssl_cert: 2229: verbose: not found

running v2.78.0, https://github.com/matteocorti/check_ssl_cert/blob/v2.78.0/check_ssl_cert#L2229

**Comment by matteocorti** [comment]
You should provide more context:

- Debugging output if possible
- Version of the plugin so that I can see what happens at line 2229

**Comment by sts** [comment]
@matteocorti I updated my initial comment, looks like verbose is not a function in the code.

**Comment by matteocorti** [comment]
Thanks. Fixed!

**Comment by sts** [comment]
Awesome, thanks @matteocorti!
