### ISSUE TITLE
feature: sips protocol (TCP port 5061)

### ISSUE THREAD

**Issue by lukastribus** [matteocorti/check_ssl_cert#497]
**Is your feature request related to a problem? Please describe.**

A want to check TLS certificates of SIPS endpoints (implicit TLS on TCP port 5061).

**Describe the solution you'd like**

Add SIPS protocol with default TCP port 5061.

**Describe alternatives you've considered**

Just using a different protocol and specifying the port (see below), but it's not "nice".

**Additional context**

Example Host: `sip.pstnhub.microsoft.com`
Example Port: `5061` (this is the default port for SIPS)

Here's an example of HTTPS and FTPS checks against the example host:

    $  check_ssl_cert -H sip.pstnhub.microsoft.com --port 5061
    SSL_CERT OK - sip.pstnhub.microsoft.com:5061, https, x509 certificate 'sip.pstnhub.microsoft.com' from 'Microsoft Corporation' valid until Dec 25 07:23:50 2024 GMT (expires in 347 days)|days_chain_elem1=347;20;15;; days_chain_elem2=956;20;15;;
    $ check_ssl_cert -H sip.pstnhub.microsoft.com --port 5061 --protocol ftps
    SSL_CERT OK - sip.pstnhub.microsoft.com:5061, ftps, x509 certificate 'sip.pstnhub.microsoft.com' from 'Microsoft Corporation' valid until Dec 25 12:56:48 2024 GMT (expires in 348 days)|days_chain_elem1=348;20;15;; days_chain_elem2=956;20;15;;
    $

**Comment by matteocorti** [comment]
Fixed in d05342f

**Comment by lukastribus** [comment]
Thank you!
