### ISSUE TITLE
Unable to fetch OCSP issuer certificate

### ISSUE THREAD

**Issue by thaurial** [matteocorti/check_ssl_cert#50]
Hi,

I'm Using VERSION=1.46.0.
We're trying to check several webservers internally with your script. Unfortunately, using certs of the internal CA is causing an issue:
"SSL_CERT UNKNOWN weberserver1.lan: Unable to fetch OCSP issuer certificate"

Using the command with the parameter "-r" doesnt fix, as we referred to a local path where the ROOTCA.cer file is located.

Could you help us here? I guess the OCSP issue didnt occur before Version 1.46

**Comment by matteocorti** [comment]
Hi

If the certificate chain specifies an OCSP server than the plugin tries to contact it and check if the certificate is revoked.

Run the plugin with the -d option and check the value of OCSP_URI

Or run the plugin with the --ignore-ocsp option

**Comment by thaurial** [comment]
Thanks for the fast reply,
I could not find out why the OSCP is used. Using the -d shows an empty value:

"[DBG] OCSP_URI   ="

Ignoring the OSCP brings me to a verification issue, which I think can be solved by adding the certs to the openssl keychain. I have to read how to do this on centos, but shouldn't be an issue.

**Comment by matteocorti** [comment]
It's strange, as the value is empty, OCSP should not be checked... I'll take a look.

Could you please attach the complete output with -d?

**Comment by thaurial** [comment]
here we go:

[DBG] ROOT_CA = -CAfile /tmp/cert/ROOTCA.cer
expect available (/usr/bin/expect)
timeout available (/usr/bin/timeout)
[DBG] perl available: /usr/bin/perl
[DBG] date available: /bin/date
found GNU date with timestamp support: enabling date computations
[DBG] check_ssl_version: 1.46.0
[DBG] OpenSSL binary: /usr/bin/openssl
[DBG] OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
[DBG] System info: Linux nagios.lan 2.6.32-696.1.1.el6.x86_64 #1 SMP Tue Apr 11 17:13:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[DBG] Date computation: GNU
[DBG] '/usr/bin/openssl s_client' supports '-servername': using -servername webserver1.lan
downloading certificate to /tmp
[DBG] executing with timeout (15s): echo 'Q' | /usr/bin/openssl s_client   -connect webserver1.lan:443 -servername webserver1.lan -verify 6 -CAfile /tmp/cert/ROOTCA.cer    2> /tmp/check_ssl_cert_2JTZynJ 1> /tmp/check_ssl_cert_287X4q2
[DBG]   /usr/bin/timeout 15 /bin/sh -c "echo 'Q' | /usr/bin/openssl s_client   -connect webserver1.lan:443 -servername webserver1.lan -verify 6 -CAfile /tmp/cert/ROOTCA.cer    2> /tmp/check_ssl_cert_2JTZynJ 1> /tmp/check_ssl_cert_287X4q2"
[DBG] storing a copy of the retrieved certificate in webserver1.lan.crt
[DBG] storing a copy of the OpenSSL errors in webserver1.lan.error
parsing the certificate file
[DBG]  subject= C = lu, ST = Luxembourg, L = Luxembourg, O = PiPaPo, OU = IT, CN = webserver1.lan
[DBG] CN         = webserver1.lan
[DBG] CA_O       = Pipapo
[DBG] CA_CN      = SUBCAV1
[DBG] SERIAL     = 5A000002F676412333330005000002F6
[DBG] OCSP_URI   =
[DBG] ISSUER_URI = LDAP:///CN=SUBCAV1,CN=AIA,CN=Public Key Services,CN=Services,CN=Configuration,DC=DROOT,DC=LU?cACertificate?base?objectClass=certificationAuthority
[DBG]     Signature Algorithm: sha256WithRSAEncryption
[DBG] Date computations: GNU
The certificate will expire in 708 day(s)
[DBG] Checking expiration date
[DBG] executing: /usr/bin/openssl x509 -in /tmp/check_ssl_cert_287X4q2 -noout -checkend 5184000
[DBG] executing: /usr/bin/openssl x509 -in /tmp/check_ssl_cert_287X4q2 -noout -checkend 7776000
[DBG] OCSP: fetching issuer certificate LDAP:///CN=SUBCAV1,CN=AIA,CN=Public Key Services,CN=Services,CN=Configuration,DC=DROOT,DC=LU?cACertificate?base?objectClass=certificationAuthority to /tmp/check_ssl_cert_2lKt7F1
[DBG] OCSP: issuer certificate type:  HTML document text
SSL_CERT UNKNOWN webserver1.lan: Unable to fetch OCSP issuer certificate.

**Comment by matteocorti** [comment]
The problem is that the ISSUER_URI is an `ldap://` URI and the script assumes that the URI is HTTP or HTTPS.

I will try to fix it as soon as possible

**Comment by matteocorti** [comment]
I just pushed a new version, could you please test it?

**Comment by thaurial** [comment]
Thanks for the edit. I'm now getting the same output as using the `--ignore-ocsp` Option.
I'll investigate on howto add the local issuer as trusted now.

many thanks

**Comment by matteocorti** [comment]
OK let me know if there still are problems
