### ISSUE TITLE
Check for missing SAN

### ISSUE THREAD

**Issue by willemdh** [matteocorti/check_ssl_cert#51]
Hello,

Thanks for this plugin, seems very useful. I was wondering if it is possible already to check for missing SAN attributes. As you might know Google has recently changes it's Chrome policy and no longer allows certificates who have no SAN. This is the error generated in Chrome:

> Subject Alternative Name Missing
> The certificate for this site does not contain a Subject Alternative Name extension containing a domain name or IP address.

For now it's possible to ignore this issue, see https://www.chromium.org/administrators/policy-list-3#EnableCommonNameFallbackForLocalAnchors

But somehwere at the end of 2017 this will no longer be possible, so I'd love to monitor for missing SAN's. :)

Grtz

Willem

**Comment by matteocorti** [comment]
Sure, do you have an example with a _bad_ certificate that I could youse for testing?

**Comment by willemdh** [comment]
@matteocorti Man, you are fast! :) I'll test asap.

**Comment by matteocorti** [comment]
I had a short break and this was pretty fast to fix :-)

Anyway, it makes sense to implement it since Chrome will complain. But I did not find any official reason for the decision. Why is a certificate without SubjectAlternativeName per definition bad?

**Comment by willemdh** [comment]
Well it's a whole story, but in short it has something to with a baseline requirements for certificates. Subject AlternativeName replaces the common name.

See http://unmitigatedrisk.com/?p=381 for more information.

And also https://nameconstraints.bettertls.com/
