### ISSUE TITLE
Options missing arguments shouldn't include the pipe in their UNKNOWN response

### ISSUE THREAD

**Issue by peternewman** [matteocorti/check_ssl_cert#516]
**Describe the bug**

On Nagios if you've failed to pass in an argument, the check currently ends up in the following state:

> Status Information: SSL_CERT UNKNOWN: '-p
> Performance Data: --port' requires an argument

**To Reproduce**

Steps to reproduce the behavior.
`check_ssl_cert -H localhost -p`

**Expected behavior**

This output, or something similar (e.g. "or" or "/" would fix it):
`SSL_CERT UNKNOWN: '-p --port' requires an argument`

**System (please complete the following information):**

 - OS version: [e.g. 22]
 - check_ssl_cert version: 2.41.0
 - OpenSSL version (```openssl version```): [e.g., 3.0.0]

**Additional context/output**

Add any other context or output (e.g., from `check_ssl_cert -d -v`) about the problem here.

Looks to be this:
https://github.com/matteocorti/check_ssl_cert/blob/master/check_ssl_cert#L3091

**Comment by matteocorti** [comment]
Thanks, didn't think about Nagios interpreting the ```|```
