### ISSUE TITLE
rpmbuild error with bad date in %changelog

### ISSUE THREAD

**Issue by nichivo** [matteocorti/check_ssl_cert#517]
**Describe the bug**

Something seems to have changed with 2.83.0 to use full month name in RPM spec file changelog which outputs an `rpmbuild` error and prevents changelogs being added to the RPM as `rpmbuild` seems to only accept short month names.

**To Reproduce**

It has started since 2.83.0:
```
rpmbuild -ba SPECS/check_ssl_cert.spec
error: bad date in %changelog: Tue August 28 2024 Matteo Corti <matteo@corti.li> - 2.83.0-0
```
and affects latest version 2.83.1 too:
```
error: bad date in %changelog: Tue September 10 2024 Matteo Corti <matteo@corti.li> - 2.83.1-0
```
Previous version use short month which work:
```
* Thu Jul  11 2024 Matteo Corti <matteo@corti.li> - 2.82.0-0
```

**Expected behavior**

`rpmbuild` should build an RPM without error with changelogs, which it can do when the months are manually shortened e.g. `August` to `Aug`

**System (please complete the following information):**

 - OS: Rocky
 - OS version: 9
 - check_ssl_cert version: Since 2.83.0
 - OpenSSL version (```openssl version```): N/A

**Additional context/output**

`rpmbuild` on RHEL7 used to fail on this type of error and not produce an RPM, but on RHEL9 it seems to continue? Or maybe now I'm building in `mock` it hides it? Either way, behaviour has changed and `date "+%a %b %d %Y"` style format should probably be used. Thanks!

**Comment by matteocorti** [comment]
Thanks, fixed in [d3d0375](https://github.com/matteocorti/check_ssl_cert/commit/d3d0375a8c3f87d0eefed0d0441ef809913b9367)
