### ISSUE TITLE
SSL_CERT UNKNOWN: --host can be specified only once

### ISSUE THREAD

**Issue by naiz0** [matteocorti/check_ssl_cert#520]
Hi

I downloaded the very new version 2.84.2.
I tested it with:
`./check_ssl_cert -H orf.at`
and got the answer:
`SSL_CERT UNKNOWN: --host can be specified only once`

The previous version was good:
```
$ /usr/lib/nagios/plugins/check_ssl --host orf.at
SSL_CERT OK - orf.at:443, https, x509 certificate '*.orf.at' (orf.at) from 'Entrust, Inc.' valid until Jun 30 08:09:15 2025 GMT (expires in 275 days)|days_chain_elem1=275;20;15;; days_chain_elem2=2260;20;15;; days_chain_elem3=2262;20;15;;
```

```
$ /usr/lib/nagios/plugins/check_ssl --version
check_ssl_cert version 2.83.1
```

**System:**

 - OS: openSuse
 - OS version: 15.6
 - check_ssl_cert version: 2.84.2
 - OpenSSL version (```openssl version```): OpenSSL 1.1.1l-fips  24 Aug 2021 SUSE release 150500.17.34.1

**Comment by matteocorti** [comment]
I cannot reproduce it:

```
$ ./check_ssl_cert -H orf.at
SSL_CERT OK - orf.at:443, https, x509 certificate '*.orf.at' (orf.at) from 'Entrust, Inc.' valid until Jun 30 08:09:15 2025 GMT (expires in 275 days)|days_chain_elem1=275;20;15;; days_chain_elem2=2260;20;15;; days_chain_elem3=2262;20;15;;
$ ./check_ssl_cert --version
check_ssl_cert version 2.84.2

Can it be that you have a host defined in a configuration file?

**Comment by matteocorti** [comment]
You are still using the buggy 2.84.2 version (look at the ```--version``` output

**Comment by matteocorti** [comment]
I cannot reproduce it but I'll check as soon as possible

**Comment by matteocorti** [comment]
Strange, I'll try to test next week, I first need to install one of both ...

**Comment by matteocorti** [comment]
I finally managed to [install openSUSE with Parallels 20](https://forum.parallels.com/threads/opensuse-will-not-install-on-parallels-20-on-mac-studio.365155/) on my mac and can reproduce the problem.

**Comment by matteocorti** [comment]
got the problem: on openSUSE ```HOST``` already defined as the host name.
