### ISSUE TITLE
[2.84.3] regression: --dane broken

### ISSUE THREAD

**Issue by bratkartoffel** [matteocorti/check_ssl_cert#521]
**Describe the bug**

`--dane` is broken

**To Reproduce**

```
$> ./check_ssl_cert -H orf.at
SSL_CERT OK - orf.at:443, https, x509 certificate '*.orf.at' (orf.at) from 'Entrust, Inc.' valid until Jun 30 08:09:15 2025 GMT (expires in 274 days)|days_chain_elem1=274;20;15;; days_chain_elem2=2259;20;15;; days_chain_elem3=2261;20;15;;

$> ./check_ssl_cert -H orf.at --dane
SSL_CERT UNKNOWN:  can be specified only once

$> ./check_ssl_cert -H orf.at --dane 211
SSL_CERT UNKNOWN:  can be specified only once
```

**Expected behavior**

Check should succeed with dane enabled.
2.83.1 is fine.

**System (please complete the following information):**

 - OS: Alpine
 - OS version: 3.20
 - check_ssl_cert version: 2.84.3
 - OpenSSL version: 3.3.2

**Comment by netchild** [comment]
Workaround: comment-out the `check_option"${DANE}" "--dane"` line.
