### ISSUE TITLE
No certificate returned on loadbalanced AWS sites

### ISSUE THREAD

**Issue by SnakeMind** [matteocorti/check_ssl_cert#53]
Hi,

When checking a site that is hosted on AWS and is using loadbalancing, the check returns the error that the certificate is not returned.

/usr/lib64/nagios/plugins/check_ssl_cert -H *an awshosted url* -c 30 -w 60 -v -A
expect not available
timeout available (/usr/bin/timeout)
found GNU date with timestamp support: enabling date computations
downloading certificate to /tmp
Error: verify depth is 6
SSL_CERT CRITICAL *an awshosted url*: No certificate returned

Is there a way to get around this? 
I have tried for several sites hosted on AWS, all returning in the same result.

**Comment by matteocorti** [comment]
Hi

Can you please try with the debug option (-d)? With 'aws.amazon.com' I get no problems. Would it be possible to know the host you are testing?

Matteo

**Comment by SnakeMind** [comment]
Hi,

This is the output, I'll sent you a pm for the hosts(s) thanks to the policies of our clients ;-)

/usr/lib64/nagios/plugins/check_ssl_cert -H *an aws host* -c 30 -w 60 -v -A -d
[DBG] ROOT_CA =
expect available (/usr/bin/expect)
timeout available (/usr/bin/timeout)
[DBG] perl available: /usr/bin/perl
[DBG] date available: /usr/bin/date
found GNU date with timestamp support: enabling date computations
[DBG] check_ssl_version: 1.48.0
[DBG] OpenSSL binary: /usr/bin/openssl
[DBG] OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
[DBG] System info: Linux servername 3.10.0-514.21.2.el7.x86_64 #1 SMP Sun May 28 17:08:21 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
[DBG] Date computation: GNU
[DBG] '/usr/bin/openssl s_client' supports '-servername': using -servername *an aws host*
downloading certificate to /tmp
[DBG] executing with timeout (15s): echo 'Q' | /usr/bin/openssl s_client   -connect *an aws host*:443 -servername *an aws host* -verify 6     2> /tmp/check_ssl_certFZ1DTu 1> /tmp/check_ssl_certxJKf8G
[DBG]   /usr/bin/timeout 15 /bin/sh -c "echo 'Q' | /usr/bin/openssl s_client   -connect *an aws host*:443 -servername *an aws host* -verify 6     2> /tmp/check_ssl_certFZ1DTu 1> /tmp/check_ssl_certxJKf8G"
[DBG] storing a copy of the retrieved certificate in *an aws host*.crt
[DBG] storing a copy of the OpenSSL errors in *an aws host*.error
Error: verify depth is 6; getaddrinfo: Name or service not known; connect:errno=0
SSL_CERT CRITICAL *an aws host*: No certificate returned

**Comment by matteocorti** [comment]
Can you please try to execute the connect manually?

```
 /usr/bin/openssl s_client -connect an aws host:443 -servername an aws host -verify 6
```

**Comment by SnakeMind** [comment]
Seems openssl is not able to get the certificate then? hm...

/usr/bin/openssl s_client -connect *an aws host*:443 -servername *an aws host* -verify 6
verify depth is 6
getaddrinfo: Name or service not known
connect:errno=0

**Comment by matteocorti** [comment]
Ok it seems that OpenSSL is not able to resolve the host name.

Can you try with

```
host awshostname
```

**Comment by SnakeMind** [comment]
I'll paste those results again in the mail, does look like an issue there thanks to the balancing.
It doesn't seem to resolve with host, but when using curl there is no issue.

**Comment by matteocorti** [comment]
Ok. I close the issue and we can continue the analysis via mail ...
