### ISSUE TITLE
SSL_CERT CRITICAL: Can't get connection fd

### ISSUE THREAD

**Issue by alexs77** [matteocorti/check_ssl_cert#57]
Hi

I updated check_ssl_cert to v1.51.0 from this repo (before, we had v1.16.1 installed).

Now some of the checks return the following:

    SSL_CERT CRITICAL 192.168.185.112: Can't get connection fd

But this is only returned, when our Icinga installation runs the check. When I run the check manually from an SSH session, it works:

```
root@app2-ewmon-prod ~ # sudo -u icinga /data/icinga/libexec/check_ssl_cert -H 192.168.185.112 -w 30 -c 7 --noauth --selfsigned
SSL_CERT OK - X.509 certificate 'mail.scalera.ch' from 'QuoVadis Global SSL ICA G2' valid until Jan 12 08:37:15 2018 GMT (expires in 151 days)|days=151;30;7;;
```

Any idea, why this might be so?

Thanks,
Alexander

**Comment by matteocorti** [comment]
Hi,

which version of OpenSSL are you using? Looking online it seems a (now corrected) bug in OpenSSL while querying OCSP servers.

Matteo

**Comment by alexs77** [comment]
```
root@app2-ewmon-prod ~ # openssl version
OpenSSL 1.0.1 14 Mar 2012

root@app2-ewmon-prod ~ # lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
```

Yeah, I know, a "bit" old…

**Comment by matteocorti** [comment]
Hi the current stable release is 1.0.2l (or better 1.1.0f)

**Comment by alexs77** [comment]
But why is it, that it works when I run the command from a SSH prompt, but not, when Icinga runs the command?

**Comment by matteocorti** [comment]
It might be that icinga has another `PATH` and is using a different OpenSSL version. As the plugin is working on the command line it is difficult to know what icinga is doing differently. Would it be possible to rund the plugin with the `-d` option?
