### ISSUE TITLE
Cannot verify certificate: unable to get local issuer certificate

### ISSUE THREAD

**Issue by netson** [matteocorti/check_ssl_cert#58]
Hi,

I am attempting to use this plugin with Let's Encrypt issued certificates, but I keep running into the same error. At first I thought this was related to my specific certificate, but it seems to be a problem on all LE certificates. For testing, I used the helloworld.letsencrypt.org domain.

Is this a problem with my syntax or with the plugin?

I've tested it with various domains on various servers and have used different servers to test running the command from as well, all with the same result.

Hope you can help!

> root@nagios:/home/myuser# ./check_ssl_cert -H helloworld.letsencrypt.org -c 5 -w 14 -v -d
> [DBG] ROOT_CA =
> expect not available
> timeout available (/usr/bin/timeout)
> [DBG] perl available: /usr/bin/perl
> [DBG] date available: /bin/date
> found GNU date with timestamp support: enabling date computations
> [DBG] check_ssl_version: 1.51.0
> [DBG] OpenSSL binary: /usr/bin/openssl
> [DBG] OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014
> [DBG] System info: Linux nagios 3.13.0-73-generic #116-Ubuntu SMP Fri Dec 4 15:31:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
> [DBG] Date computation: GNU
> [DBG] '/usr/bin/openssl s_client' supports '-servername': using -servername helloworld.letsencrypt.org
> downloading certificate to /tmp
> [DBG] executing with timeout (15s): echo 'Q' | /usr/bin/openssl s_client   -connect helloworld.letsencrypt.org:443 -servername helloworld.letsencrypt.org -verify 6     2> /tmp/check_ssl_certUtfcxw 1> /tmp/check_ssl_certfdDmsm
> [DBG]   /usr/bin/timeout 15 /bin/sh -c "echo 'Q' | /usr/bin/openssl s_client   -connect helloworld.letsencrypt.org:443 -servername helloworld.letsencrypt.org -verify 6     2> /tmp/check_ssl_certUtfcxw 1> /tmp/check_ssl_certfdDmsm"
> [DBG] storing a copy of the retrieved certificate in helloworld.letsencrypt.org.crt
> [DBG] storing a copy of the OpenSSL errors in helloworld.letsencrypt.org.error
> parsing the certificate file
> [DBG]  subject= CN = helloworld.letsencrypt.org
> [DBG] CN         = helloworld.letsencrypt.org
> [DBG] CA_O       = Let's Encrypt
> [DBG] CA_CN      = Let's Encrypt Authority X3
> [DBG] SERIAL     = 03138CE4E010536F7E690296073C556AC9D7
> [DBG] OCSP_URI   = http://ocsp.int-x3.letsencrypt.org
> [DBG] ISSUER_URI = http://cert.int-x3.letsencrypt.org/
> [DBG]     Signature Algorithm: sha256WithRSAEncryption
> [DBG] Date computations: GNU
> The certificate will expire in 50 day(s)
> [DBG] subjectAlternativeName = helloworld.letsencrypt.org
> [DBG] Checking expiration date
> [DBG] executing: /usr/bin/openssl x509 -in /tmp/check_ssl_certfdDmsm -noout -checkend 432000
> [DBG] executing: /usr/bin/openssl x509 -in /tmp/check_ssl_certfdDmsm -noout -checkend 1209600
> [DBG] Checking revokation via OCSP
> [DBG] OCSP: fetching issuer certificate http://cert.int-x3.letsencrypt.org/ to /tmp/check_ssl_certaM7nxr
> [DBG] OCSP: issuer certificate type:  data
> [DBG] OCSP: converting issuer certificate from DER to PEM
> [DBG] OCSP: storing a copy of the retrieved issuer certificate to cert.int-x3.letsencrypt.org
> [DBG] OCSP: host = ocsp.int-x3.letsencrypt.org
> [DBG] openssl ocsp supports the -header option
> [DBG] openssl ocsp -header requires 'key value'
> [DBG] executing /usr/bin/openssl ocsp -no_nonce -issuer /tmp/check_ssl_certaM7nxr -cert /tmp/check_ssl_certfdDmsm  -url http://ocsp.int-x3.letsencrypt.org  -header HOST ocsp.int-x3.letsencrypt.org
> [DBG] OCSP: response = Response Verify Failure
> [DBG] OCSP: response = 140015886833312:error:27069076:OCSP routines:OCSP_basic_verify:signer certificate not found:ocsp_vfy.c:85:
> [DBG] OCSP: response = /tmp/check_ssl_certfdDmsm: good
> [DBG] OCSP: response =  This Update: Aug 13 16:00:00 2017 GMT
> [DBG] OCSP: response =  Next Update: Aug 20 16:00:00 2017 GMT
> [DBG] Error: verify depth is 6
> [DBG] Error: depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
> [DBG] Error: verify error:num=20:unable to get local issuer certificate
> [DBG] Error: verify return:1
> [DBG] Error: depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
> [DBG] Error: verify error:num=27:certificate not trusted
> [DBG] Error: verify return:1
> [DBG] Error: depth=0 CN = helloworld.letsencrypt.org
> [DBG] Error: verify return:1
> [DBG] Error: DONE
> SSL_CERT CRITICAL helloworld.letsencrypt.org: Cannot verify certificate: unable to get local issuer certificate, certificate not trusted|days=50;14;5;;

**Comment by matteocorti** [comment]
Hi

Your OpenSSL does not have the root certificate of Let's Encrypt. You can either download it from https://letsencrypt.org/certificates/ and the use the `--rootcert` option or update the central certificate store of your system.

Matteo

**Comment by netson** [comment]
Thanks, that solved the issue! 👍  Keep up the good work!
