### ISSUE TITLE
Feature Request: Execute "OCSP: fetching issuer certificate" with timeout

### ISSUE THREAD

**Issue by bjoernbessert** [matteocorti/check_ssl_cert#59]
Hi,

Comodo OCSP/CRT servers seem to be down at the moment, therefore the plugin hangs and is only killed by nagios plugin execution timeout. It would ne nice if the timeout parameter would also apply to the OCSP part.

**Comment by vurgun** [comment]
I can confirm the same issue. There is no timeout set on OCSP check part

`[DBG] Checking revokation via OCSP
[DBG] OCSP: fetching issuer certificate http://crt.comodoca.com/COMODORSADomainValidationSecureServerCA.crt to /tmp/check_ssl_certPUjLIy
`

**Comment by matteocorti** [comment]
Yes the timeout should apply to the whole. I will fix as soon as possible
