### ISSUE TITLE
xmpp check not working

### ISSUE THREAD

**Issue by dahabakuk** [matteocorti/check_ssl_cert#67]
hi,
with OpenSSL 1.1.0f  25 May 2017 using --procotol xmpp there is no cert returned.

running bash -x check_ssl_cert shows:

/usr/bin/openssl s_client   -starttls xmpp -connect localhost:5222 -servername xmpphost -verify 6

which does connect, but not return a cert.

using

/usr/bin/openssl s_client   -starttls xmpp -connect localhost:5222 -xmpphost xmpphost -verify 6

a proper cert is returned.

otherwise, good work!

**Comment by dahabakuk** [comment]
for now, i created this dirty fix:

319c319
<             pop3|imap|ftp|ldap)
---
>             pop3|imap|ftp|xmpp|ldap)
323,327d322
< 	    xmpp)
< 		SERVERNAME=$(echo $SERVERNAME | sed 's/-servername/-xmpphost/')
< 		exec_with_timeout "$TIMEOUT" "echo 'Q' | $OPENSSL s_client ${CLIENT} ${CLIENTPASS} -starttls ${PROTOCOL} -connect $HOST:$PORT ${SERVERNAME} -verify 6 ${ROOT_CA} ${SSL_VERSION} ${SSL_VERSION_DISABLED} ${SSL_AU} 2> ${ERROR} 1> ${CERT}"
< 		RET=$?
< 		;;

**Comment by matteocorti** [comment]
` -xmpphost` is not always available. Which version of OpenSSL are you using? On which OS?

**Comment by dahabakuk** [comment]
im using debian stretch with 1.1.0f-3+deb9u1

**Comment by dahabakuk** [comment]
/usr/bin/openssl s_client -starttls xmpp -connect localhost:5222 without xmpphost will not fix it here...
