### ISSUE TITLE
Multiple OCSP responder

### ISSUE THREAD

**Issue by kroomagnon** [matteocorti/check_ssl_cert#72]
Hi,

I found that check_ssl_cert fails with multiple ocsp responders:

```
check_ssl_cert --debug --host netlock.hu
[DBG] OCSP: host = ocsp1.netlock.hu
ocsp2.netlock.hu
ocsp3.netlock.hu

```
I can fix it with addition of "head -n1", but I don't think it's the best way:

```
OCSP_URI="$($OPENSSL ${OPENSSL_COMMAND} ${OPENSSL_PARAMS} -in "${CERT}" -ocsp_uri -noout | head -n1)"
```

**Comment by matteocorti** [comment]
I will write a quick fix as suggested. A loop over all the hosts would be better: I'll put it in the to do list.

**Comment by dilyanpalauzov** [comment]
The ./TODO file contains:
`* Loop over all the provided OCSP hosts (https://github.com/matteocorti/check_ssl_cert/issues/72)`

Is this now implemented and can be removed from the TODO?
