### ISSUE TITLE
Error opening issuer certificate

### ISSUE THREAD

**Issue by flo-assling** [matteocorti/check_ssl_cert#81]
Hi, the plugin was working perfectly for a longer time on CentOS 7.
Since yesterday, I get a timeout, and on manual execution/Ctrl-C the following error:

CSSL_CERT CRITICAL www.mydomain.de: Error opening issuer certificate /tmp/check_ssl_certZgQ1V0
139756719761312:error:02001002:system library:fopen:No such file or directory:bss_file.c:402:fopen('/tmp/check_ssl_certZgQ1V0','r')
139756719761312:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:404:
unable to load certificate|days=884;;;;

**Comment by matteocorti** [comment]
Hi, can you please post the output with -d option?

**Comment by flo-assling** [comment]
I found the issue - it's the ComodoCA which leads to a timeout.
Switched everything to Let's Encrypt, works perfectly again.
Thank you for your very quick reply!


[DBG] executing /usr/bin/openssl ocsp -no_nonce -issuer /tmp/check_ssl_certxtx0Ch -cert /tmp/check_ssl_certLAYg5p  -url http://ocsp.comodoca.com  -header HOST ocsp.comodoca.com
[DBG] OCSP: response = Error connecting BIO
[DBG] OCSP: response = Error querying OCSP responder
[DBG] OCSP: response = 140684828747680:error:0200206E:system library:connect:Connection timed out:bss_conn.c:246:host=ocsp.comodoca.com:80
[DBG] OCSP: response = 140684828747680:error:20073067:BIO routines:CONN_STATE:connect error:bss_conn.c:249:
SSL_CERT CRITICAL www.mydomain.de: Error connecting BIO
Error querying OCSP responder
140361517111200:error:0200206F:system library:connect:Connection refused:bss_conn.c:246:host=ocsp.comodoca.com:80
140361517111200:error:20073067:BIO routines:CONN_STATE:connect error:bss_conn.c:249:|days=285;;;;
