### ISSUE TITLE
Add support to check via IPv4 or IPv6

### ISSUE THREAD

**Issue by imtek** [matteocorti/check_ssl_cert#85]
Is it possible to add a feature to check the certificate via IPv4 or IPv6. By default IPv6 get's preference. 

Would be nice to have an option to check via IPv4 or IPv6, thanks for your efforts!

**Comment by matteocorti** [comment]
OpenSSL does not offer any way to force the version of the IP protocol. I could add support as soon as the used tools will offer the option.

**Comment by imtek** [comment]
Ofcourse this is not something that is done by openssl but purely by your script. Thank you! :)

**Comment by matteocorti** [comment]
My script cannot force other tools to do something. Once I start OpenSSL, OpenSSL creates the network connection. I did not rewrite OpenSSL, I used it.
