### ISSUE TITLE
Check for SNI support in openssl does not work with openssl 1.1.0g

### ISSUE THREAD

**Issue by markuswernig** [matteocorti/check_ssl_cert#96]
Currently, the check for SNI support in openssl is done like this:

```
 if ${OPENSSL} s_client not_a_real_option 2>&1 | grep -q -- -servername ; then
```

With openssl 1.1.0g, this always returns false, even if it does support the flag.

The check should probably be  done like this:
```
if ${OPENSSL} s_client -help 2>&1 | grep -q -- -servername ; then
```
best /markus

**Comment by matteocorti** [comment]
You are most likely using an old version of check_ssl_cert as the check now supports both versions:

`    if ${OPENSSL} s_client -help 2>&1 | grep -q -- -servername || ${OPENSSL} s_client not_a_real_option 2>&1 | grep -q -- -servername; then
`

**Comment by markuswernig** [comment]
On 9/17/18 5:54 PM, Matteo Corti wrote:
> You are most likely using an old version of check_ssl_cert as the check
> now supports both versions:

The one from monitoring-plugins in ubuntu 18.04.1. My bad for not having
checked the versions. Thanks for the heads-up ;-)
