### ISSUE TITLE
CN regex match fails with openssl 1.1.0g

### ISSUE THREAD

**Issue by markuswernig** [matteocorti/check_ssl_cert#97]
In version 1.37.0, when checking certificates against a servername (-n), the regex does no longer match the output from openssl. The reason is that the output format has changed, there is one space less:

OpenSSL 1.0.2g:
openssl x509 -in linuxday.ch.crt -subject -noout -nameopt utf8,oneline,-esc_msb
subject= CN = linuxday.ch

OpenSSL 1.1.0g:
openssl x509 -in linuxday.ch.crt -subject -noout -nameopt utf8,oneline,-esc_msb
subject=CN = linuxday.ch

The regex should therefore now probably be

```
CN="$($OPENSSL x509 -in "${CERT}" -subject -noout -nameopt utf8,oneline,-esc_msb |
        sed -e "s/^.*[[:space:]]*CN[[:space:]]=[[:space:]]//"  -e "s/\/[[:alpha:]][[:alpha:]]*=.*\$//" -e "s/,.*//" )"
```

best /markus

**Comment by matteocorti** [comment]
Hi

Are you really referring to 1.37.0? The current version is 1.73.0.

The current regex is:

```
CN="$($OPENSSL x509 -in "${CERT}" -subject -noout ${OPENSSL_PARAMS} |
            sed -e "s/^.*[[:space:]]*CN[[:space:]]=[[:space:]]//"  -e "s/\\/[[:alpha:]][[:alpha:]]*=.*\$//" -e "s/,.*//" )"
```
